### ISSUE TITLE
Can SigProfilerExtractor extract COSMIC ID signature of GRCh38?

### ISSUE THREAD

**Issue by lincj1994** [AlexandrovLab/SigProfilerExtractor#106]
Hi. I have run SigProfilerMatrixGenerator using the GRCh38 as the reference genome and I found a ID83 matrix was also created. Next I run SigProfilerExtractor using the ID83 matrix to refit the COSMIC ID signature and I got an output. But it seems that COSMIC only provided ID signatures derived from GRCh37. So I dont know if the COSMIC ID signature decomposed by SigProfiler is correct for GRCh38.
Thank you.

**Comment by marcos-diazg** [comment]
Hi and thanks for your interest! In contrast to SBS and DBS signatures, no renormalization for different reference genomes is available for ID signatures, as mentioned in the downloads section of the COSMIC database (https://cancer.sanger.ac.uk/signatures/downloads/).

I hope this helps and please let us know if you have further questions.

**Comment by lincj1994** [comment]
Thanks for your reply. So does that mean we should not use the output of ID83 matrix and ID signature generated by SigProfiler when GRCh38 was used as a reference genome?

**Comment by marcos-diazg** [comment]
Hi again @lincj1994

No, you can perfectly use SigProfilerExtractor for extracting ID signatures from GRCh38 without any problem. COSMIC reference ID signatures were extracted originally from GRCh37 data, but they can be used with GRCh38 too.

I hope this helps! Best,

Marcos
