### ISSUE TITLE
issue about Trancriptional stranded signature

### ISSUE THREAD

**Issue by chujunliu** [AlexandrovLab/SigProfilerExtractor#108]
Hi,
    I read paper  "The repertoire of mutational signatures in human cancer" metioned that using SigProfilerExtractor to get transcitional stranded mutation signature. here is a description of the source of strand-bias table,
"Transcriptional strand bias associated with mutational signatures was assessed by applying SigProfilerExtraction to catalogues of in-transcript mutations that capture strand information (192 mutations classes, syn12026195). These 192-class signatures were collapsed to strandinvariant 96-class signatures and compared to the signatures extracted from the 96-class data, revealing very high cosine similarities (median 0.90, column F in syn12016215). "
But now SigProfilerExtractor version can't provide stranded 192-classes mutation calculation parameter according to "context_type" SigProfilerExtraction parameter. If I want to calculate stranded siganture using our cancer somatic vcf data, How do I achieve that?

Thanks a lot

**Comment by chujunliu** [comment]
Then I found SBS288 can be used to do trancriptional stranded signature， but on decompsition part SBS288 can't use.
The TCGA somatic data were used to test. My Sp version is 1.1.4. Can you give me some help

>>> decomp.decompose(signatures, activities, samples, "LUSC_descomp288", genome_build="GRCh37", verbose=False,collapse_to_SBS96=False)
The context-288 decomposition plots pages were not able to be generated.
The context-288 decomposition plots pages were not able to be generated.
The context-288 decomposition plots pages were not able to be generated.
The context-288 decomposition plots pages were not able to be generated.
The context-288 decomposition plots pages were not able to be generated.
Samples                       SBS288_Ref_1  SBS288_Ref_5  SBS288A  SBS288B  SBS288C  SBS288D  SBS288E
TCGA-18-3406-01A-01D-0983-08             0             0        0      110      133        0        0
TCGA-18-3407-01A-01D-0983-08             0             0        0        0      290        0        0

**Comment by chujunliu** [comment]
if parameter ”make_decomposition_plots=False“ were used，SBS288 decomposition can't work either.
command
 decomp.decompose(signatures, activities, samples, "LUSC_descomp288_plotsF", genome_build="GRCh37", verbose=False,collapse_to_SBS96=False,make_decomposition_plots=False)
View Log can't get cosmic 288 composition

!!!!!!!!!!!!!!!!!!!!!!!!! LAYER: 0 !!!!!!!!!!!!!!!!!!!!!!!!!
Best Signature Composition [2]
L2 Error % 0.94
Cosine Similarity 0.34


!!!!!!!!!!!!!!!!!!!!!!!!! LAYER: 1 !!!!!!!!!!!!!!!!!!!!!!!!!
Best Signature Composition [2]
L2 Error % 0.94
Cosine Similarity 0.34

#################### Final Composition #################################
[2]
L2 Error % 0.94
Cosine Similarity 0.34

**Comment by mdbarnesUCSD** [comment]
The SBS192 context has been retired. It has been moved to SBS288, which in addition to transcription strand bias, also incorporates the untranscribed strand. Specify the parameter _collapse_to_SBS96=true_ to decompose to COSMIC signatures. 

Thanks!

**Comment by chujunliu** [comment]
> The SBS192 context has been retired. It has been moved to SBS288, which in addition to transcription strand bias, also incorporates the untranscribed strand. Specify the parameter _collapse_to_SBS96=true_ to decompose to COSMIC signatures.
> 
> Thanks!

thanks a lot， i read the script and found that using SBS288 do decomposition part  and SBS288 cosmic reference can be found in /data directory，subroutines.py line826 to 1082, how can use this part script to decomposition in SBS288 context
such as
”elif signatures.shape[0]==288:
        sigDatabase = pd.read_csv(paths+"/data/Reference_Signatures/GRCh37/COSMIC_v"+str(3.2)+"_SBS"+str(signatures.shape[0])+"_GRCh37.txt", sep="\t", index_col=0)
        signames = sigDatabase.columns“
