### ISSUE TITLE
The full spell of quad in SigProfilerExtractor/SigProfilerExtractor/data/CN_classes_dictionary.txt

### ISSUE THREAD

**Issue by lincj1994** [AlexandrovLab/SigProfilerExtractor#109]
Hi. It wil be termed quad when the copy number is between 5-8. I wonder if you can provide the full spell of "quad".

**Comment by azhark2** [comment]
The names for the channels have been set according to our preprint. If you want to modify these you will have to fork the repository and change the relevant lines of code.

Thanks,
Azhar
