### ISSUE TITLE
problem with decomposition result

### ISSUE THREAD

**Issue by Charlene-c** [AlexandrovLab/SigProfilerExtractor#11]
Hello, 
I've followed the example to run the following codes:

    >>> path_to_example_folder_containing_vcf_files = sig.importdata("vcf")
    >>> data = path_to_example_folder_containing_vcf_files # you can put the path to your folder containing the vcf samples
    >>> sig.sigProfilerExtractor("vcf", "example_output", data, startProcess=1, endProcess=3)

However, it showed up that there's no decomposition result at the end.

**"WARNING!!! We apolozize we don't have a global signature database for the mutational context you provided. We have a database only for SB S96, DINUC and INDELS.
Therefore no result for signature Decomposition is generated."**

What could I do to solve the warning and get the decomposition result?

Thank you,
Charlene

**Comment by mishugeb** [comment]
Dear Charlene,
Thank you for submitting the issue. Could you please tell which version of SigProfilerExtractor and other packages you are using? I was unable to reproduce the issue using 0.0.5.74 version. The JOB_METADATA.txt in the results folder will show you version of critical packages used by the tool. I have attached the link of the results folder I just generated using the latest version. 

Thanks,
Mishu
[example_output.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/3649648/example_output.zip)

**Comment by Charlene-c** [comment]
@mishugeb Thank you for the reply.
The following is part of JOB_METADATA.txt which is unable to generate the Decomposed_Solution folder:

_-------System Info-------
Operating System Name: Linux
Nodename: localhost.localdomain
Release: 3.10.0-957.12.2.el7.x86_64
Version: #1 SMP Tue May 14 21:24:32 UTC 2019

-------Python and Package Versions-------
Python Version: 3.7.1
Sigproextractor Version: 0.0.5.75
SigprofilerPlotting Version: 1.0.8
SigprofilerMatrixGenerator Version: 1.0.20
Pandas version: 0.23.4
Numpy version: 1.15.4
Scipy version: 1.1.0
Scikit-learn version: 0.20.1
Nimfa version: 1.3.4

-------Vital Parameters Used for the execution -------
input_type: vcf
inputdata: vcftest
startProcess: 1
endProcess: 3
totalIterations: 8
cpu: -1
hierarchy: False
refgen: GRCh37
genome_build: GRCh37
mtype: ['default']_


but, the good new is after I used conda to create an environment with python 3.7.3 then it can produce result folders correctly, there's no WARNING anymore. The following is the part of JOB_METADATA.txt with no WARNING:

_-------System Info-------
Operating System Name: Linux
Nodename: localhost.localdomain
Release: 3.10.0-957.12.2.el7.x86_64
Version: #1 SMP Tue May 14 21:24:32 UTC 2019

-------Python and Package Versions-------
Python Version: 3.7.3
Sigproextractor Version: 0.0.5.75
SigprofilerPlotting Version: 1.0.8
SigprofilerMatrixGenerator Version: 1.0.20
Pandas version: 0.25.1
Numpy version: 1.17.2
Scipy version: 1.3.1
Scikit-learn version: 0.21.3
Nimfa version: 1.3.4

-------Vital Parameters Used for the execution -------
input_type: vcf
inputdata: input
startProcess: 1
endProcess: 3
totalIterations: 1000
cpu: -1
hierarchy: False
refgen: GRCh37
genome_build: GRCh37
mtype: ['default']_

Thanks,
Charlene

**Comment by mishugeb** [comment]
Sounds good! It looks like one of the packages to read the signature database was missing and it was installed when you installed Conda. 

Regards,
Mishu
