### ISSUE TITLE
the relationship between SigProfilerExtractor  and SigProfilerMatrixGenerator/SigProfilerPlotting

### ISSUE THREAD

**Issue by stroke1989** [AlexandrovLab/SigProfilerExtractor#110]
Excuese me
I'm a new to study bioinformatics analysis. I try to analysis mutational signature and I find this tool SigProfilerExtractor, I found the output of SigProfilerExtractor is likely same to SigProfilerMatrixGenerator+SigProfilerPlotting, I don't know if I understand in the wrong way

**Comment by mdbarnesUCSD** [comment]
Learn more about the tools by reading the publications:

1. [SigProfilerMatrixGenerator and SigProfilerPlotting](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-019-6041-2)
2. [SigProfilerExtractor](https://www.biorxiv.org/content/10.1101/2020.12.13.422570v2)

SigProfilerExtractor does DeNovo Extraction of mutational signatures.
