### ISSUE TITLE
Identifying optimum number of signatures

### ISSUE THREAD

**Issue by MySelvan** [AlexandrovLab/SigProfilerExtractor#111]
Hi,

I have 28 samples from two different conditions (14 samples with condition A & 14 samples with condition B).

I ran the SigProfiler with all the 28 samples together using the default parameters and minimum_signatures=1 and maximum_signatures=10. The reason I ran all the 28 samples together was to see which de novo signatures was unique and common to both conditions.

I got the attached SBS96_selection_plot.pdf. Could you please let me know whether  it is expected to have such a curve for Avg. stability. If not, could you please provide me suggestions on improving the results?

On separate note, could you also please let me know what is the criteria for identifying de novo signatures in the file De_Novo_map_to_COSMIC_SBS96.csv (in terms of number of Global NMF signatures, cosine similarity etc)

**Comment by MySelvan** [comment]
https://app.box.com/s/oyyqsb0b8iyp4685zrysxycb0864givk

**Comment by lalexandrov1018** [comment]
The selection curve looks reasonable and 8 signature should be used as a selected solution.
