### ISSUE TITLE
Reconstructed spectrum after signature extraction

### ISSUE THREAD

**Issue by itsvenu** [AlexandrovLab/SigProfilerExtractor#113]
Dear Mishu & Ludmil,

I was just wondering if the reconstructed spectrum of each sample is saved after SigProfilerExtractor is successfully ran. So far, I didn't find a file for this. Specifically, I want to check for a few samples how reconstruction-stats (at each step) are changed while signature add-removal steps are performed to arrive at the final solution. (I can get the final reconstructed spectras by matrix multiplications of identified signatures & their exposures)

Under `Suggested_Solution/COSMIC_SBS96_Decomposed_Solution/Solution_Stats/` folder, I found a few files but none of them have reconstructed spectrum with above details.

Is there function which I can use to save these details as well or did I miss any file which already contains this info? 

Thank you  & stay safe!

**Comment by marcos-diazg** [comment]
Dear Venu,

I hope you are doing great, and thanks for your question. If I understood you correctly, you are looking for the reconstruction stats at every assignment step per sample. If this is the case, you can find them in the `COSMIC_SBS96_Signature_Assignment_log.txt` file within the folder you mentioned.

Please let me know if you have further questions.

Best,

Marcos

**Comment by itsvenu** [comment]
Hi @marcos-diazg,

Thanks a lot for the quick reply and pointing me to the file. Much appreciated! Yes, these are the exact details I was looking for. Just to make sure if I understand it correctly, here is an example

```
                    ################ Sample 45 #################
############################# Initial Composition ####################################
    SBS1   SBS4   SBS5  SBS7c  SBS25   SBS40  SBS44
0  281.0  686.0  588.0   25.0  457.0  1029.0  111.0
L2 Error %: 0.37
Cosine Similarity: 0.93
############################## Composition After Initial Remove ###############################
         SBS1        SBS4        SBS40
0  362.707691  706.323197  2107.969112
L2 Error %: 0.42
Cosine Similarity: 0.91

############################## Performing Add-Remove Step ##############################


!!!!!!!!!!!!!!!!!!!!!!!!! LAYER: 0 !!!!!!!!!!!!!!!!!!!!!!!!!
Best Signature Composition ['SBS1', 'SBS4', 'SBS5', 'SBS40']
L2 Error % 0.39
Cosine Similarity 0.92

!!!!!!!!!!!!!!!!!!!!!!!!! LAYER: 1 !!!!!!!!!!!!!!!!!!!!!!!!!
Best Signature Composition ['SBS1', 'SBS4', 'SBS5', 'SBS40']
L2 Error % 0.39
Cosine Similarity 0.92

#################### Final Composition #################################
['SBS1', 'SBS4', 'SBS5', 'SBS40']
L2 Error % 0.39
Cosine Similarity 0.92
####################################### Composition After Add-Remove #######################################
    SBS1   SBS4   SBS5   SBS40
0  309.0  836.0  994.0  1038.0
L2 Error %: 0.39
Cosine Similarity: 0.92
```
Initial composition - is all signatures identified in the cohort used. So, at each step `L2% Error` is minimized & cosine similarity to original sample spectrum is optimized. 

Now the question is, is it possible for me to check, in this sample,  if I remove SBS4 how L2 & cosine similarity will change?

Also, in the sole `decompose` function, I didn't find a parameter to apply a cut-off on `cosine similarity` to call a signature novel or COSMIC one. Did I miss any detail or is it not possible?

Thank you so much for your time. Stay safe!

**Comment by itsvenu** [comment]
Hi @rvangara, great thanks a lot for the update. 

Sorry if I haven't framed the question well, in addition to Q2, I would also like to know about one more possibility. That is, during per-sample decomposition, is it possible to remove the signature of my choice from final set (`Composition After Add-Remove`) and test how the stats are changing, as explained in above example?

Thank you & stay safe!

**Comment by marcos-diazg** [comment]
Dear Venu,

In order to achieve what you mentioned in the last message, I recommend running the decomposition module using a custom signature database, where you remove the COSMIC signature you want from the analysis. You can do that by generating your custom signatures matrix, for example, by removing one/more columns from the COSMIC reference signatures matrix from [here](https://cancer.sanger.ac.uk/signatures/downloads/). Then, you can include this custom signature matrix as the `signature_database` parameter in the `decompose` function.

By doing so, you should see how removing this signature affects the L2 error and the cosine similarity of the decomposition, as requested.

I hope this helps, and thanks for your interest!

**Comment by itsvenu** [comment]
Dear @marcos-diazg,

Perfect. I have been doing the same, thanks for confirming that's the only way atm to achieve this. However, I have two more questions. 

1. Error while doing custom decomposition. I installed correct version of pandas as stated in `requirements` file. Would you please suggest a way to fix this issue?

```
>>> decomp.decompose(signatures, activities, samples, output, genome_build="GRCh37", signature_database=None, verbose=True, newsignature_threshold=0.9)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/venu/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/decomposition.py", line 130, in decompose
    colnames,denovo_exposureAvg  = denovo_exposureAvg, add_penalty=nnls_add_penalty, remove_penalty=nnls_remove_penalty, initial_remove_penalty=initial_remove_penalty, de_novo_fit_penalty=de_novo_fit_penalty, connected_sigs=connected_sigs, refit_denovo_signatures=refit_denovo_signatures)
  File "/Users/venu/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 1586, in make_final_solution
    processes.to_csv(layer_directory+"/Signatures"+"/"+solution_prefix+"_"+"Signatures.txt", "\t", float_format='%.8f',index_label=[processes.columns.name])
  File "/Users/venu/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3403, in to_csv
    storage_options=storage_options,
  File "/Users/venu/anaconda3/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/Users/venu/anaconda3/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 234, in save
    storage_options=self.storage_options,
  File "/Users/venu/anaconda3/lib/python3.7/site-packages/pandas/io/common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/venu/Desktop/ServerView/BRCA/results/sigProfiler_pedpancan/signatureAnalysis_XX/signatureExtraction/PPC_Extraction_13122019/SBS96/k2_decomp_cos09/De_Novo_Solution/Signatures/De_Novo_Signatures.txt'
```
2. When decomposition is performed, a denovo signature is reconstructed with the constituent COSMIC signatures. However, I don't seem to find the reconstructed denovo signature profile (text file)? Is this saved in one of the files that I missed? If not, is there a way to save it?

For example, in the following image, is the reconstructed profile saved to a text file?

![ex](https://i.ibb.co/rm5JmV7/SS-2022-02-03-at-08-51-39.png)

Thank you for your time. Stay safe!

**Comment by marcos-diazg** [comment]
Dear @itsvenu,

Sorry for the late reply. Regarding your questions:

1. It looks like an error because the path you are providing to one of the function parameters does not exist. Also, remember that if you want to use a custom signature database, you need to provide it using the `signature_database` parameter. The `signatures` parameter will correspond to the _de novo_ extracted signatures by SigProfilerExtractor.

2. I'm not sure exactly which file you are looking for. If you are referring to the contribution of the different COSMIC signatures that explains the reconstructed _de novo_ signature, you can find those in the `De_Novo_map_to_COSMIC` file, inside the `Suggested_Solution/COSMIC_[context]_Decomposed_Solution` folder. But please let me know if you are referring to other data.

I hope this helps, and thanks again for your interest.

**Comment by rvangara** [comment]
Hi @itsvenu,  Please reopen this ticket if you still have the issue.
