### ISSUE TITLE
sigProfilerExtractor ignores some vcf files

### ISSUE THREAD

**Issue by AnastasiaShind** [AlexandrovLab/SigProfilerExtractor#115]
Hi guys, 

I run sigProfilerExtractor on vcf files using this command line: 
sig.sigProfilerExtractor("vcf", input_data = "/path/to/vcfs", output = 'results',reference_genome = 'mm10', exome = True, cpu=30, maximum_signatures=10, nmf_replicates=100, resample = True)

It runs successfully, but when I check activities txt files, I see that only 1 file from 4 is analyzed. There is no apparent pattern why some vcf file is chosen over others: it's not alphabetical or size-dependent. But if I remove this one file that was analyzed and run sigProfilerExtractor on remaining 3 files, I get this error: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ashindyapina/.pyenv/versions/3.6.8/lib/python3.6/site-packages/SigProfilerExtractor/sigpro.py", line 606, in sigProfilerExtractor
    data = datadump.SigProfilerMatrixGeneratorFunc(project_name, refgen, project, exome=exome,  bed_file=None, chrom_based=False, plot=False, gs=False)
  File "/home/ashindyapina/.pyenv/versions/3.6.8/lib/python3.6/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 289, in SigProfilerMatrixGeneratorFunc
    shutil.copy(vcfFiles + files, vcf_path + files)
  File "/home/ashindyapina/.pyenv/versions/3.6.8/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ashindyapina/.pyenv/versions/3.6.8/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/results'
 
Looks like sigProfilerExtractor ignores these other files. 
It doesn't make sense since all vcfs were generated in the same run. And it works for some sets of vcfs, and then fails for others. 

Anastasia

**Comment by ebergstr** [comment]
Hi Anastasia,

Can I please ask you to run SigProfilerMatrixGenerator separately on these files using a new folder and to report any errors from that run under the SigProfilerMatrixGenerator issues page?

For instance, you can run the following command from a python instance:

>>from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
>>matrices = matGen.SigProfilerMatrixGeneratorFunc("project_name", "mm10", "/path/to/vcfs/")

I will close this current issue and will check back in on the MatrixGenerator page for the next follow-up!

Best,
Erik
