### ISSUE TITLE
the given project path does not appear to exist

### ISSUE THREAD

**Issue by stroke1989** [AlexandrovLab/SigProfilerExtractor#116]
Hi,
I a newer to  sigProfiler, I tried to use sigProfilerExtractor to run build-in example data, errors occurred, I don't know how to handle this issue, as following:
sig.sigProfilerExtractor("vcf", "results", "~/software/SigProfilerMatrixGenerator/21BRCA/21BRCA_vcf", reference_genome="GRCh37", minimum_signatures=1, maximum_signatures=10, nmf_replicates=100)

************** Reported Current Memory Use: 0.31 GB *****************

The given project path does not appear to exist. Please check that the specified path exists before proceeding...
        ~/software/SigProfilerMatrixGenerator/21BRCA/21BRCA_vcf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ug0416/.conda/envs/cnvkit/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 600, in sigProfilerExtractor
    genomes = pd.DataFrame(data[m])
TypeError: tuple indices must be integers or slices, not str
However, I have defined absolut path to input vcf file

**Comment by marcos-diazg** [comment]
Dear @stroke1989 

I hope you are doing great, and thanks for your interest in our tool. As the error message shows, could you please check that you have your vcf files in that specific path? Also, please use the [importdata](https://github.com/AlexandrovLab/SigProfilerExtractor#-importdata) function as described in the README for using the built-in example data.

I would also recommend checking out the [video tutorials](https://github.com/AlexandrovLab/SigProfilerExtractor#video_tutorials) available to help you with this and other potential issues.

Please let us know if you have any further problems.

Marcos

**Comment by stroke1989** [comment]
Thank you for your reponse. I could proceed. However, another issue happened. I finished extration of de novo signature, but the ID83 graph was wierd, the legend overlapped, so I tried to use  SigProfilerPlotting plot ID83 by myself, I run as following:
 plotID("/home/ug0416/software/SigProfilerExtractor/SigProfilerExtractor/results/ID83/Suggested_Solution/ID83_De-Novo_Solution/Signatures/" + "ID83_De-Novo_Signatures.txt", "/home/ug0416/software/SigProfilerExtractor/SigProfilerExtractor/results/ID83/Suggested_Solution/ID83_De-Novo_Solution/Signatures/", test, "83", percentage=FALSE)
Error in "/home/ug0416/software/SigProfilerExtractor/SigProfilerExtractor/results/ID83/Suggested_Solution/ID83_De-Novo_Solution/Signatures/" +  :
  non-numeric argument to binary operator
I thought that  the ample_matrices_path and output_path was set incorrectly. I don't know how to handle this issue. Hope your reponse! Appreciate!

**Comment by marcos-diazg** [comment]
Hi again!

The issue of the legend overlapping is probably due to a [well-known issue of matplotlib](https://github.com/matplotlib/matplotlib/issues/13139). Please try to follow the instructions in that issue, as well as install the appropriate fonts in your system.

Regarding your problem with SigProfilerPlotting, I think it can be related to the command you used. Please use absolute paths without `+` operators. Also, you should check the use of R-style `FALSE` instead of Python `False`. If you have further questions, @ebergstr can help you more if you open a new issue in [SigProfilerPlotting](https://github.com/AlexandrovLab/SigProfilerPlotting).

I hope this helps and thanks for your interest!

**Comment by marcos-diazg** [comment]
Please reopen this issue or a new one if you are encountering any problems.
