### ISSUE TITLE
How to install reference genome

### ISSUE THREAD

**Issue by TomhitsJerry** [AlexandrovLab/SigProfilerExtractor#120]
![image](https://user-images.githubusercontent.com/22815603/153539222-3c14b307-3982-4c0d-aaed-6d2310370f30.png)
![fdfb109652b143185aaa71bfa49dad5](https://user-images.githubusercontent.com/22815603/153538088-780aae6d-fe47-43a8-9e6e-b26b2fc36d50.png)

how can I download the 38 reference, it seems the url is missing.Thanks a lot!
both url has tried:
ftp://ngs.sanger.ac.uk/scratch/project/mutographs/SigProf/
 ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/[desired_genome].tar.gz

**Comment by marcos-diazg** [comment]
Dear @TomhitsJerry,

Thanks for your interest! Could you please open a new issue on the [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator) GitHub? This tool handles the mutational matrix generation and the reference genome installation.

**Comment by TomhitsJerry** [comment]
OK, I have opened a issue on the [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator) GitHub.   Looking forward for your help to get GRCh38!
