### ISSUE TITLE
RuntimeError:An attempt has been made to start a new process before the current process has finished its bootstrapping phase.

### ISSUE THREAD

**Issue by DimitrisGrig** [AlexandrovLab/SigProfilerExtractor#121]
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/22744570/154162493-1c7bcfbe-a91f-472d-8d0e-61b590f7c945.png">

**Comment by marcos-diazg** [comment]
Please reopen the ticket if you are still experiencing any issues after including the `if __name__ == 'main':` idiom. Thanks for your interest!
