### ISSUE TITLE
custom reference signatures

### ISSUE THREAD

**Issue by vr1087** [AlexandrovLab/SigProfilerExtractor#125]
Is it possible to modify SigProfileExtractor to use custom reference signatures instead of the reference cosmic signatures? Would it be sufficient to replace files under the Reference_Signatures folder? For context, I'm interested in constructing reference signatures for mismatch repair deficient ecoli experiments. Thanks in advance.

**Comment by marcos-diazg** [comment]
No need to replace any files. You can decompose your _de novo_ extracted signatures and assign mutations using a custom reference set of signatures by using [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment). Please let us know if you still have any issues.
