### ISSUE TITLE
Activity for signature is 0, but shows as 2% in decomposition plot

### ISSUE THREAD

**Issue by oliverartz** [AlexandrovLab/SigProfilerExtractor#131]
Dear developers,

While using `SigProfilerExtractor`, I found a `SBS96_Decomposition_Plots.pdf` in `COSMIC_SBS96_Decomposed_Solution`, which is composed of about 49% SBS21, 49% SBS5, and 2% SBS1 (see picture below). The `COSMIC_SBS96_Activities.txt` (attached), however, tells me that there are 0 activities found for SBS1. I don't quite understand how this can be possible. Am I misinterpreting the numbers?

[SBS96_Decomposition_Plots.pdf](https://github.com/AlexandrovLab/SigProfilerExtractor/files/8873114/SBS96_Decomposition_Plots.pdf)
[COSMIC_SBS96_Activities.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/8873124/COSMIC_SBS96_Activities.txt)

Thank you for your help and the development of the tools!
Best,
Oliver

**Comment by mdbarnesUCSD** [comment]
Hi @oliverartz,

COSMIC_SBS96_Activities.txt is the samples reconstructed by the COSMIC signatures and SBS96_Decomposition_Plots.pdf is the de novo signatures reconstructed by the COSMIC signatures. SBS1 may be present in the de novo signature reconstruction though SBS1 may not be present in the sample reconstruction.

**Comment by oliverartz** [comment]
🤦 My bad! Thanks for the explainer - that makes a lot of sense.
