### ISSUE TITLE
Did you update the Extractor reference signature of CNV from the Preprint to the Nature?

### ISSUE THREAD

**Issue by lincj1994** [AlexandrovLab/SigProfilerExtractor#133]
Hi.
I've read your CNV signature paper (the Preprint version) previously. At that time, the total number of signature was 19. When I read the related paper published in Nature, I found the total number was 21. I'm wondering if you have updated the reference signature in Extractor?
Besides, in the [Assignment Issue #17](https://github.com/AlexandrovLab/SigProfilerAssignment/issues/16), I was told 'SingleSample is an old version and is soon to be archived. Please use the SigProfilerAssignment tool for attribution of COSMIC to a single sample.' But in the Nature paper, you assigned CNV signature using SingleSample. I'm wondering which tool is recommended or both is OK in terms of CNV signature.
Thanks.
Lin.

**Comment by marcos-diazg** [comment]
Dear Lin,

Thanks for your interest, and sorry for our late reply. We have just recently updated the reference CNV signatures used by SigProfilerExtractor to the [COSMIC v3.3](https://cancer.sanger.ac.uk/signatures/downloads/) version (corresponding to the reference signatures published in [Steele et al. 2022 Nature](https://doi.org/10.1038/s41586-022-04738-6)). Indeed, you may need to update [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment) to the latest version, v0.0.8.

SigProfilerAssignment is our new tool to perform _de novo_ signature decomposition to reference mutational signatures and signature assignment, and it is used internally by SigProfilerExtractor. As my colleague mentioned in the mentioned issue, we are in the process of retiring the SigProfilerSingleSample tool, and we strongly recommend users to use our new SigProfilerAssignment approach.

I hope this helps, and please reopen the ticket if you have further questions.
