### ISSUE TITLE
PCG64DXSM causing run problems 

### ISSUE THREAD

**Issue by laurelhiatt** [AlexandrovLab/SigProfilerExtractor#137]
In both the python code and an R wrapper, I have run into a block with importing PCG64DXSM

This is the R error, the python error was similar:
ImportError: cannot import name 'PCG64DXSM' from 'numpy.random' (/Users/quinlan/opt/anaconda3/lib/python3.8/site-packages/numpy/random/__init__.py)

I commented out in the python code and it seemed to be fine as it's a function intrinsic to numpy/numpy.random, but I've run into additional quirks with the python code so I am trying out the R wrapper, and figure if it's happening in both setups, I might as well mention it.632

**Comment by marcos-diazg** [comment]
Dear @laurelhiatt,

Could you please let us know which version of numpy and python are you using? Thanks!

**Comment by mdbarnesUCSD** [comment]
Please feel free to open this issue if you are still encountering this.
