### ISSUE TITLE
number of signatures

### ISSUE THREAD

**Issue by dmusachio** [AlexandrovLab/SigProfilerExtractor#138]
Hi,

I am setting the minimum number of signatures to be extracted to 5, yet in my decomposition plot, I only see one signature. Is this a bug or am I reading the plot below incorrectly?

![Capture](https://user-images.githubusercontent.com/99296128/181332418-c218aac3-de14-4847-a236-7a87fbd6f479.PNG)

The reason I am trying to extract more signatures is that I read that 5-10 signatures tends to create the highest cosine similarity and the lowest error rate.

Thanks

**Comment by marcos-diazg** [comment]
Dear @dmusachio,

Could you please confirm the number of samples that you are using to extract mutational signatures? Also, the number of signatures to extract is totally dependent on your dataset and the mutational processes shaping the mutations found in that specific cohort. SigProfilerExtractor will automatically select the more appropriate number of signatures.

**Comment by marcos-diazg** [comment]
Please reopen the ticket if you are still experiencing this issue. Thanks so much for your interest in our tool!
