### ISSUE TITLE
extractor error with gpu=True

### ISSUE THREAD

**Issue by itsvenu** [AlexandrovLab/SigProfilerExtractor#14]
Hi,

I was trying to extract signatures with `gpu=True`. However, I get the following error.

```
/usr/local/lib/python3.6/dist-packages/sigproextractor/sigpro.py in sigProfilerExtractor(input_type, out_put, input_data, refgen, genome_build, startProcess, endProcess, totalIterations, init, cpu, hierarchy, mtype, exome, par_h, penalty, resample, wall, gpu)
    569                                                 init = init,
    570                                                 normalization_cutoff=normalization_cutoff,
--> 571                                                 gpu=gpu,)
    572 
    573 

/usr/local/lib/python3.6/dist-packages/sigproextractor/subroutines.py in decipher_signatures(genomes, i, totalIterations, cpu, mut_context, resample, seeds, init, normalization_cutoff, gpu)
    982     ############################################################# The parallel processing takes place here #######################################################################
    983     ##############################################################################################################################################################################
--> 984     results = parallel_runs(genomes=genomes, totalProcesses=totalProcesses, iterations=totalIterations,  n_cpu=cpu, verbose = False, resample=resample, seeds = seeds, init=init, normalization_cutoff=normalization_cutoff, gpu=gpu)
    985 
    986     toc = time.time()

/usr/local/lib/python3.6/dist-packages/sigproextractor/subroutines.py in parallel_runs(genomes, totalProcesses, iterations, n_cpu, verbose, resample, seeds, init, normalization_cutoff, gpu)
    459     #print(seeds)
    460     pool_nmf=partial(pnmf, genomes=genomes, totalProcesses=totalProcesses, resample=resample, init=init, normalization_cutoff=normalization_cutoff, gpu=gpu)
--> 461     result_list = pool.map(pool_nmf, seeds)
    462     pool.close()
    463     pool.join()

/usr/lib/python3.6/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    264         in a list that is returned.
    265         '''
--> 266         return self._map_async(func, iterable, mapstar, chunksize).get()
    267 
    268     def starmap(self, func, iterable, chunksize=None):

/usr/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

TypeError: nnmf_gpu() got an unexpected keyword argument 'init'
```

Any help in solving the errors would be highly appreciated.

Thank you.

**Comment by vellamike** [comment]
Hi @itsvenu  - are you using the latest version of sigprofiler? How are you installing it?

**Comment by itsvenu** [comment]
hi @vellamike, I'm using the latest version 1.0.3 installed with pip.

I am using tool with google-colab assisted with GPU (but I guess this shouldn't cause the error?).

**Comment by vellamike** [comment]
hi @itsvenu , I think the latest version off pip hasn't been updated to use gpu. Is this correct @mishugeb ? Can you try running on colab but installing via setup.py?

Also, if you run on colab, can you check what GPU you are using via `nvidia-smi`? Sigprofiler is tested to run on a V100 which is a GPU provided on colab although you might not get it.

**Comment by mishugeb** [comment]
Hi all, the GPU version is on PyPI. Just use $pip install SigProfilerExtractor

**Comment by itsvenu** [comment]
hi @vellamike, the GPU is Tesla K80. 

hi @mishugeb, I installed the latest version, however, it is giving me the error mentioned above. If I use `gpu=False`, it's running smoothly.

I can share the notebook if that helps? 

Thank you.

**Comment by vellamike** [comment]
Yes please do, could you send me a link to the notebook?

**Comment by itsvenu** [comment]
@vellamike, could you please share your email id? or drop a text to `thatikonda92 [at] gmail [dot] com` so I can share it in a DM.

**Comment by vellamike** [comment]
Just sent you an email

**Comment by itsvenu** [comment]
shared the notebook along with test dataset. Thanks.

**Comment by mishugeb** [comment]
Hi all, 
Sorry for the delayed reply as I did not notice the conversation.  Please don't use the init argument when using GPU=True. We are optimizing the NMF parameter for GPU.  I will upload a new version once we do that.

**Comment by vellamike** [comment]
Should this issue be closed? Reporter hasn't confirmed suggested fix works

**Comment by mishugeb** [comment]
Hi Mike, 
We thought a number of updates have been made since the issue was reported. So we are closing this now. If people have issues again they can let us know. 

Thanks,
Mishu
