### ISSUE TITLE
Only Context working output is 6 and 18 

### ISSUE THREAD

**Issue by pinunQ** [AlexandrovLab/SigProfilerExtractor#148]
Hello I am running SigProfilerExtractor command and the only signatures that are received as output are the CH6 and CH18.
It does not bring any signature for any number of samples.

Can you please explain the situation happening?

**Comment by marcos-diazg** [comment]
Dear @pinunQ,

CH is the name given to signatures using a non-standard mutational context (i.e., different from COSMIC standard SBS96, DBS78, ID83 or CN48). Not sure if this is something that can be of interest to your analysis. If you want to use the standard contexts, I recommend you to follow our wiki page instructions at https://osf.io/t6j7u/wiki/home/ and check our video tutorials at https://github.com/AlexandrovLab/SigProfilerExtractor#video_tutorials.

I hope this helps, and please feel free to reopen the ticket if you have further questions.
