### ISSUE TITLE
synchronisation with PyPI

### ISSUE THREAD

**Issue by mvforster** [AlexandrovLab/SigProfilerExtractor#149]
Dear devs,
I noticed that the versions hosted on GitHub are lagging behind the versions from PyPI. Can you please confirm if versions greater than v.1.1.4 will be published here?
If not would it be possible to included this information in the repo's README?

Many thanks,

Matthieu

**Comment by marcos-diazg** [comment]
Dear Matthieu,

Thanks for your interest in our tool. All PyPI versions have been tagged on GitHub, as you can see here: https://github.com/AlexandrovLab/SigProfilerExtractor/tags. I hope this helps, and please reopen the ticket if you have further questions.

Marcos
