### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by XuanYuXu** [AlexandrovLab/SigProfilerExtractor#15]
When I" pip install SigProfilerExtractor",and then always metion that "ERROR: No matching distribution found for torch>=1.1.0 (from SigProfilerExtractor)".I do not now how to solve that ,anyone can tell me?

**Comment by itsvenu** [comment]
Upgrade `torch` with `pip install torch --upgrade` and install `SigProfilerExtractor `. It should work fine.

**Comment by mishugeb** [comment]
Hi, 
Please use "pip3 install SigProfilerExtractor" if you are not using the conda environment. That should solve the problem.
