### ISSUE TITLE
About decomposing de novo signatures to COSMIC signatures

### ISSUE THREAD

**Issue by FromSoSimple** [AlexandrovLab/SigProfilerExtractor#153]
Hi Team,

About decomposing the De Novo Signatures into COSMIC Signatures, I was wondering if there was any algorithmic difference between the results generated by SigProfilerExtractor (i.e, De_novo_map_to_COSMIC_SBS96.csv) vs. the results generated by SigProfilerAssignment decompose_fit function?

Thanks,
Corey

**Comment by rvangara** [comment]
Hi Corey,

No. The latest versions of  SigProfilerExtractor use decompose_fit fn of SigProfilerAssignment for the decomposition of de novo signatures to COSMIC.

Please reopen the ticket if you have any issues.

Thanks
Ravi.
