### ISSUE TITLE
Sample contribution mutational signatures

### ISSUE THREAD

**Issue by msubirana** [AlexandrovLab/SigProfilerExtractor#155]
Is it possible to extract the contribution of each sample to the extracted signatures?

Something like:

![image](https://user-images.githubusercontent.com/48090783/193022378-dc434c17-2722-4445-a55d-bd1d5fd6dde6.png)

**Comment by marcos-diazg** [comment]
Dear @msubirana,

Thanks for your question. The image you posted does not correspond to a SigProfilerExtractor output but rather to another mutational signature extraction tool, and it's actually representing the contribution of each extracted signature to each sample.

SigProfilerExtractor has an extensive documentation about the output files that you can check on our [wiki page](https://osf.io/t6j7u/wiki/5.%20Output%20-%20All%20Solutions/) and [video tutorials](https://github.com/AlexandrovLab/SigProfilerExtractor#video_tutorials). The files you are looking for are the activity results and plots.

Please feel free to reopen the ticket if you have further questions.
