### ISSUE TITLE
CNV Matrix causes error

### ISSUE THREAD

**Issue by Ott-Alexander** [AlexandrovLab/SigProfilerExtractor#156]
Hi,

I'm trying to run SigProfilerExtractor on a small CNV dataset to assign cosmic cnv signatures.
I'm using the call:

`sig.sigProfilerExtractor("seg:FACETS", result_folder, input_file, reference_genome="mm10",  minimum_signatures=1, maximum_signatures=10, nmf_replicates=100, cpu=5)`

with the input file in the format:
`chr	start	end	tcn.em	lcn.em	sample	id`

It seems to work until the matrix is generated but then throws this error:
  
>************** Reported Current Memory Use: 0.33 GB *****************
> Saved matrix to results/FACETS.CNV48.matrix.tsv
>  Traceback (most recent call last):
>    File "/mnt/users/ahott1a1/projects/Somatic/Issue139_SigProfiler/extractSignatures.py", line 128, in <module>
>      main(args)
>    File "/mnt/users/ahott1a1/projects/Somatic/Issue139_SigProfiler/extractSignatures.py", line 36, in main
>      sig.sigProfilerExtractor("seg:FACETS", result_folder, args.input, reference_genome=args.ref,  minimum_signatures=args.minSig,
>    File "/mnt/users/ahott1a1/opt/miniconda/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 686, in >sigProfilerExtractor
>      normalization_cutoff = sub.get_normalization_cutoff(genomes, manual_cutoff=100*genomes.shape[0])
>    File "/mnt/users/ahott1a1/opt/miniconda/lib/python3.9/site-packages/SigProfilerExtractor/subroutines.py", line 182, in >get_normalization_cutoff
>      mean = np.mean(col_sums)
>    File "<__array_function__ internals>", line 180, in mean
>    File "/mnt/users/ahott1a1/opt/miniconda/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3432, in mean
>      return _methods._mean(a, axis=axis, dtype=dtype,
>    File "/mnt/users/ahott1a1/opt/miniconda/lib/python3.9/site-packages/numpy/core/_methods.py", line 180, in _mean
>      ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
>  TypeError: can only concatenate str (not "int") to str

Is that an error because of my input? 
I saw the closse issue #146 but there was no mention of what was happening.

Thank you for the help
Alex

**Comment by marcos-diazg** [comment]
Dear @Ott-Alexander,

Could you please share your input files/mutational matrix, as well as your JOB_METADATA file to try to reproduce your issue? Happy to help also over email at mdiazgay@health.ucsd.edu. Thanks!

Marcos

**Comment by mdbarnesUCSD** [comment]
Please update to v1.1.4, the issue should be resolved in that update. Thanks!
