### ISSUE TITLE
signature for each mutation in a sample

### ISSUE THREAD

**Issue by sainadfensi** [AlexandrovLab/SigProfilerExtractor#163]
Hi,

I'm using the SigProfilerExtractor to analysis my variants and find the tool is really handy.

I'm trying to find which mutation associated to which signature but cannot find the related information in outputs. In the Activity folder, the COSMIC_SBS96_Activities.txt shows the total number of mutations associated to each signatures. The Decomposed_Mutation_Probabilities.txt shows the probabilities for each type of variants in each sample. I tried multiplied the probabilities with the number of variants for each type and added them up, but not all of them equals to the numbers listed in Decomposed_Mutation_Probabilities.txt.

Thanks for any advice.

Bests,

**Comment by marcos-diazg** [comment]
Hi @sainadfensi,

Thanks so much for your interest, and sorry for our late reply. You can now use the newest version (v0.0.19) of our new tool [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment/) to calculate the signature probabilities per mutation from your SigProfilerExtractor output. You just need to set the `export_probabilities_per_mutation` parameter to "True".

I hope this helps, and please feel free to reopen the ticket or reach out by email at mdiazgay@health.ucsd.edu if you have further issues or questions.
