### ISSUE TITLE
Alter COSMIC version

### ISSUE THREAD

**Issue by RTCarmo** [AlexandrovLab/SigProfilerExtractor#168]
Hello,

I'm trying to use the flag `cosmic_version`, stated as a possible flag [here](https://osf.io/t6j7u/wiki/3.%20Using%20the%20Tool%20-%20Input/). But, I keep getting the following error:
```
File "<stdin>", line 1, in <module>
TypeError: sigProfilerExtractor() got an unexpected keyword argument 'cosmic_version'
```
To have older versions of COSMIC signature profiles of my samples I have to run exclusivity SigProfilerAssignment? Or there is another way to run SigProfilerExtractor with different versions of COSMIC?

Best Regards

**Comment by mdbarnesUCSD** [comment]
Hi @RTCarmo,

Apologies for the delayed response. If you are still having this issue, could you please post the full command that was used?

Thanks!

**Comment by mdbarnesUCSD** [comment]
We are not able to reproduce the issue at this time. If you encounter this issue, please re-open this ticket.
