### ISSUE TITLE
 /lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by JLiandbear** [AlexandrovLab/SigProfilerExtractor#169]
Hi
I need use SigProfilerExtractor on our cluster. However, I encountered this error message:
OSError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ~/.local/lib/python3.7/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11)

This is a known issue in our HPC. It is using GLIBC-2.12 (from Centos6.9). We can't safely update that to GLIBC-2.14 inside a shared user environment without going to Centos 7++.

I am wondering whether there's possibility that SigProfilerExtractor can use GLIBC-2.12?

Thank you
Regards
Jun

**Comment by mdbarnesUCSD** [comment]
Hi @JLiandbear,

Thanks for reaching out. Unfortunately, Centos6 was deprecated in November of 2020 so we will not be providing support for this.

You may be able to install SigProfilerExtractor with an older version of Pytorch, but that will likely cause other issues to arise.
