### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:  sigProfilerPlotting/templates/DBS78.pkl 

### ISSUE THREAD

**Issue by AldhairMedico** [AlexandrovLab/SigProfilerExtractor#170]
Dear SigProfiler team, 
I'm having the issue:
FileNotFoundError: [Errno 2] No such file or directory: 

> '/home/aldhair/.local/lib/python3.10/site-packages/sigProfilerPlotting/templates/DBS78.pkl'

According to pip3 list:

> SigProfilerAssignment 0.0.18
> SigProfilerExtractor 1.1.4
> SigProfilerMatrixGenerator 1.2.13
> SigProfilerPlotting 1.3.2

My code was: 
```
from SigProfilerExtractor import sigpro as sig
sig.sigProfilerExtractor("vcf", "59only", "/home/aldhair/Apps/SigProfilerExtractor-1.1.4/59only", reference_genome="GRCh38", opportunity_genome = "GRCh38", exome = True, minimum_signatures=1, maximum_signatures=25, nmf_replicates=100, resample = True, batch_size=1, cpu=-1, gpu=False, nmf_init="nndsvd_min", precision= "single", matrix_normalization= "gmm", min_nmf_iterations= 10000, max_nmf_iterations=1000000, nmf_test_conv= 10000, nmf_tolerance= 1e-15, nnls_add_penalty=0.05, nnls_remove_penalty=0.01, initial_remove_penalty=0.05, de_novo_fit_penalty=0.02, get_all_signature_matrices= False)
```

I'm working on the Ubuntu subsystem for Windows 11, any idea of what is happening?  

Thanks

**Comment by rvangara** [comment]
Hi @AldhairMedico ,

The error is due to the recent update in the Sigprofilerplotting library.

However, this issue should be addressed in SigProfilerPlotting 1.3.2 as you are showing in your pip3 list.

Can you please make sure to upgrade SigProfilerPlotting to the recent version of 1.3.2 and remove any conflicting previous versions of this library installed in your environment?

Best,
Ravi

**Comment by rvangara** [comment]
Please reopen the ticket if the issue persists.

Ravi.

**Comment by gamabunta313** [comment]
I found the very same problem installing SigProfiler with SigProfilerPlotting version 1.3.2 (python 3.6)

**Comment by rvangara** [comment]
Please remove any previous SigProfilerPlotting modules you have in your environment and reinstall SPP v1.3.2. And even then if you are having this issue please notify us.
