### ISSUE TITLE
Crash when trying to create Signature Plot file

### ISSUE THREAD

**Issue by mattiyeh** [AlexandrovLab/SigProfilerExtractor#173]
Hello,
When running the latest version on my matrix file, I came across an error when SigProfilerPlotting tried to create the Signature_Plot file. The Signature_Plot folder was not being created beforehand so any file creation inside that folder would fail. I had to manually edit the subroutines.py file in SigProfilerExtractor to fix this bug.

subroutine.py (~line 1000):

```
if not os.path.exists(subdirectory):
        os.makedirs(subdirectory)
        os.makedirs(signature_subdirectory) #processes, processSTE and SBS Plots will go here
        os.makedirs(signature_subdirectory+"/Signature_plot")  # NEW LINE OF CODE
        os.makedirs(activity_subdirectory)  #exposures, exposureSTE, TMB plot and activity plot
        os.makedirs(stats_subdirectory)     #all others
```

**Comment by rvangara** [comment]
As I answered in the other issue, please send me(rvangara@health.ucsd.edu) your input file and try using it with SPP version 1.2.2

**Comment by rvangara** [comment]
Please look at Issue #176 

Thanks
Ravi.
