### ISSUE TITLE
Hello，i want to know how can i use the result of SigProfilerMatrixGenerator to start SigProfilerExtractor?

### ISSUE THREAD

**Issue by ruinw** [AlexandrovLab/SigProfilerExtractor#175]
This is my output file
Should i use this txt as the input file?or merge this txt
I dont know which way can i get CN signatures and SBS too
thx

U:~/mutation/ESCC/output$ ls
DBS  ID  SBS  TSB  vcf_files
U:~/mutation/ESCC/output$ cd ID
U:~/mutation/ESCC/output/ID$ ls
ESCC.ID28.all  ESCC.ID332.all  ESCC.ID415.all  ESCC.ID83.all  ESCC.ID8628.all  ESCC.ID96.all
U:~/mutation/ESCC/output/ID$ cd ..
U:~/mutation/ESCC/output$ cd vcf_files/
U:~/mutation/ESCC/output/vcf_files$ ls
DBS  ID  MNS  SNV
U:~/mutation/ESCC/output/vcf_files$ cd ID/
U:~/mutation/ESCC/output/vcf_files/ID$ ls
10_seqinfo.txt  13_seqinfo.txt  16_seqinfo.txt  19_seqinfo.txt  21_seqinfo.txt  3_seqinfo.txt  6_seqinfo.txt  9_seqinfo.txt   Y_seqinfo.txt
11_seqinfo.txt  14_seqinfo.txt  17_seqinfo.txt  1_seqinfo.txt   22_seqinfo.txt  4_seqinfo.txt  7_seqinfo.txt  MT_seqinfo.txt
12_seqinfo.txt  15_seqinfo.txt  18_seqinfo.txt  20_seqinfo.txt  2_seqinfo.txt   5_seqinfo.txt  8_seqinfo.txt  X_seqinfo.txt

**Comment by rvangara** [comment]
Hi @ruinw ,

Could you provide some more information on your input file(s) and JOB METADATA?

**Comment by ruinw** [comment]
Sorry,i didn't convey my means well.
It should be how can i use the result of SigProfilerMatrixGenerator to start SigProfilerExtractor。
this is my output file of&nbsp;SigProfilerMatrixGenerator



U:/mutation/ESCC/output$ ls
DBS ID SBS TSB vcf_files
U:/mutation/ESCC/output$ cd ID
U:/mutation/ESCC/output/ID$ ls
ESCC.ID28.all ESCC.ID332.all ESCC.ID415.all ESCC.ID83.all ESCC.ID8628.all ESCC.ID96.all
U:/mutation/ESCC/output/ID$ cd ..
U:/mutation/ESCC/output$ cd vcf_files/
U:/mutation/ESCC/output/vcf_files$ ls
DBS ID MNS SNV
U:/mutation/ESCC/output/vcf_files$ cd ID/
U:/mutation/ESCC/output/vcf_files/ID$ ls
10_seqinfo.txt 13_seqinfo.txt 16_seqinfo.txt 19_seqinfo.txt 21_seqinfo.txt 3_seqinfo.txt 6_seqinfo.txt 9_seqinfo.txt Y_seqinfo.txt
11_seqinfo.txt 14_seqinfo.txt 17_seqinfo.txt 1_seqinfo.txt 22_seqinfo.txt 4_seqinfo.txt 7_seqinfo.txt MT_seqinfo.txt
12_seqinfo.txt 15_seqinfo.txt 18_seqinfo.txt 20_seqinfo.txt 2_seqinfo.txt 5_seqinfo.txt 8_seqinfo.txt X_seqinfo.txt



ruin007
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "AlexandrovLab/SigProfilerExtractor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月17日(星期四) 凌晨5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlexandrovLab/SigProfilerExtractor] Hello，i want to know how can i use the result to start SigProfilerExtractor? (Issue #175)





 
Hi @ruinw ,
 
Could you provide some more information on your input file(s) and JOB METADATA?

**Comment by marcos-diazg** [comment]
Dear @ruinw,

Thanks for contacting us. I would strongly suggest you to use SigProfilerExtractor directly using your VCF/MAF files as input, by setting the `input_type` parameter to "vcf". Like this, SigProfilerMatrixGenerator will be run automatically by SigProfilerExtractor. I will also suggest to check our [wiki page](https://osf.io/t6j7u/wiki/home/) and our [video tutorials](https://github.com/AlexandrovLab/SigProfilerExtractor#video_tutorials) that can guide you on how to run SigProfilerExtractor and the different options and parameters available.

I hope this helps, and please feel free to reopen the ticket in case you still have any issues.
