### ISSUE TITLE
Error when extracting signatures with SBS96 matrix generated from SigProfilerMatrixGenerator

### ISSUE THREAD

**Issue by tc86** [AlexandrovLab/SigProfilerExtractor#176]
Hi, Thank you for developing this useful tool. I am facing a problem while running the latest version of the tool with the input matrix file (SBS96 specifically) generated by the SigProfilerMatrixGenerator tool. 
The tool starts to run okay but stops after extracting 1 signature, even when "maximum_signatures" is set to 10. And the following Error message was printed in the terminal

_There may be an issue with the formatting of your matrix file.
_Traceback (most recent call last):_
  _File "/hpcenv/mambaforge/envs/snakemake/lib/python3.10/site-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 1147, in plotSBS_
    _pp = PdfPages(os.path.join(output_path, 'SBS_96_plots_' + project + '.pdf'))_
  _File "/hpcenv/mambaforge/envs/snakemake/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 2623, in_ __init__
    _self._file = PdfFile(filename, metadata=metadata)_
  _File "/hpcenv/mambaforge/envs/snakemake/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 637, in __init__
    fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)_
  _File "/hpcenv/mambaforge/envs/snakemake/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 462, in to_filehandle
    fh = open(fname, flag, encoding=encoding)_
_FileNotFoundError: [Errno 2] No such file or directory:_ _'sbs96_results/SBS96/All_Solutions/SBS96_1_Signatures/Signatures/Signature_plot/SBS_96_plots_S1.pdf'_

_During handling of the above exception, another exception occurred:_

_Traceback (most recent call last):_
  _File "<stdin>", line 1, in <module>_
  _File "/hpcenv/mambaforge/envs/snakemake/lib/python3.10/site-packages/SigProfilerExtractor/sigpro.py", line 789, in_ _sigProfilerExtractor_
    _sub.export_information(loopResults, m, layer_directory, index, colnames, wall=wall, sequence=sequence)_
  _File "/hpcenv/mambaforge/envs/snakemake/lib/python3.10/site-packages/SigProfilerExtractor/subroutines.py", line 1118, in export_information_
    _plot.plotSBS(signature_subdirectory+"/"+mutation_type+"_S"+str(i)+"_Signatures"+".txt", _signature_subdirectory+"/Signature_plot", "S"+str(i), m, True, custom_text_upper=stability_list, custom_text_middle=total_mutation_list)__
  _File "/hpcenv/mambaforge/envs/snakemake/lib/python3.10/site-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 1163, in plotSBS_
    _os.remove(os.path.join(output_path, 'SBS_96_plots_' + project + '.pdf'))_
_FileNotFoundError: [Errno 2] No such file or directory:_ _'sbs96_results/SBS96/All_Solutions/SBS96_1_Signatures/Signatures/Signature_plot/SBS_96_plots_S1.pdf'__

But when I run the tool with the DBS78 matrix generated from the same sample set, it finishes running successfully with all the expected output files. 
Also note that with the previous version of SigProfilerExtractor I was able to run the tool successfully with the SBS96 matrix but was getting error with the DBS78 matrix which was mentioned in other previously reported issues here. And as per suggestion from those issues I updated the tools (SigProfilerExtractor, SigProfilerPlotting) from github with the latest version which solved the DBS78 error issue but now facing this SBS96 matrix file issue. 
I have attached the job metadata file here too.  
I appreciate any solutions you could provide on this. 
Thanks!
[JOB_METADATA.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/10023852/JOB_METADATA.txt)

**Comment by rvangara** [comment]
Hi @tc86 ,

Can you please try running your  SBS96 matrix with SigProfilerPlotting 1.2.2 ?

In the same env that you have your tools installed , please install `pip install SigProfilerPlotting=1.2.2` and then run and please let us know if it you are having the same issue.

**Comment by mattiyeh** [comment]
i think this is related to my issue #173 . The folder is not being created beforehand so the program fails when trying to create SBS_96_plots_project.pdf.

I suppose this can be fixed in either SigProfilerExtractor or SigProfilerPlotting but i didn't see any patches for this issue and i am running SPE 1.1.15 and SPP 1.3.3

**Comment by rvangara** [comment]
Hi @mattiyeh,

Please try using SigProfilerPlotting=1.2.2 as mentioned in previous suggestion and send me the file you are trying to plot with the latest version. 

Thanks
Ravi.
