### ISSUE TITLE
docker update

### ISSUE THREAD

**Issue by snashraf** [AlexandrovLab/SigProfilerExtractor#179]
Dear team,

Do you have any plan for updating dockerized SigProfilerExtractor? 

https://registry.hub.docker.com/r/zlskidmore/sigprofilerextractor

It would be good if you updated it with the latest one.

Regards,
Najeeb

**Comment by marcos-diazg** [comment]
Dear @snashraf,

Thanks for your interest. Our lab does not currently have any official dockerized version of SigProfilerExtractor. Regarding the specific version you mentioned, you may need to contact the authors themselves. We will let you know about future updates in this regard.
