### ISSUE TITLE
What does these subfolders means?

### ISSUE THREAD

**Issue by MaryGoAround** [AlexandrovLab/SigProfilerExtractor#18]
Hi

I have run your software on a couple of my samples (.VCF) 

In output I see some sub folders like

```
SBS96_1_Signatures
SBS96_2_Signatures
SBS96_3_Signatures
SBS96_4_Signatures
SBS96_5_Signatures
```

Does this mean that 5 signatures have found in my data? Why only you divided 5 signatures in an accumulative way in 5 sub folders?
If I want to select the best signatures defining my samples (overall), which sub folder I should look?

Please help me to get these

I really could not figure out the meaning of output even by reading the wiki pages several times

Thanks for any help in advance

**Comment by mishugeb** [comment]
Do you have a subfolder named "selected solutions"? Inside that, you will see two more subfolders named "de_novo_solutions" and "decomposed_solutions". Inside the de_novo_solution subfolder, you will see the selected solution of the de novo signatures. Inside the decomposed subfolder, you will see the decomposed solutions with the COSMIC signatures.

**Comment by MaryGoAround** [comment]
Thanks a million

In de novo sub folder I see `Signature_plotSBS_96_plots_De_Novo_Solution.pdf` with three signatures

So these 3 signatures have been extracted from my data

To know what these 3 signatures are, shall I compare them with something to get an idea what those are?

**Comment by mishugeb** [comment]
You can look at the Decomposed signatures subfolder to see the COSMIC signatures you found in the dataset
