### ISSUE TITLE
Generating plots for COSMIC_v3.3_DBS_GRCh37 now...

### ISSUE THREAD

**Issue by JLiandbear** [AlexandrovLab/SigProfilerExtractor#182]
Hello, 
Really appreciate your support towards the analysis of SigProfiler.
I have noticed something a bit strange during my analysis. Would be grateful to confirm with you whether this is a real concern.
Here's my command:
>>> data="/mnt/research-data/SigProfiler/vcf"
>>> sig.sigProfilerExtractor("vcf", "Extractor_test", data, reference_genome="GRCh38", opportunity_genome = "GRCh38", exome = True, minimum_signatures=1, maximum_signatures=2)

I notice on screen message, it used COSMIC_v3.3_DBS_GRCh37 and COSMIC_v3.3_SBS_GRCh37 to generate plots.
" Decomposing De Novo Signatures .....
Generating plots for COSMIC_v3.3_DBS_GRCh37 now...
Plots for COSMIC_v3.3_DBS_GRCh37 have been successfully installed.
Decompositon Plot:DBS78A |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%]

Assigning decomposed signature
|████████████████████████████████████████| 74/74 [100%] in 0.5s (163.88/s)

Your Job Is Successfully Completed! Thank You For Using SigProfilerAssignment."

My data was based on GRCh38 and I installed GRCh38 reference genome using command:

  >>> from SigProfilerMatrixGenerator import install as genInstall
  >>> genInstall.install('GRCh38', bash=True)

I looked into COSMIC Mutational Signatures Data Files and there're GRCh38 SBS and DBS versions.

I am wondering whether I am using wrong settings? Please advise where I am possibly wrong.
Here's the version info of installations:
Successfully installed PyMuPDF-1.21.0 PyPDF2-2.11.2 SigProfilerAssignment-0.0.20 SigProfilerExtractor-1.1.16 SigProfilerMatrixGenerator-1.2.13 about-time-3.1.1 alive-progress-2.4.1 cycler-0.11.0 grapheme-0.6.0 joblib-1.2.0 kiwisolver-1.4.4 matplotlib-3.4.3 nimfa-1.4.0 numpy-1.23.5 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 packaging-21.3 pandas-1.5.2 patsy-0.5.3 pdf2image-1.16.0 pillow-9.3.0 psutil-5.9.4 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.6 reportlab-3.6.12 scikit-learn-1.1.3 scipy-1.9.3 sigProfilerPlotting-1.3.6 statsmodels-0.13.5 threadpoolctl-3.1.0 torch-1.13.0 typing_extensions-4.4.0

Thank you very much

**Comment by mdbarnesUCSD** [comment]
Hi @JLiandbear,

Thank you for reaching out with this issue. This issue is specific to the decomposition plots and was introduced with the v0.0.20 SigProfilerAssignment update and should be resolved in [SigProfilerAssignment's v0.0.21 update (pull request #60).](https://github.com/AlexandrovLab/SigProfilerAssignment/pull/60) Please reach out if you continue to receive this issue after updating SigProfilerAssignment to v0.0.21.

Thanks,
Mark
