### ISSUE TITLE
Runtime Error: freeze_support() and dependency issues?

### ISSUE THREAD

**Issue by roseisgold** [AlexandrovLab/SigProfilerExtractor#184]
Hi! I am having issues running SigProfilerExtractor-- and I'm struggling to debug this issue. Have you seen this before? Do you have any tips on how to debug? Thanks!!

<img width="702" alt="Screenshot 2022-12-12 at 15 14 15" src="https://user-images.githubusercontent.com/112878116/207067411-43dfbc63-304f-4cd9-8ac3-624eefc35b06.png">
<img width="1270" alt="Screenshot 2022-12-12 at 15 14 27" src="https://user-images.githubusercontent.com/112878116/207067453-7b85c4ac-48ee-4a36-8188-f7d4835aa23b.png">

**Comment by mdbarnesUCSD** [comment]
Hi,

To resolve this issue please include `if __name__ == "__main__":` in your script:

```
from SigProfilerExtractor import sigpro as sig
if __name__ == "__main__":
    sig.sigProfilerExtractor(input_type,...)
```

See from #88.

Thanks!

**Comment by roseisgold** [comment]
Thank you!!
