### ISSUE TITLE
Bug in 96 plot tri-nucleotide context naming?

### ISSUE THREAD

**Issue by jlevatic** [AlexandrovLab/SigProfilerExtractor#195]
Dear developers,

I've noticed that in the SBS96 plots, the names of tri-nucleotide contexts are mixed up (see attached image). It seems the order is correct, just the labels in x-axis are mixed up.

I'm using the following versions:
sigprofilerassignment 0.0.21       
sigprofilermatrixgenerator 1.2.13 
sigprofilerplotting 1.3.6 

![SBS96_contexts](https://user-images.githubusercontent.com/20645225/216992593-8c8bc5b1-0166-41ae-b585-f20dee96ca51.PNG)

**Comment by mdbarnesUCSD** [comment]
Hi @jlevatic,

Yes, sigProfilerPlotting v1.3.6 and v1.3.7 are erroneous releases so please update to the latest releases for sigProfilerPlotting (v1.3.11) and SigProfilerAssignment (v0.0.26).

Please reach out if you encounter any additional issues. Thanks!
