### ISSUE TITLE
Bacterial genomes?

### ISSUE THREAD

**Issue by cyrusmallon** [AlexandrovLab/SigProfilerExtractor#197]
Hi, quick question, is it possible to use SigProfilerExtractor on bacterial genomes?
Thank you.

**Comment by mdbarnesUCSD** [comment]
Hi @cyrusmallon,

Do you have a specific genome that you would like to use?

Thanks!

**Comment by mdbarnesUCSD** [comment]
Please reopen this issue for further support.
