### ISSUE TITLE
mm39 reference genome?

### ISSUE THREAD

**Issue by conormcguinness9016** [AlexandrovLab/SigProfilerExtractor#198]
Is it possible to use SigProfilerExtractor with the mm39 reference genome?

**Comment by mdbarnesUCSD** [comment]
Hi @conormcguinness9016,

Yes, you can download the [reference genome using SigProfilerMatrixGenerator](https://github.com/alexandrovlab/SigProfilerMatrixGenerator) and the list of supported genomes are under the section "SUPPORTED GENOMES". Please reach out if you have any more questions.

Thanks!
