### ISSUE TITLE
Run SigProfilerExtractor without a reference

### ISSUE THREAD

**Issue by gamabunta313** [AlexandrovLab/SigProfilerExtractor#199]
I am working o the immunological repertoire of lymphoproliferative disorders. Functional B and T cell receptors originates from genomic recombination of hypermutated genes. It is clear that it is not possible to generate a vcf with genomic coordinates since, there is NO  "absolute" genomic reference. I am able to reproduce the 96 row- matrix to test whether any signature is found (i.e. A[C>T]T mutation count). Is it possible to run SigProfilerExtractor without the reference genome using as input the matrix? Thanks in advance for your help

**Comment by marcos-diazg** [comment]
Hi @gamabunta313,

Thanks so much for your interest! Sure, you can run SigProfilerExtractor using a mutational matrix as input. You just need to use "matrix" as the `input_type`.

I hope this helps, and feel free to reach out if you have further questions.
