### ISSUE TITLE
Some errors and question

### ISSUE THREAD

**Issue by yoonicon** [AlexandrovLab/SigProfilerExtractor#200]
Thank you for your sharing.

I have one question and one error.

First, my question is that whether I can compared somatic mutations of two ALS patient groups. I have two groups of VCF files and can i compared somatic mutation between them.

And second, using SigprofilerExtractor, I met an error, which is "index out of range". Here is my error code.

-------------------------
Cell In[13], line 1
----> 1 sig.sigProfilerExtractor('vcf', './example/output', './example', minimum_signatures=1, maximum_signatures=3)

File ~/.local/lib/python3.10/site-packages/SigProfilerExtractor/sigpro.py:542, in sigProfilerExtractor(input_type, output, input_data, reference_genome, opportunity_genome, cosmic_version, context_type, exome, minimum_signatures, maximum_signatures, nmf_replicates, resample, batch_size, cpu, gpu, nmf_init, precision, matrix_normalization, seeds, min_nmf_iterations, max_nmf_iterations, nmf_test_conv, nmf_tolerance, nnls_add_penalty, nnls_remove_penalty, initial_remove_penalty, collapse_to_SBS96, clustering_distance, export_probabilities, make_decomposition_plots, stability, min_stability, combined_stability, allow_stability_drop, get_all_signature_matrices)
    539 elif input_type=="vcf":
    540     ################################# For vcf input files #######################################################
    541     title = project # set the title for plotting
--> 542     data = datadump.SigProfilerMatrixGeneratorFunc(project_name, refgen, project, exome=exome,  bed_file=None, chrom_based=False, plot=False, gs=False)
    543     # Selecting the MutationType
    544     if mtype == ["default"]:

File ~/.local/lib/python3.10/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py:470, in SigProfilerMatrixGeneratorFunc(project, genome, vcfFiles, exome, bed_file, chrom_based, plot, tsb_stat, seqInfo, cushion, gs)
    466 lines = sorted(lines, key = lambda x: (x[0], int(x[2])))
    469 context = '6144'
--> 470 mutation_pd, skipped_mut, total, total_DINUC, mutation_dinuc_pd_all = matGen.catalogue_generator_single (lines, chrom, mutation_pd, mutation_dinuc_pd_all, mutation_types_tsb_context, vcf_path, vcf_path_original, vcf_files, bed_file_path, chrom_path, project, output_matrix, context, exome, genome, ncbi_chrom, functionFlag, bed, bed_ranges, chrom_based, plot, tsb_ref, transcript_path, tsb_stat, seqInfo, gs, log_file)
    472 if chrom_based and not exome and not bed:
    473 	matrices = matGen.matrix_generator (context, output_matrix, project, samples, bias_sort, mutation_pd, exome, mut_types, bed, chrom, functionFlag, plot, tsb_stat)

File ~/.local/lib/python3.10/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator.py:358, in catalogue_generator_single(lines, chrom, mutation_dict, mutation_dinuc_pd_all, mutation_types_tsb_context, vcf_path, vcf_path_original, vcf_files, bed_file_path, chrom_path, project, output_matrix, context, exome, genome, ncbi_chrom, functionFlag, bed, bed_ranges, chrom_based, plot, tsb_ref, transcript_path, tsb_stat, seqInfo, gs, log_file)
    355 mut_seq += previous_mut
    357 for l in range(start1+1, start2, 1):
--> 358 	mnv_seq += tsb_ref[chrom_string[l-1]][1]
    359 	mut_seq += tsb_ref[chrom_string[l-1]][1]
    361 if i < len(mnv_index) -1 :

IndexError: index out of range
---------------------------------------

Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @yoonicon,

Could you please include your JOB_METADATA file?

Thanks!

**Comment by mdbarnesUCSD** [comment]
Please reopen this issue if you have any further questions.
