### ISSUE TITLE
TypeError in SigProfiler Extractor in concat

### ISSUE THREAD

**Issue by pushpa-itagi** [AlexandrovLab/SigProfilerExtractor#202]
__ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
TypeError: can only concatenate str (not "int") to str__

Hi,
I am trying to run the sigProfilerEXtractor method by using the same syntax as one of the samples in your test code as input, and I get a concat error.
Two weeks ago, I tried this method and it had worked for the same file and my sample files as well. Not sure, what is causing errors now. For your reference, I have attached my code, input sample file and METADAT.txt
Please let me know if there is something that I am missing here.

Files are here:
[JOB_METADATA.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/10913464/JOB_METADATA.txt

[test_out.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/10913497/test_out.txt)

Code 
  _data = "19-007/test_out.txt"
    
    sig.sigProfilerExtractor( "matrix", "19-007", data, reference_genome="GRCh38", opportunity_genome = "GRCh38", context_type = "default", exome = False,
                         minimum_signatures=1, maximum_signatures=10, nmf_replicates=100, resample = True, batch_size=1, cpu=-1, gpu=False,
                         nmf_init="random", precision= "single", matrix_normalization= "gmm", seeds= "random",
                         min_nmf_iterations= 10000, max_nmf_iterations=1000000, nmf_test_conv= 10000, nmf_tolerance= 1e-15, get_all_signature_matrices= False)_

Thanks
Pushpa Itagi

**Comment by mdbarnesUCSD** [comment]
Hi @pushpa-itagi,

It looks like your data is a vcf file and you are currently passing "matrix" as a parameter. Please try using "vcf".

Thanks!
