### ISSUE TITLE
Enable redirection of output files

### ISSUE THREAD

**Issue by RubenRam** [AlexandrovLab/SigProfilerExtractor#204]
After checking the **SigProfilerMatrixGeneratorFunc** implementation, I've noticed that the output path, the error path and the log path depend on the input path. From a shared computational environment point of view, this is not ideal. Would it be possible to add a way to change this behavior and be able to redirect elsewhere the output?

Despite having an output parameter, after installing the GRCh37 genome, when using the sample code provided:
```
from SigProfilerExtractor import sigpro as sig
path_to_example_folder_containing_vcf_files = sig.importdata("vcf")
data = path_to_example_folder_containing_vcf_files
sig.sigProfilerExtractor("vcf", "example_output", data, minimum_signatures=1, maximum_signatures=3)
```

I just get _some_ of the ouput but not the logs or out and err:
```
(SigProfilerExtractor) bash-4.4$ ls -ltrah example_output2
total 16K
drwx------ 27 rubenram its 8,0K mar 22 15:52 ..
drwxr-xr-x  2 rubenram its 4,0K mar 22 15:52 .
-rw-r--r--  1 rubenram its   48 mar 22 15:57 Seeds.txt
-rw-r--r--  1 rubenram its  556 mar 22 15:57 JOB_METADATA.txt
```

Thanks for considering this suggestion in advance.

**Comment by mdbarnesUCSD** [comment]
Hi @RubenRam,

Could you please clarify if the issue with the output and error messages is from SigProfilerExtractor or SigProfilerMatrixGenerator?

Thanks!
