### ISSUE TITLE
OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by maia-munteanu** [AlexandrovLab/SigProfilerExtractor#207]
Hi,

I'm currently trying to run SigProfilerExtractor as part of a nextflow pipeline, processing the matrix files generated by SigProfilerMatrixGenerator. 

This is the python script I'm using:
https://github.com/maia-munteanu/Mutation_clustering/blob/main/SignatureExtractor.py

The matrix file used is created by the SigProfilerMatrixGenerator tools and the metadata is below.
[JOB_METADATA.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/11452045/JOB_METADATA.txt)

**The error I'm getting is:**

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 1027, in plotSBS
    fig_orig=make_pickle_file(context='SBS96', return_plot_template=True, volume=volume)
  File "/usr/local/lib/python3.8/dist-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 129, in make_pickle_file
    os.mkdir(volume)
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.8/dist-packages/sigProfilerPlotting/templates/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g/strcombio/fsupek_cancer1/SV_clusters_project/nextflow_pipeline/Mutation_clustering/SignatureExtractor.py", line 15, in <module>
    main_function()
  File "/g/strcombio/fsupek_cancer1/SV_clusters_project/nextflow_pipeline/Mutation_clustering/SignatureExtractor.py", line 13, in main_function
    sig.sigProfilerExtractor("matrix", "./Unclustered/Signatures", "./Unclustered/unclustered.SBS96.all", reference_genome="GRCh37", minimum_signatures=1, maximum_signatures=5, nmf_replicates=100, cpu=1)
  File "/usr/local/lib/python3.8/dist-packages/SigProfilerExtractor/sigpro.py", line 793, in sigProfilerExtractor
    sub.export_information(loopResults, mutation_type, layer_directory, index, colnames, wall=wall, sequence=sequence)
  File "/usr/local/lib/python3.8/dist-packages/SigProfilerExtractor/subroutines.py", line 1110, in export_information
    plot.plotSBS(signature_subdirectory+"/"+mutation_type+"_S"+str(i)+"_Signatures"+".txt", signature_subdirectory+"/Signature_plot", "S"+str(i), tmp_m, True, custom_text_upper=stability_list, custom_text_middle=total_mutation_list)
  File "/usr/local/lib/python3.8/dist-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 1172, in plotSBS
    os.remove(os.path.join(output_path, 'SBS_96_plots_' + project + '.pdf'))
FileNotFoundError: [Errno 2] No such file or directory: './Unclustered/Signatures/SBS96/All_Solutions/SBS96_1_Signatures/Signatures/Signature_plot/SBS_96_plots_S1.pdf'

**From the stdout file, I'm also getting this message:**

************** Reported Current Memory Use: 0.33 GB *****************

Extracting signature 1 for mutation type 96
The matrix normalizing cutoff is 59057

process 1 continues please wait... 
execution time: 2 seconds 

process 1 continues please wait... 
execution time: 3 seconds 

process 1 continues please wait... 
execution time: 2 seconds 
 **.....**
process 1 continues please wait... 
execution time: 2 seconds 

Time taken to collect 100 iterations for 1 signatures is 179.1 seconds
Optimization time is 2.5346157550811768 seconds
The reconstruction error is 0.2496, average process stability is 1.0 and 
the minimum process stability is 1.0 for 1 signatures

There may be an issue with the formatting of your matrix file.

I read in the other issues that the **Errno2 No such file of directory error** is due to issues with older versions of SigProfilerPlotting, but as far as I can tell I am using the latest version, 1.3.13. I also couldn't find any references to the other error, Errno 30. Note that I am running SigProfiler within a singularity container, but I'm not sure if this has anything to do with it. I can run SigProfilerMatrixGenerator and SigProfilerClusters within the same container with no issues. As far as I can tell the matrix file unclustered.SBS96.all is fine because the first signature is generated in the Signatures directory, but the signature spectrum plot is not. Do you have any idea what might be generating these errors?

Thanks,
Maia

**Comment by mdbarnesUCSD** [comment]
Hi @maia-munteanu,

The repositories are currently being updated to support moving post-installation files from the site-packages to a user defined location. The current implementation causes issues when running the code using a docker or singularity container, since plotting templates are being installed to a destination that does not have write access. I believe this is the error that you are seeing.

Until further updates have been made, please run using a python environment.

Thanks!
