### ISSUE TITLE
possible to change minimum signatures?

### ISSUE THREAD

**Issue by kerstinth** [AlexandrovLab/SigProfilerExtractor#208]
Hi, 

I was wondering if it is possible to change the minimum number of signatures?

I am running sigprofiler extractor on ~400 tumour samples with minimum signatures = 1 and maximum signatures = 25. Unfortunately, my job timed out at 10 signatures. Is it possible to set the minimum number of signatures to 11 in order to continue extracting signatures 11-25? I tried setting the minimum_signatures parameter to 11, but when I did this it stayed at 1 in the JOB_METADATA.txt file. So I tried also manually changing minimum_signatures to 11 in the JOB_METADATA.txt but again, when I ran the job it changed back to 1 in the metadata file.

Any help with this would be greatly appreciated!

Best Wishes
Kerstin

**Comment by mdbarnesUCSD** [comment]
Hi @kerstinth,

Please use `sigProfilerExtractor(...,minimum_signatures=11, maximum_signatures=25)` in order to set the maximum and minimum number of signatures for the extraction. You will want to make sure that the script you are running is updated to reflect these changes.

**Comment by mdbarnesUCSD** [comment]
Please reach out if you encounter any more issues.
