### ISSUE TITLE
How to extrat?

### ISSUE THREAD

**Issue by XuanYuXu** [AlexandrovLab/SigProfilerExtractor#21]
When I did this ,there some problems ,but I do not know why,anyone can help me ?

In [21]: a = sig.importdata("vcf")

In [22]:  sig.sigProfilerExtractor("vcf", "example_output", "PD3851a", minimum_signatures=1, maximum_signatures=3)

************** Reported Current Memory Use: 0.14 GB *****************

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-22-93de97d63016> in <module>
----> 1 sig.sigProfilerExtractor("vcf", "example_output", "PD3851a", minimum_signatures=1, maximum_signatures=3)

C:\Anaconda3\lib\site-packages\SigProfilerExtractor\sigpro.py in sigProfilerExtractor(input_type, output, input_data, reference_genome, opportunity_genome, context_type, exome, minimum_signatures, maximum_signatures, nmf_replicates, resample, batch_size, cpu, gpu, nmf_init, precision, matrix_normalization, seeds, min_nmf_iterations, max_nmf_iterations, nmf_test_conv, nmf_tolerance, nnls_penalty, get_all_signature_matrices)
    513
    514         #project_name = project.split("/")[-1]
--> 515         data = datadump.SigProfilerMatrixGeneratorFunc(project_name, refgen, project, exome=exome,  bed_file=None, chrom_based=False, plot=False, gs=False)
    516
    517

C:\Anaconda3\lib\site-packages\SigProfilerMatrixGenerator\scripts\SigProfilerMatrixGeneratorFunc.py in SigProfilerMatrixGeneratorFunc(project, genome, vcfFiles, exome, bed_file, chrom_based, plot, tsb_stat, seqInfo, cushion, gs)
    340
    341         # Creates a temporary folder for sorting and generating the matrices
--> 342         file_name = vcf_files[0].split(".")
    343         file_extension = file_name[-1]
    344         unique_folder = project + "_"+ str(uuid.uuid4())

IndexError: list index out of range

**Comment by mishugeb** [comment]
Hi,
You need use "a" as input instead of "PD3851a".

Thanks

**Comment by XuanYuXu** [comment]
> Hi,
> You need to use "a" as input instead of "PD3851a".
> 
> Thanks

OK，thanks,I get it .But do you know how to use cosmic signatures to indicate the mutation matrix, and do not need to extract new signatures ?

**Comment by mishugeb** [comment]
you can use SigProfilerSingleSample for that purpose:
https://github.com/AlexandrovLab/SigProfilerSingleSample.git
