### ISSUE TITLE
install own copy of genome

### ISSUE THREAD

**Issue by me-nobody** [AlexandrovLab/SigProfilerExtractor#213]
Hi,
I work within the Genomics England Research environment. Getting data in and out is difficult. for local install, can we install a copy of the genome available within the Genomics England Research environment?

**Comment by mdbarnesUCSD** [comment]
I believe that this is a similar question this [#87 on SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment/issues/87). I am going to close this one since it has been answered there.
