### ISSUE TITLE
Cosine similarity for each COSMIC signature

### ISSUE THREAD

**Issue by nash5202** [AlexandrovLab/SigProfilerExtractor#215]
Hi, 

Is there a way in SigProfilerExtractor to get cosine similarity of the suggested solution to each of the existing COSMIC signatures? For instance, for SBS96 signatures. 

Thank you.

Best regards,
Nash

**Comment by mdbarnesUCSD** [comment]
Hi @nash5202,

This is not a functionality that SigProfilerExtractor supports. Please reach out if you have any other questions.

Thanks!
