### ISSUE TITLE
calculate cosine similarity

### ISSUE THREAD

**Issue by me-nobody** [AlexandrovLab/SigProfilerExtractor#216]
Hi,
is there some way to calculate the cosine similarity of 2 denovo signature matrices? I am able to compare the cosmic deconvoluted ones, but how do i compare the denovo signatures? I apologize that I am from a non-mathematical  background.
Many Thanks,
Anubrata

**Comment by mdbarnesUCSD** [comment]
Hi @me-nobody,

SigProfilerExtractor does not support this functionality. There are many resources online, like scikit-learn, that can help with this.
