### ISSUE TITLE
Inquiry Regarding sigProfilerExtractor Resource Requirements

### ISSUE THREAD

**Issue by ShinXeno** [AlexandrovLab/SigProfilerExtractor#219]
Hi,
I am writing to inquire about the resource requirements for sigProfilerExtractor when extracting SBS signatures. Specifically, I am interested in knowing how many threads and how much memory are typically needed for this process.

My input data consists of a matrix for SBS1536 from 1,900 samples. I am running this analysis with a CPU limit of 16 cores. Could you please provide an estimate of the time it would take to complete this analysis under these conditions?

Your guidance on the resource requirements and expected runtime would be greatly appreciated as it will help me plan and optimize my analysis effectively.

Thank you for your time and assistance. I look forward to hearing from you and receiving guidance on this issue.

**Comment by mdbarnesUCSD** [comment]
Hi @ShinXeno,

Thank you for reaching out. It may help for you to extrapolate from a test run to better understand the resources your infrastructure requires:

- **Key Parameters**: Do consider the parameters in the NMF Replicate and NMF Engines sections of the README. These are known to impact runtime, specifically the ones that pertain to the multiplicative updates.

- **Benchmarking**: A practical approach might be to run a shorter test. For instance, if you can try 16 NMF replicates at rank 30 with default parameters, it would give a better sense of the max run time at a rank. You could extrapolate the required time for 100 replicates and have an approximate worst case time for each rank (lower ranks can be significantly faster).

- **Worst-case Estimate**: From the benchmark, multiplying the runtime of the worst case rank by 30 signatures (covering `minimum_signatures=1` to `maximum_signatures=30`) can offer a ballpark estimate. However, remember the impact of the `max_nmf_iterations` parameter. If many replicates hit or approach this max, it could extend the actual runtime.

I hope this helps.
