### ISSUE TITLE
How to use cosmic signatures to indicate the mutation matrix?

### ISSUE THREAD

**Issue by XuanYuXu** [AlexandrovLab/SigProfilerExtractor#22]
Did anyone knows how to use cosmic signatures to fit the muations,and do not need to extract new signatures ? I do not want to extract new signatures, because it neeed a lot of time for big mutation samples.
Please help me ,thanks!

**Comment by mishugeb** [comment]
Hi, 
Please visit https://github.com/AlexandrovLab/SigProfilerSingleSample or https://pypi.org/project/sigproSS/ to learn how to fit COSMIC signatures to your samples without doing NMF.

**Comment by XuanYuXu** [comment]
> Hi,
> Please visit https://github.com/AlexandrovLab/SigProfilerSingleSample or https://pypi.org/project/sigproSS/ to learn how to fit COSMIC signatures to your samples without doing NMF.

Thanks,but the first website does not work...

**Comment by XuanYuXu** [comment]
> > Hi,
> > Please visit https://github.com/AlexandrovLab/SigProfilerSingleSample or https://pypi.org/project/sigproSS/ to learn how to fit COSMIC signatures to your samples without doing NMF.
> 
> Thanks,but the first website does not work...

I got it ,but the type you input must be 'vcf'?Can it be 'matrix'?

**Comment by mishugeb** [comment]
Sorry, we don't support matrix since we need certain information from vcf to check the rules before fitting signatures.

**Comment by XuanYuXu** [comment]
OK,thanks anyway.
