### ISSUE TITLE
interpretation for SBS 96D

### ISSUE THREAD

**Issue by sainadfensi** [AlexandrovLab/SigProfilerExtractor#220]
Hi SigProfilerExtractor team,

Thank you for the developing and maintenance of this great signature tool.
I've got signature SBS96D as one of the results, but there is no SBS 96 in the website (https://cancer.sanger.ac.uk/signatures/sbs/). Can you give me some advice about it. Many thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @sainadfensi,

SBS96D is a de novo signature in your output. If you view your COSMIC decomposed solution directory, you can see into which COSMIC signatures it decomposes.

Please refer to the [wiki](https://osf.io/t6j7u/wiki/home/) for more information about the output. 

Thanks!

**Comment by sainadfensi** [comment]
Hi @mdbarnesUCSD,

Thank you for the prompt reply, super appreciated! 
Yes, you are right that 96D is not decomposed. I assume that because I don't allow enough signatures, so the decomposed signatures of 96D is not shown, instead 96D is shown in the activities results. I'll try larger values for the maximum signatures.

**Comment by sainadfensi** [comment]
Hi @mdbarnesUCSD,
I increased the maximum signatures to 25, but still have un-decomposed signature (e.g. SBS96H this time):
header of COSMIC_SBS96_Activities.txt: 
Samples	SBS1	SBS3	SBS5	SBS8	SBS15	SBS18	SBS21	SBS30	SBS32	SBS33	SBS37	SBS38	SBS39	SBS40	SBS41	SBS49	SBS52	SBS96H

Can you give me some advice for this situation? Thank you very much.

**Comment by MousumyCSE** [comment]
Hi @sainadfensi,

SBS96H is also a de novo signature. Getting SBS96H from the decomposed activities means that this signature was not decomposed into any known COSMIC signatures (more specifically, that the reconstruction did not get a cosine similarity above 0.8).

For details you can have a look on SigProfilerExtractor manuscript(https://doi.org/10.1016/j.xgen.2022.100179), specifically within the method “Computational implementation of SigProfilerExtractor and its seven modules” section which includes a comprehensive explanation of signature decomposition.

Best,
Mousumy

**Comment by sainadfensi** [comment]
Hi @mdbarnesUCSD ,
I see! Thank you for the nice explanation. I'll keep the novel SBS96H is the results then.
