### ISSUE TITLE
SBS384 extraction problem

### ISSUE THREAD

**Issue by frvirard** [AlexandrovLab/SigProfilerExtractor#221]
Hi,
Signature extraction works well on my data for SBS96 and SBS288 contexts, but gives me weird results for SBS384 (see last signature plot)
![image](https://github.com/AlexandrovLab/SigProfilerExtractor/assets/74251513/0cbf56c5-d225-44bb-b22f-61c27d238c5b)
![image](https://github.com/AlexandrovLab/SigProfilerExtractor/assets/74251513/cd0b02a9-9574-4a1d-9522-2d8d928fe73a)
![image](https://github.com/AlexandrovLab/SigProfilerExtractor/assets/74251513/528d23a7-e7ec-4e79-bb23-e7aa5198475b)
[SBS384_De-Novo_Signatures.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/12817959/SBS384_De-Novo_Signatures.txt)

I 'm running sigprofiler from R using SigProfilerExtractorR package.
I did a clean install of SigprofilerExtractor with pip install command inside a new environnement.

I enclose the log for SBS384 extraction
[JOB_METADATA.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/12817923/JOB_METADATA.txt)

Thanks a lot for your help.

Best
Francois VIRARD

**Comment by MousumyCSE** [comment]
Hi @frvirard,

Apologies for the late response.
Did you get the results for SBS384 after running with SigProfilerExtractor with R package or in python? 

Best,
Mousumy

**Comment by frvirard** [comment]
Thanks Mousumy for your response.

Signature seems to be OK.
Look like the problem is coming from the plot 
[SBS384_De-Novo_Signatures.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/13061851/SBS384_De-Novo_Signatures.txt)

Best 
Francois

**Comment by mdbarnesUCSD** [comment]
Hi @frvirard,

This issue has now been resolved in the [SigProfilerAssignment v0.0.33 release](https://github.com/AlexandrovLab/SigProfilerAssignment/releases/tag/v0.0.33), so please update your package. If you encounter any issues, please reach out. Thanks!

**Comment by frvirard** [comment]
Thanks a lot for the update. 
Denovo extraction plot is now working.

It would be great if SBS384 extraction could also be compatible with COSMIC decomposition.
Collapse to SBS96 seems to be available only for SBS288 and SBS1536 context.
