### ISSUE TITLE
error because of new pandas version

### ISSUE THREAD

**Issue by sainadfensi** [AlexandrovLab/SigProfilerExtractor#223]
Dear developer of SigProfiler,

I encountered an error of `AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?` after updating pandas to version >2.0.0 for another tool. The issue was solved after re-install an older version of pandas.

**Comment by rvangara** [comment]
Hello @sainadfensi,

Thank you for bringing this to our attention. Our development team is already informed about this compatibility concern. Rest assured, it will be addressed in upcoming versions of the SigProfiler tools. In the meantime, we recommend using Pandas versions earlier than 2.0.0.
