### ISSUE TITLE
Minimum number of mutations or genome length.

### ISSUE THREAD

**Issue by shenhaizhongdechanrao** [AlexandrovLab/SigProfilerExtractor#224]
Hello! I'd like to inquire whether it is advisable to exclusively use a specific gene region in constructing a signature.

**Comment by mdbarnesUCSD** [comment]
Hello, thanks for reaching out. It is not recommended to use a specific gene region for constructing a signature. Signatures are created using WGS or WES data. Additional information can be found at #180, thanks!
