### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys (decomposition.py error)

### ISSUE THREAD

**Issue by nan5895** [AlexandrovLab/SigProfilerExtractor#227]
I am trying to run SigprofilerExtract to get mutation signature results, but somehow I get an error below while doing the signature decomposition via sigprofilerassignment ...

```
There may be an issue with the formatting of your matrix file.


 De Novo Fitting .....
|████████████████████████████████████████| 1/1 [100%] in 0.0s (31.78/s)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/sigprofiler_v1_1_2/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 862, in sigProfilerExtractor
    decomp.spa_analyze(allgenomes, output, signatures=processAvg, genome_build=genome_build, cosmic_version=cosmic_version, exome=exome, verbose=False,
  File "/opt/conda/envs/sigprofiler_v1_1_2/lib/python3.9/site-packages/SigProfilerAssignment/decomposition.py", line 520, in spa_analyze
    final_signatures = sub.signature_decomposition(processAvg, mutation_type, layer_directory2, genome_build=genome_build,cosmic_version=cosmic_version,signature_database=signature_database, mutation_context=mutation_context, add_penalty=0.05, connected_sigs=connected_sigs,remove_penalty=0.01, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg,new_signature_thresh_hold=new_signature_thresh_hold,sig_exclusion_list=sig_exclusion_list,exome=exome, m_for_subgroups=m_for_subgroups)
  File "/opt/conda/envs/sigprofiler_v1_1_2/lib/python3.9/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 369, in signature_decomposition
    byte_plot = sp.run_PlotDecomposition(originalProcessAvg[denovo_cols],
  File "/opt/conda/envs/sigprofiler_v1_1_2/lib/python3.9/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 513, in run_PlotDecomposition
    denovo_plots_dict = convert_to_imgReaderDict(denovo_plots_dict)
  File "/opt/conda/envs/sigprofiler_v1_1_2/lib/python3.9/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 162, in convert_to_imgReaderDict
    for name in image_dict.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
There may be an issue with the formatting of your matrix file.

```

Previously, it worked with the below versions without using `SigprofilerAssignment`
```
 -------Python and Package Versions------- 
Python Version: 3.9.13
SigProfilerExtractor Version: 1.1.7
SigProfilerPlotting Version: 1.2.2
SigProfilerMatrixGenerator Version: 1.2.5
Pandas version: 1.4.2
Numpy version: 1.22.4
Scipy version: 1.8.1
Scikit-learn version: 1.1.1
```

However, after I updated the version SigprofilerExtract from `1.1.7` to `1.1.23` and SigprofilerAssignment version is `0.1.0`
I encountered the above error... should I downgrade my version??.. but I would like to apply COMIC sig 3.4v...which is not applied  old version...

Note ...
I scanned the `sigpro.py` in SigprofilerExtract, and it imports Python script `decomposition.py` at SigprofilerAssignment....
something wrong with for name in image_dict.keys() of decomposition.py .... what should i do ?

Again
Currently, the SigprofilerExtract version is `1.1.23`, and the SigprofilerAssignment version is `0.1.0`

**Comment by mdbarnesUCSD** [comment]
Hi @nan5895,

Thanks for reaching out. I would recommend updating your packages to the newest versions. There are cosmic plot templates that are saved to SigProfilerAssignment's site-packages that should also be removed to ensure no version issues occur. It may be easier to start with a new conda environment, and install the packages again.

If after doing this, you are still encountering the issue then it would be good to look at your input matrix to see that it is formatted correctly ([SBS96 example here](https://github.com/AlexandrovLab/SigProfilerExtractor/blob/master/SigProfilerExtractor/data/TextInput/Samples_SBS.txt)).

**Comment by nan5895** [comment]
Thank you for your response. It worked when I changed the input.

**Comment by nan5895** [comment]
Thank you for your response. It worked when I changed the input
