### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by SukanyaPanja** [AlexandrovLab/SigProfilerExtractor#228]
Hi 
when I try to run the SigProfileextractor, it goes into an infinite loop. Below is the screenshot of my error

![image](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/53057887/50b2c8d2-e62f-4415-9c59-54ab2f342c0c)

Basically it goes into an infinite loop.. I am not sure why this is happening. Can someone please help?

**Comment by mdbarnesUCSD** [comment]
Hi @SukanyaPanja,

It appears that you have run into an issue when running SigProfilerExtractor. Please take a look at #88 to see if it helps resolve your issue.

Thanks!
