### ISSUE TITLE
Issue with install

### ISSUE THREAD

**Issue by cutleraging** [AlexandrovLab/SigProfilerExtractor#229]
Hello, I am having troubles installing this into my environment

`pip install SigProfilerExtractor
Collecting SigProfilerExtractor
  Downloading SigProfilerExtractor-1.1.23-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: scipy>=1.6.3 in /gs/gsfs0/users/rcutler/.conda/envs/SigProfiler/lib/python3.12/site-packages (from SigProfilerExtractor) (1.11.4)
INFO: pip is looking at multiple versions of sigprofilerextractor to determine which version is compatible with other requirements. This could take a while.
  Downloading SigProfilerExtractor-1.1.22-py3-none-any.whl.metadata (18 kB)
  Downloading SigProfilerExtractor-1.1.21-py3-none-any.whl (491 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.4/491.4 kB 5.9 MB/s eta 0:00:00
  Downloading SigProfilerExtractor-1.1.20-py3-none-any.whl (491 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.4/491.4 kB 5.5 MB/s eta 0:00:00
  Downloading SigProfilerExtractor-1.1.19-py3-none-any.whl (310 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.4/310.4 kB 3.8 MB/s eta 0:00:00
  Downloading SigProfilerExtractor-1.1.18-py3-none-any.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 3.2 MB/s eta 0:00:00
  Downloading SigProfilerExtractor-1.1.17-py3-none-any.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 23.3 MB/s eta 0:00:00
  Downloading SigProfilerExtractor-1.1.16-py3-none-any.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 19.9 MB/s eta 0:00:00
INFO: pip is still looking at multiple versions of sigprofilerextractor to determine which version is compatible with other requirements. This could take a while.
  Downloading SigProfilerExtractor-1.1.15-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 9.7 MB/s eta 0:00:00
  Downloading SigProfilerExtractor-1.1.14-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 14.0 MB/s eta 0:00:00
Collecting matplotlib<=3.4.3,>=3.4.2 (from SigProfilerExtractor)
  Using cached matplotlib-3.4.3.tar.gz (37.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-w8yt9yy2/matplotlib_113a6fc1374d42d49b1442b8161695a0/setup.py", line 54, in <module>
          __version__ = versioneer.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-w8yt9yy2/matplotlib_113a6fc1374d42d49b1442b8161695a0/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-w8yt9yy2/matplotlib_113a6fc1374d42d49b1442b8161695a0/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-w8yt9yy2/matplotlib_113a6fc1374d42d49b1442b8161695a0/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`
Can you please help with this issue?

Thanks,
Ronnie

**Comment by mdbarnesUCSD** [comment]
Hi Ronnie,

Could you please check what version of pip you have installed and if  update it?
pip -V
pip install --upgrade pip

Thanks!

**Comment by cutleraging** [comment]
I was able to solve this issue by using Python 3.8. Thanks
