### ISSUE TITLE
Problems with large samples

### ISSUE THREAD

**Issue by WuRAFY** [AlexandrovLab/SigProfilerExtractor#23]
Hi,
    I have 3500 genomes to analysis, so the matrix I made has 3500 columns. And I did not pass the    parameter  "maximum_signatures" to sigProfilerExtractor. I find the default value of maximum_signtures is 10, but it has generated a subfolder name's SBS96_11_Signatures. When will it stop? Thanks

**Comment by mishugeb** [comment]
Hi, 
This is weird! Could you please send me the Job_METADATA file in the results folder? I need to check that. 

Thanks

**Comment by mishugeb** [comment]
Nevermind. I forgot that I have changed the default value of the maximum_signatures to 25 signatures in a recent update. So it will stop at 25 signatures by default.

**Comment by WuRAFY** [comment]
Oh, thanks for your reply
