### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (83,0) (0,0)

### ISSUE THREAD

**Issue by dineshpeace** [AlexandrovLab/SigProfilerExtractor#230]
Error msg:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dvelayutham/miniconda3/lib/python3.11/site-packages/SigProfilerExtractor/sigpro.py", line 752, in sigProfilerExtractor
    processes = sub.decipher_signatures(execution_parameters,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvelayutham/miniconda3/lib/python3.11/site-packages/SigProfilerExtractor/subroutines.py", line 565, in decipher_signatures
    H = results[j][1]
                      
ValueError: operands could not be broadcast together with shapes (83,0) (0,0)

############
>>> sig.sigProfilerExtractor("vcf", "results", "/mypath/VCFfolder", genome_build="GRCh37", minimum_signatures=1, maximum_signatures=10, nmf_replicates=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sigProfilerExtractor() got an unexpected keyword argument 'genome_build'

##For the above error, I ran without declaring genome_build as shown below

>>> sig.sigProfilerExtractor("vcf", "results", "mypath/VCFfolder")
sig.sigProfilerExtractor("vcf", "results", "/Users/dvelayutham/Documents/Collaborations/TTK modelling/SigExtract")
++++++++++++++
P.S: While installing genome I received error saying
/Users/dvelayutham/miniconda3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/references/vcf_files/GRCh37_bench doesn't exist.

I created folder GRCh37_bench and re-ran genome installation command and then the error was rectified.

Kindly suggest where the error could be. I have tried this is linux server and Macbook pro.

Dinesh

**Comment by dineshpeace** [comment]
Update: I tried to install through R and still faced issue with Reference Genome
#############################################################
...
798750K .......... .......... .......... .......... .......... 99% 12.7M 0s
798800K .......... .......... .......... .......... .......... 99% 8.36M 0s
798850K .......... .......... .......... .......... .......... 99% 16.3M 0s
798900K .......... .......... .......... .......... .......... 99% 11.8M 0s
798950K .......... .......... .......... .......... .......... 99% 10.4M 0s
799000K .......... .......... .......... .......... .......... 99% 11.2M 0s
799050K .......... .......... .......... .......... .......... 99% 3.96M 0s
799100K .......... .......... .......... .......... .......... 99%  173M 0s
799150K .......... .......... .......... .......... .......... 99% 37.3M 0s
799200K .......... .......... .......... .......... .......... 99% 6.46M 0s
799250K .......... .......... .......... .......... .......... 99% 38.2M 0s
799300K .......... .....                                      100% 2.71M=2m2s

2023-12-22 20:46:22 (6.39 MB/s) - ‘/Users/dvelayutham/miniconda3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37.tar.gz’ saved [818499387]

FINISHED --2023-12-22 20:46:22--
Total wall clock time: 2m 8s
Downloaded: 1 files, 781M in 2m 2s (6.39 MB/s)
Tool       | Status    
-----------------------
wget       | Installed 
rsync      | Installed 
tar        | Installed 
All reference files have been created.
Verifying and benchmarking installation now...
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  IndexError: list index out of range
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Users/dvelayutham/miniconda3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/install.py", line 1029, in install
    benchmark(genome, volume=volume)
  File "/Users/dvelayutham/miniconda3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/install.py", line 719, in benchmark
    matGen.SigProfilerMatrixGeneratorFunc(
  File "/Users/dvelayutham/miniconda3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 1342, in SigProfilerMatrixGeneratorFunc
    file_name = vcf_files[0].split(".")
                ~~~~~~~~~^^^
IndexError: list index out of range

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─SigProfilerMatrixGeneratorR::install(...)
 2.   └─genInstall$install(genome, custom, rsync, bash, ftp)
 3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)

**Comment by mdbarnesUCSD** [comment]
Hi @dineshpeace,

Could you please review the matrices that were generated by SigProfilerMatrixGenerator to make sure they are not all zeros. If they are, please generate the matrices again.

Please let me know if this resolves your issue, thanks!

**Comment by mdbarnesUCSD** [comment]
Please re-open if you still encounter this issue.
