### ISSUE TITLE
Sample filtering before extraction

### ISSUE THREAD

**Issue by thisisliuyu** [AlexandrovLab/SigProfilerExtractor#231]
Hi，

SigProfilerExtractor is really handy. It has helped me a lot. 
However, I have a question about input samples. Do we need to delete hypermutation samples? Will samples with too many mutations affect analysis？Or are there any other filtering criteria?

In general, SBS2 and SBS13 are highly prevalent in cancers. However, I'm using SigProfilerExtractor to analyze my variants in colorectal cancer, and SBS2 and SBS13 did not appear. Is there any problem with the samples?

There are the activities of COSMIC_SBS96_Decomposed_Solution：
[COSMIC_SBS96_Activities.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/13970641/COSMIC_SBS96_Activities.txt)

**Comment by marcos-diazg** [comment]
Dear @thisisliuyu,

We are glad you find SigProfilerExtractor helpful!

The question about hypermutated samples is an interesting one. SigProfilerExtractor has been designed to avoid being affected by hypermutators, thanks to the normalization step (more details in our [manuscript](https://doi.org/10.1016/j.xgen.2022.100179), where the normalization step is part of the Module 2 of SigProfilerExtractor). However, if you have enough number of samples and mutations, it is a good practice to perform separate signature analyses in hypermutators and non-hypermutators to further characterize the spectrum of mutational signatures in the non-hypermutators.

If you are interested in APOBEC-related mutations, I suggest checking for clustered mutations by using our [SigProfilerClusters](https://github.com/AlexandrovLab/SigProfilerClusters) tool, as a separate analysis of clustered and non-clustered mutations can also be informative, as evidenced by [prior studies](https://doi.org/10.1038/s41586-022-04398-6). Also, in colorectal cancer SBS2 and SBS13 are not as prevalent as in other cancer types, and they might be present at low levels, making them undetectable in WES data with low numbers of mutations (as the TCGA data that you shared). FYI, a prior analysis of the TCGA cohort with SigProfilerExtractor has been done [here](https://doi.org/10.1016/j.xgen.2022.100179) (supplementary data found [here](https://figshare.com/articles/dataset/Supplementary_data_for_Islam_et_al_2022/20293890); based in _de novo_ signatures) and also previously [here](https://doi.org/10.1038/s41586-020-1943-3) (supplementary data found [here](https://www.synapse.org/#!Synapse:syn11804040); based in COSMIC v3 decomposed signatures).

I will go ahead and close this ticket, as we keep our GitHub issues mainly focused on specific technical problems of the tools. However, please feel free to follow up by email (mdiazgay@health.ucsd.edu) if you have further comments or concerns about your mutational signature analysis.

Thanks again for your interest! Best,

Marcos
