### ISSUE TITLE
New issue with Indels

### ISSUE THREAD

**Issue by gafishbein** [AlexandrovLab/SigProfilerExtractor#236]
Thank you so much for creating sigProfiler. In the last month I reinstalled sigProfiler (I don't recall when I initially installed it, sorry) and I suddenly get errors when extracting indels (SBS and DBS are unaffected). I have reproduced this on 3 computers. VCF files I successfully used in the past now give this traceback message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SigProfilerExtractor\sigpro.py", line 862, in sigProfilerExtractor
    decomp.spa_analyze(allgenomes, output, signatures=processAvg, genome_build=genome_build, cosmic_version=cosmic_version, exome=exome, verbose=False,
  File "SigProfilerAssignment\decomposition.py", line 306, in spa_analyze
    genomes = sigPlot.process_input(genomes, m)
  File "sigProfilerPlotting\sigProfilerPlotting.py", line 213, in process_input
    return order_input_context(plot_type, data)
  File "sigProfilerPlotting\sigProfilerPlotting.py", line 207, in order_input_context
    reindexed_data = input_data.reindex(ref_format)
  File "pandas\util\_decorators.py", line 324, in wrapper
    return func(*args, **kwargs)
  File "pandas\core\frame.py", line 4807, in reindex
    return super().reindex(**kwargs)
  File "pandas\core\generic.py", line 4966, in reindex
    return self._reindex_axes(
  File "pandas\core\frame.py", line 4626, in _reindex_axes
    frame = frame._reindex_index(
  File "pandas\core\frame.py", line 4645, in _reindex_index
    return self._reindex_with_indexers(
  File "pandas\core\generic.py", line 5032, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "pandas\core\internals\managers.py", line 676, in reindex_indexer
    self.axes[axis]._validate_can_reindex(indexer)
  File "pandas\core\indexes\base.py", line 4121, in _validate_can_reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels

Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @gafishbein,

Could you please let us know what versions of SigProfiler packages that you have installed in your environment? Also, can you please confirm that running from a new directory with just your vcf files that the error does not persist?

Thanks!

**Comment by gafishbein** [comment]
Thank you so much for getting back to me. I can confirm that running from a
new directory with just my vcf files creates the same error. I am using the
following (unfortunately, I don't recall which versions I was using when it
was functioning).

sigProfilerExtractor: 1.1.23
sigProfilerMatrixGenerator: 1.2.25
sigProfilerPlotting: 1.3.21
sigProfilerAssignment: 0.1.3

Thanks again for your assistance!

**Comment by gafishbein** [comment]
Thanks again for your assistance. I was able to find output from a previous
successful attempt at ID analysis. Here were the versions that worked.
Running the newer versions on the same data fail.

Python Version: 3.9.12
SigProfilerExtractor Version: 1.1.21
SigProfilerPlotting Version: 1.3.10
SigProfilerMatrixGenerator Version: 1.2.13
SigProfilerAssignment Version: 0.0.25

Greg

**Comment by mdbarnesUCSD** [comment]
Thank you for providing this, we are looking into this issue and will update here.

**Comment by mdbarnesUCSD** [comment]
Hi @gafishbein,

I believe the issue was due to sigProfilerPlotting and was present in v.1.3.21. Could you please update to sigProfilerPlotting v1.3.22, which should now resolve this issue. Please reach out if you are still encountering it. Thank you!

**Comment by gafishbein** [comment]
No more issues. Thanks for your assistance!!
