### ISSUE TITLE
sigProfilerExtractor for ID(INDELS)

### ISSUE THREAD

**Issue by shanimalik86** [AlexandrovLab/SigProfilerExtractor#237]
Hi, I am running sigProfilerExtractor for SNVs and Indels. It's running successfully for SNVs but getting error for INdels.

Below is the command I am using : 
sig.sigProfilerExtractor("matrix", "SOMATIC_BloodResults_Pon_IDs_Test", "/pathtotheinput/input.ID96.txt", reference_genome="GRCh37", minimum_signatures=1, maximum_signatures=10, nmf_replicates=100)

I am getting following error after it runs 1st signature:

.local/lib/python3.7/site-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 1040, in plotSBS
    plt.text(0.045, 0.75, sample + ": " + "{:,}".format(int(total_count)) + " subs", fontsize=60, weight='bold', color='black', fontname= "Arial", transform=plt.gcf().transFigure)
ValueError: cannot convert float NaN to integer

Please guide me on how to run indels for matrix input and which matrix file I should use for indels ( I am using ID96.all) and how to overcome this error?

**Comment by mdbarnesUCSD** [comment]
Hi @shanimalik86,

Could you please provide the JOB_METADATA.txt in the output directory?

Thanks!

**Comment by shanimalik86** [comment]
Hi, Thanks for your response.

Below I copied the JOB_METADATA.txt 


THIS FILE CONTAINS THE METADATA ABOUT SYSTEM AND RUNTIME


-------System Info-------
Operating System Name: Linux
Nodename: ai-hpcgpu15
Release: 3.10.0-1160.11.1.el7.x86_64
Version: #1 SMP Mon Nov 30 13:05:31 EST 2020

-------Python and Package Versions------- 
Python Version: 3.7.3
SigProfilerExtractor Version: 1.1.15
SigProfilerPlotting Version: 1.3.2
SigProfilerMatrixGenerator Version: 1.2.13
SigProfilerAssignment Version: 0.0.19
Pandas version: 1.2.4
Numpy version: 1.21.6
Scipy version: 1.7.3
Scikit-learn version: 1.0.2

--------------EXECUTION PARAMETERS--------------
INPUT DATA
        input_type: matrix
        output: SOMATIC_SalivaResults_Pon_IDs
        input_data: /hpcdata/dir/ZEESHAN/2024-03-02-mutationalsignature/SOMATIC_Saliva_Pon/SALIVA_Extractor/SALIVA_PON.ID96.txt
        reference_genome: GRCh37
        context_types: SBS96
        exome: False
NMF REPLICATES
        minimum_signatures: 1
        maximum_signatures: 10
        NMF_replicates: 100
NMF ENGINE
        NMF_init: random
        precision: single
        matrix_normalization: gmm
        resample: True
        seeds: random
        min_NMF_iterations: 10,000
        max_NMF_iterations: 1,000,000
        NMF_test_conv: 10,000
        NMF_tolerance: 1e-15
CLUSTERING
        clustering_distance: cosine
EXECUTION
        cpu: 56; Maximum number of CPU is 56
        gpu: False
Solution Estimation
        stability: 0.8
        min_stability: 0.2
        combined_stability: 1.0
        allow_stability_drop: False
COSMIC MATCH
        opportunity_genome: GRCh37
        cosmic_version: 3.3
        nnls_add_penalty: 0.05
        nnls_remove_penalty: 0.01
        initial_remove_penalty: 0.05
        export_probabilities: True
        collapse_to_SBS96: True

-------Analysis Progress------- 
[2024-03-11 15:37:32] Analysis started: 

##################################

[2024-03-11 15:37:32] Analysis started for SBS96. Matrix size [96 rows x 79 columns]

[2024-03-11 15:37:32] Normalization GMM with cutoff value set at 9600

**Comment by shanimalik86** [comment]
I got SALIVA_PON.ID96.all from Matrix script and changed  the extension to .txt and gave this file to Sigprofile extractor> I followed the same process which I did for SNVs but For ID(INDEL analysis) I get error

**Comment by mdbarnesUCSD** [comment]
If you are still encountering this issue, please first update to sigProfilerPlotting v1.3.22. If the issue persists, please re-open this issue. Thanks!
