### ISSUE TITLE
sigproSS python package

### ISSUE THREAD

**Issue by XuanYuXu** [AlexandrovLab/SigProfilerExtractor#24]
I want to ask if this 'sigproSS'package could only make SBS decompositions?Can it apply to DBS and Indel decompositions?
Please help me ,thanks a lot!

**Comment by beginner984** [comment]
This is my concern too

Thanks for any information

**Comment by mishugeb** [comment]
You can decompose DBS, INDEL, or any other context if you have your own signature database. 

In that case, you need to pass the parameter of "data" argument as a pandas DataFrame. The rows will be the mutation types and columns will be the samples. In the same way, you need to pass the parameter of the "sig_database" argument as DataFrame where rows will mutation type and columns will signatures. 

for example:

>>>import sigproSS as ss
>>>data="Matrix as DataFrame"
>>>sig_database="DataFrame of the COSMIC DBS or Indel signatures" (the row number of data and sign_database dataframe should be the same)
>>>ss.single_sample(data, output, ref="GRCh37", sig_database = sig_database)

**Comment by beginner984** [comment]
Sorry by sig_database, can we use **sigProfiler_DBS_signatures.csv**

In this link as DBS?

https://www.synapse.org/#!Synapse:syn11738317

this file have 78 rows that means our mutational catalogue also should have 78 rows?

And am I right about the INDELs that is here as `sigProfiler_ID_signatures.csv`

Thank you for any clarification

**Comment by mishugeb** [comment]
You are correct in each of the aspects. Good luck with your analysis.
