### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by IanVermes** [AlexandrovLab/SigProfilerExtractor#246]
Would you consider including a [changelog](https://keepachangelog.com/en/1.0.0/) to describe the significant changes between each release (major release, minor and subversion). It would help with deciding the upgrade strategy for our installations of SPE in long running projects.

We are currently pinned to 1.1.21, a changelog would help determine whether we can upgrade or not.

---
Edit: Perhaps you could use your existing release notes to help write a changelog file?

**Comment by mdbarnesUCSD** [comment]
Hi @IanVermes,

Thanks for reaching about this. We have decided that we will introduce a changelog into our repositories to help communicate the changes across versions moving forward.

Regarding your pinned v1.1.21 SigProfilerExtractor version, here are some things worth noting:
v1.1.22: SBS4608 plotting was added for de novo signatures
v1.1.23: COSMIC v3.4 signatures parameters set by default
v1.1.24: Input processing for matrices was added

Importantly too though, [when SigProfilerAssignment was updated to v0.1.0](https://github.com/AlexandrovLab/SigProfilerAssignment/pull/106) COSMIC v3.4 signatures were added. The [v1.1.21 release of SigProfilerExtractor does not require this version](https://github.com/AlexandrovLab/SigProfilerExtractor/blob/82d96925d0c23baf0430a8da545f2a55d862056b/setup.py#L37), so in your installation you may be using an older version of SigProfilerAssignment.
