### ISSUE TITLE
user defined H_initials and W_initials

### ISSUE THREAD

**Issue by MariaCartolano** [AlexandrovLab/SigProfilerExtractor#248]
Hello,

is it possible to provide the program with user-defined H_initials and W_initials?

**Comment by mdbarnesUCSD** [comment]
Hi @MariaCartolano,

We do not support user-defined H_initials and W_initials. The default behavior is to use random initialization, but you can modify the initialization technique using the following options:

'random', 'nndsvd', 'nndsvda', 'nndsvdar', or 'nndsvd_min'

**Comment by mdbarnesUCSD** [comment]
Please reach out if you have any additional questions.
