### ISSUE TITLE
Should the copy number segments be filtered before COPY NUMBER MATRIX GENERATION?

### ISSUE THREAD

**Issue by YingYa** [AlexandrovLab/SigProfilerExtractor#249]
Hi,

I would like to run de novo extraction for copy number from a cancer cohort that contains both male and female. Should the copy number segments of chrX and chrY be filtered before COPY NUMBER MATRIX GENERATION? I have tried to find the processing details on the paper "Signatures of copy number alterations in human cancer", but got little.

**Comment by mdbarnesUCSD** [comment]
Hi @YingYa,

We will respond to your initial question here:
https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/issues/182

Thanks!
