### ISSUE TITLE
I am right in getting the point?

### ISSUE THREAD

**Issue by beginner984** [AlexandrovLab/SigProfilerExtractor#25]
Hello

Please, you may look at this shot

<img width="1134" alt="Screenshot 2020-04-27 at 19 36 28" src="https://user-images.githubusercontent.com/43682980/80408119-9567e800-88be-11ea-85b3-56b38c0fe51e.png">

I am right that 5 as the optimum number of extracted signatures, is the best solution because of the lowest `Frobenius` ?

Thanks for any help

**Comment by mishugeb** [comment]
It is not based on Frobenius. It is based on the thresh-hold of avg and minimum, where the significant decrease of L2_norm % is True.
