### ISSUE TITLE
 Could not read from remote repository.

### ISSUE THREAD

**Issue by Ryia-Illani** [AlexandrovLab/SigProfilerExtractor#253]
Hi,

I was unable to install the SigProfilerExtractor. Below are the error messages. Please advice.

Cloning into 'SigProfilerExtractor'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mdbarnesUCSD** [comment]
Hi @Ryia-Illani,

It looks like you are having an issue with the command `git clone`. Please make sure you are not trying to connect from behind a firewall.
