### ISSUE TITLE
Use of deprecated pandas 

### ISSUE THREAD

**Issue by simonjuleseric2** [AlexandrovLab/SigProfilerExtractor#255]
The exemple provided here: https://osf.io/t6j7u/wiki/2.%20Quick%20Start%20Example/

makes use of deprecated pandas attribute, namely 'append' which has been removed from the newer library updates, will there be an update of this repo as well?

**Comment by mdbarnesUCSD** [comment]
Hi @simonjuleseric2,

Please use a version of pandas <2.0.0 until we update to use pandas >=2.0.0.

#206 also covers this.

Thanks!
