### ISSUE TITLE
cannot reindex on an axis with duplicate labels

### ISSUE THREAD

**Issue by jasmin774** [AlexandrovLab/SigProfilerExtractor#256]
Hi,

I am using SigProfilerExtractor version 1.1.23 and attempting to perform an analysis with the mm10 reference genome. While the SBS analysis seems to have worked, I encountered the following error when trying to analyze INDELs:

ValueError                                Traceback (most recent call last)
Cell In[1], line 2
      1 from SigProfilerExtractor import sigpro as sig
----> 2 sig.sigProfilerExtractor("vcf", "extractor_results", "octopus/input",
      3                          reference_genome="mm10", minimum_signatures=1, 
      4                          maximum_signatures=10)

File ~/mambaforge/lib/python3.10/site-packages/SigProfilerExtractor/sigpro.py:862, in sigProfilerExtractor(input_type, output, input_data, reference_genome, opportunity_genome, cosmic_version, context_type, exome, minimum_signatures, maximum_signatures, nmf_replicates, resample, batch_size, cpu, gpu, nmf_init, precision, matrix_normalization, seeds, min_nmf_iterations, max_nmf_iterations, nmf_test_conv, nmf_tolerance, nnls_add_penalty, nnls_remove_penalty, initial_remove_penalty, collapse_to_SBS96, clustering_distance, export_probabilities, make_decomposition_plots, stability, min_stability, combined_stability, allow_stability_drop, get_all_signature_matrices)
    859         sysdata.close()
    860         genome_build = "GRCh37"
--> 862     decomp.spa_analyze(allgenomes, output, signatures=processAvg, genome_build=genome_build, cosmic_version=cosmic_version, exome=exome, verbose=False,
    863                        decompose_fit_option= True, denovo_refit_option=True, cosmic_fit_option=False, export_probabilities=export_probabilities, devopts=devopts, make_metadata=False)
    866 sysdata = open(out_put+"/JOB_METADATA.txt", "a")
    867 end_time = datetime.datetime.now()

File ~/mambaforge/lib/python3.10/site-packages/SigProfilerAssignment/decomposition.py:306, in spa_analyze(samples, output, input_type, context_type, signatures, signature_database, decompose_fit_option, denovo_refit_option, cosmic_fit_option, nnls_add_penalty, nnls_remove_penalty, initial_remove_penalty, de_novo_fit_penalty, genome_build, cosmic_version, make_plots, collapse_to_SBS96, connected_sigs, verbose, devopts, new_signature_thresh_hold, exclude_signature_subgroups, exome, export_probabilities, export_probabilities_per_mutation, sample_reconstruction_plots, make_metadata)
    303 m = mutation_type
    305 # Re-indexing the input matrix file by using process_input function from SigProfilePlotting
--> 306 genomes = sigPlot.process_input(genomes, m)
    308 m_for_subgroups = ""
    309 if m == "96" or m == "288" or m == "1536":

File ~/mambaforge/lib/python3.10/site-packages/sigProfilerPlotting/sigProfilerPlotting.py:213, in process_input(matrix_path, plot_type)
    210         reindexed_data = input_data
    211     return reindexed_data
--> 213 return order_input_context(plot_type, data)

File ~/mambaforge/lib/python3.10/site-packages/sigProfilerPlotting/sigProfilerPlotting.py:207, in process_input.<locals>.order_input_context(plot_type, input_data)
    205     else:
    206         ref_format = get_context_reference(plot_type)
--> 207         reindexed_data = input_data.reindex(ref_format)
    208 else:
    209     # If a non-standard context is used, no sort is applied
    210     reindexed_data = input_data

File ~/mambaforge/lib/python3.10/site-packages/pandas/util/_decorators.py:347, in rewrite_axis_style_signature.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    345 @wraps(func)
    346 def wrapper(*args, **kwargs) -> Callable[..., Any]:
--> 347     return func(*args, **kwargs)

File ~/mambaforge/lib/python3.10/site-packages/pandas/core/frame.py:5202, in DataFrame.reindex(self, *args, **kwargs)
   5200 kwargs.pop("axis", None)
   5201 kwargs.pop("labels", None)
-> 5202 return super().reindex(**kwargs)

File ~/mambaforge/lib/python3.10/site-packages/pandas/core/generic.py:5289, in NDFrame.reindex(self, *args, **kwargs)
   5286     return self._reindex_multi(axes, copy, fill_value)
   5288 # perform the reindex on the axes
-> 5289 return self._reindex_axes(
   5290     axes, level, limit, tolerance, method, fill_value, copy
   5291 ).__finalize__(self, method="reindex")

File ~/mambaforge/lib/python3.10/site-packages/pandas/core/frame.py:5001, in DataFrame._reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   4999 index = axes["index"]
   5000 if index is not None:
-> 5001     frame = frame._reindex_index(
   5002         index, method, copy, level, fill_value, limit, tolerance
   5003     )
   5005 return frame

File ~/mambaforge/lib/python3.10/site-packages/pandas/core/frame.py:5020, in DataFrame._reindex_index(self, new_index, method, copy, level, fill_value, limit, tolerance)
   5007 def _reindex_index(
   5008     self,
   5009     new_index,
   (...)
   5015     tolerance=None,
   5016 ):
   5017     new_index, indexer = self.index.reindex(
   5018         new_index, method=method, level=level, limit=limit, tolerance=tolerance
   5019     )
-> 5020     return self._reindex_with_indexers(
   5021         {0: [new_index, indexer]},
   5022         copy=copy,
   5023         fill_value=fill_value,
   5024         allow_dups=False,
   5025     )

File ~/mambaforge/lib/python3.10/site-packages/pandas/core/generic.py:5355, in NDFrame._reindex_with_indexers(self, reindexers, fill_value, copy, allow_dups)
   5352     indexer = ensure_platform_int(indexer)
   5354 # TODO: speed up on homogeneous DataFrame objects (see _reindex_multi)
-> 5355 new_data = new_data.reindex_indexer(
   5356     index,
   5357     indexer,
   5358     axis=baxis,
   5359     fill_value=fill_value,
   5360     allow_dups=allow_dups,
   5361     copy=copy,
   5362 )
   5363 # If we've made a copy once, no need to make another one
   5364 copy = False

File ~/mambaforge/lib/python3.10/site-packages/pandas/core/internals/managers.py:739, in BaseBlockManager.reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy, only_slice, use_na_proxy)
    737 # some axes don't allow reindexing with dups
    738 if not allow_dups:
--> 739     self.axes[axis]._validate_can_reindex(indexer)
    741 if axis >= self.ndim:
    742     raise IndexError("Requested axis not found in manager")

File ~/mambaforge/lib/python3.10/site-packages/pandas/core/indexes/base.py:4359, in Index._validate_can_reindex(self, indexer)
   4357 # trying to reindex on an axis with duplicates
   4358 if not self._index_as_unique and len(indexer):
-> 4359     raise ValueError("cannot reindex on an axis with duplicate labels")

ValueError: cannot reindex on an axis with duplicate labels

Could you please advise on how to resolve this issue?

Thanks

**Comment by mdbarnesUCSD** [comment]
Hi @jasmin774,

Could you please share what versions of SigProfilerPlotting, SigProfilerAssignment, and SigProfilerExtractor that you have installed? If they are not current, could you please update and then try running again?

Thanks!

**Comment by jasmin774** [comment]
Hi,

Thanks for your reply.

python3.10
SigProfilerMatrixGenerator, Version: 1.2.25
sigProfilerPlotting, Version: 1.3.24
SigProfilerExtractor, Version: 1.1.24
SigProfilerAssignment, Version: 0.1.4

I also tried under the following condition, got the same error.
python3.9
SigProfilerMatrixGenerator, Version: 1.2.25
sigProfilerPlotting, Version: 1.3.21
SigProfilerExtractor, Version: 1.1.23
SigProfilerAssignment, Version: 0.1.4

Thanks

**Comment by mdbarnesUCSD** [comment]
Thanks for checking that. There is a [known issue with the v1.3.21 release of SigProfilerPlotting for re-indexing](https://github.com/AlexandrovLab/SigProfilerExtractor/issues/236) that has since been resolved in subsequent releases. However, you have run with v1.3.24 so it is likely something else.

You are starting with a VCF input type, so SigProfilerMatrixGenerator is is generating your input matrices during runtime. Could you please check your input directory and confirm that matrices were generated and are non-zero?

**Comment by jasmin774** [comment]
I might have been using an older version of sigProfilerPlotting. I tried again with the latest version, and it worked fine. Sorry for the trouble, and thank you very much.

**Comment by mdbarnesUCSD** [comment]
Thanks for letting us know!
