### ISSUE TITLE
alexandrov ftp site is currently available?

### ISSUE THREAD

**Issue by a00101** [AlexandrovLab/SigProfilerExtractor#257]
Dear Developer

I cannot download any reference genome and example data.
something like below.
wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerExtractor/Example_data/21BRCA.zip

Regards

Su-Min.

**Comment by mdbarnesUCSD** [comment]
Hi @a00101,

The ftp server status is a badge on SigProfilerMatrixGenerator's README, and it looks like it has had no issues in the past day. Is it possible that you are downloading from behind a firewall?

**Comment by mdbarnesUCSD** [comment]
Please re-open if you are still encountering this issue.

Also, this thread may be helpful for you too:
https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/issues/176
