### ISSUE TITLE
Problem in getting the main point

### ISSUE THREAD

**Issue by MaryGoAround** [AlexandrovLab/SigProfilerExtractor#26]
Hello

After running your tool, in `Suggested_Solution` subfolder of `SBS96` folder I see `De_Novo_Solution` and `Decomposed_Solution` folders

`De_Novo_Solution` says signatures `A`, `B`, `C`, `D` and `E` have been extracted from my data

`Decomposed_Solution` says this results in the photo

<img width="724" alt="Screenshot 2020-04-28 at 06 16 54" src="https://user-images.githubusercontent.com/60115705/80449811-ff60ab80-8917-11ea-8c79-3b48c25cfc3a.png">

Does this mean only `signature C` has been enriched on `COSMIC` signatures (COSMIC 1, 3 and 5) and your software has not found any enrichment for signatures `B`, `D` and `E` in reference signatures?

How I could know what these unannotated signatures are?

Please help me in understanding this

**Comment by mishugeb** [comment]
You are right. The signature A and C were mapped with the COSMIC signatures but B, D, and E couldn't be mapped. So those are potentially new De Novo Signatures. You will get information on the De Novo Signatures in De_novo_solution folder.

**Comment by MaryGoAround** [comment]
Sorry I denovo folder I only see some statistics
How one could know what is the etiology or meaning of denovo identified signatures

**Comment by mishugeb** [comment]
We don't have etiologies for the de_novo signatures. You are the person who will find out the etiologies and publish papers :-)
