### ISSUE TITLE
How to Access COSMIC Signature Decomposition in Individual Solutions 

### ISSUE THREAD

**Issue by hilmklnc** [AlexandrovLab/SigProfilerExtractor#260]
Hi,

First of all, thank you for developing and maintaining this valuable tool!

I have two questions regarding the use of SigProfilerExtractor:

**1. How can I identify which COSMIC signatures are decomposed into individual signatures in the result files?**
After running SigProfilerExtractor, I can see the individual signature outputs in the 'All_Solutions' directory (e.g., _All_Solutions/SBS96_11_Signatures/ containing SBS96A, SBS96B,..., SBS96K_). However, I am unable to determine which COSMIC signatures these individual signatures have been decomposed from. I can only see their COSMIC signatures in the suggested solution, not individual solutions. Is there a way to access this information within the existing output files? If not, how can I use SigProfilerAssignment or another approach to map these individual signatures to COSMIC signatures?

**2. Clarification on the '_All_solutions_stat.csv_' file:**
In this file, the suggested solution is marked with a star (*) and, for example, it shows 12 signatures. However, I noticed there is also a p-value marked as "Most Stab Sigs" for the next solution (13 signatures). Could you explain the significance of this p-value and what it means in the context of the stability of the suggested solution?

Any help or guidance on these issues would be greatly appreciated!

Best regards,
Hilmi

**Comment by mdbarnesUCSD** [comment]
Hi @hilmklnc,

> 1. How can I identify which COSMIC signatures are decomposed into individual signatures in the result files?

The signatures that are labeled SBS96A, SBS96B, ..., etc. are the de novo signatures. The results from decomposing the de novo signatures into COSMIC signatures can be found in the suggested solution directory (within subdirectory is `COSMIC_SBS96_Decomposed_Solution`). You can use SigProfilerAssignment's decompose_fit function to decompose your de novo signatures into COSMIC signatures.

> 2. Clarification on the 'All_solutions_stat.csv' file

The selection of the signatures is determined using only the average and minimum stabilities. @rvangara or @marcos-diazg could you please share some insight into the p-value? Thanks!

**Comment by hilmklnc** [comment]
Hi, 

Thank you for your response. I know that the de novo signatures and that their decomposition into COSMIC signatures can be found in the solution directory within the suggested solution. 

However, I am still a bit unclear on how I can directly map each of these de novo signatures (e.g., SBS96A, SBS96B, ...)  in the specific signature solution file to their corresponding COSMIC signatures. 
For example,   I want to specifically obtain COSMIC signatures of  SBS_signature_11 result coming from the all solution. For decompose_fit function which input file should I use to decompose de novo signatures of a certain solution file. 

Thank you,
Hilmi

**Comment by mdbarnesUCSD** [comment]
You will want to use the de novo signatures file from the _All_Solutions_ directory for input to `decompose_fit` as well as your samples matrix. The de novo signatures file that you use will depend on the rank of the solution that you chose from the _All_Solutions_ directory. 

After you run `decompose_fit` in the results directory there will be a file _Decompose_Solution/De_Novo_map_to_COSMIC_SBS96.csv_ that details for each of the de novo signatures (ie SBS96A) the COSMIC signatures that it is composed of.

**Comment by hilmklnc** [comment]
Hi, 

Thank you for the explanation! Using the decompose_fit function as you described worked perfectly, and I now have a clear mapping of each de novo signature to its corresponding COSMIC signatures. 

I have one last question regarding my second issue on the _All_solutions_stat.csv_ file from SPE output. Specifically:

Could you clarify the meaning of the star (*) next to the suggested solution?
Also, what does "Most Stab Sigs" signify for the subsequent solutions in the P-value column, and how does it relate to their overall stability and selection of solutions? 

Example stats: 

| Signatures | Stability (Avg Silhouette) | Minimum Stability | Considerable Solution | P-value       |
|------------|----------------------------|-------------------|-----------------------|---------------|
| 10         | 0.97                       | 0.9              | NO                    | N/A           |
| 11         | 0.96                       | 0.87             | YES                   | 1.98E-02      |
| 12*        | 0.91                       | 0.51             | YES                   | 2.91E-01      |
| 13         | 0.9                        | 0.63             | YES                   | Most Stab Sigs|
| 14         | 0.82                       | 0.02             | NO                    | N/A           |

**Comment by mdbarnesUCSD** [comment]
@rvangara could you please explain the significance of the `*` in the _All_soltuions_stat.csv_ file?

**Comment by mdbarnesUCSD** [comment]
The `p-value` is derived from a statistical test that compares the most stable solution to prior values. In the example that you shared, the solution for 12 was selected because it was not considered significantly different than the solution at rank 13.
