### ISSUE TITLE
 input is not an integer.

### ISSUE THREAD

**Issue by shenhaizhongdechanrao** [AlexandrovLab/SigProfilerExtractor#264]
Hi
I am trying to exact signature from duplex data. To average the depth I use (mutation counts)/depth as SBS96 count which mean input is not an integer. I want to know if non-integers can be used as input and if there is any rounding of the number of mutation s in the program. 
thanks

**Comment by mdbarnesUCSD** [comment]
Hi @shenhaizhongdechanrao,

Non-integer values can be used are valid inputs and are not rounded prior to NMF. @rvangara please correct me if my understanding is incorrect.

Thanks!
