### ISSUE TITLE
[Bug] SigProfilerExtractor : ProfileGenerator works but then stop at the extractor step

### ISSUE THREAD

**Issue by Ephedria** [AlexandrovLab/SigProfilerExtractor#27]
Hello,

I'm a new user of the library.
I tried to extract the Signature using the extractor module, and It worked pretty well on my computer.
But when I used it on a cluster I have a bug.

The extraction step is working well :

> **************** Reported Current Memory Use: 0.16 GB *****************
> 
> Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 5.09 seconds.
> Starting matrix generation for INDELs...Completed! Elapsed time: 4.46 seconds.
> Matrices generated for 1 samples with 1618 errors. Total of 28370 SNVs, 541 DINUCs, and 2012 INDELs were successfully analyzed.**

but then, it stop, it won't go on the extracting step.

here is the command used : 
sig.sigProfilerExtractor("vcf", dossier_output, dossier_input,"GRCh38",1,2)

Do you see where I went wrong ?

Best,

Mario

**Comment by mishugeb** [comment]
Could you please use the matrix formats (not the vcf) to see if it works on the matrix format of your data? You need to use the matrices generated from SigProfilerMatrixGenerator in this case. 

Thanks

**Comment by Ephedria** [comment]
Thanks for your quick answer,

I tried locally to use the extractor using the matrix but it doesn't seem to work, maybe I made a flaw somewhere : 

> from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
> from SigProfilerExtractor import sigpro as sig
> 
> dossier_input = "/home/mneou/Documents/Projets/Mutational_Signatures/VCFs"
> dossier_output = "/home/mneou/Documents/Projets/Mutational_Signatures/Res"
> 
> 
> matrix_input = matGen.SigProfilerMatrixGeneratorFunc("test", "GRCh38", dossier_input, plot=True, exome=True, bed_file=None, chrom_based=None, tsb_stat=False, seqInfo=False, cushion=1000)
> sig.sigProfilerExtractor("matrix", dossier_output, matrix_input,"GRCh38",1,2)
>  ************** Reported Current Memory Use: 0.29 GB *****************

It stop there, and create the JOB_METADATA.txt in the output repertory ...

Best,

**Comment by SegoleneDiry** [comment]
Hello,

I'm a new user too and I have the same kind of troubles. When I tried to run the extractor with matrix example data on my computer, no output was created except JOB_MEDATA.txt. In my case, it's associated with an error (see below).

Best regards,

```
from SigProfilerExtractor import sigpro as sig

path_to_example_table = sig.importdata("matrix")
data = path_to_example_table

sig.sigProfilerExtractor("matrix", "poc_lines/variantsignature/example_output_test", data, opportunity_genome="GRCh38", minimum_signatures=1, maximum_signatures=3, nmf_replicates=8, cpu=1)
************** Reported Current Memory Use: 0.18 GB *****************

Extracting signature 1 for mutation type 96
The matrix normalizig cutoff is set for 100X

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 115, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.5/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/signature_extractor.py", line 6, in <module>
    sig.sigProfilerExtractor("matrix", "poc_lines/variantsignature/example_output_test", data, opportunity_genome="GRCh38", minimum_signatures=1, maximum_signatures=3, nmf_replicates=8, cpu=1)
  File "/usr/local/lib/python3.5/dist-packages/SigProfilerExtractor/sigpro.py", line 724, in sigProfilerExtractor
    i = i)
  File "/usr/local/lib/python3.5/dist-packages/SigProfilerExtractor/subroutines.py", line 805, in decipher_signatures
    results = parallel_runs(excecution_parameters, genomes=genomes, totalProcesses=totalProcesses, verbose = False)
  File "/usr/local/lib/python3.5/dist-packages/SigProfilerExtractor/subroutines.py", line 703, in parallel_runs
    pool = multiprocessing.Pool(processes=n_cpu)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 118, in Pool
    context=self.get_context())
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 274, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 33, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 43, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

**Comment by Dagsbio** [comment]
Same here

**Comment by mishugeb** [comment]
@SegoleneDiry  and @Dagsbio, 
Please use the SigProfilerExtractor function under  **if __name__="__main__": idiom**.
Please see the following example:

_from SigProfilerExtractor import sigpro as sig
import sys
import pandas as pd



def run():
    data = "All-Tissues"
    
    project = sig.importdata("matrix")
    output = sys.argv[1]
    #output="results"
    
    mtype = "SBS280"
    norm="100X"
    seeds="random"
    dist="cosine"
    sig.sigProfilerExtractor("matrix", output, project, seeds=seeds, matrix_normalization=norm,resample = True, context_type=mtype, minimum_signatures=1,maximum_signatures=3,nmf_test_conv=1000, nmf_replicates=5, clustering_distance=dist,min_nmf_iterations=3000, get_all_signature_matrices=True,cpu=8)

if __name__ == '__main__':
    run()_

**Comment by mishugeb** [comment]
@Ephedria 
You need to use the matrix generated from SigProfilerMatrixGenetor if you use the "matrix" type input. I assume you are using VCF files.

**Comment by SegoleneDiry** [comment]
Thanks for your answer. I'm sorry to re-open this issue but I have another question. I just tried your script sigpro.py in the zip folder. The only thing I change is cpu=3 (instead of 8).

Some output files were created (but not all?): 

example_issue/
├── JOB_METADATA.txt
├── SBS96
│   ├── All_solutions
│   │   ├── SBS96_1_Signatures
│   │   │   ├── SBS96_S1_Activities_SEM_Error.txt
│   │   │   ├── SBS96_S1_Activities.txt
│   │   │   ├── SBS96_S1_Hall.txt
│   │   │   ├── SBS96_S1_NMF_Convergence_Information.txt
│   │   │   ├── SBS96_S1_Samples_stats.txt
│   │   │   ├── SBS96_S1_Signatures_SEM_Error.txt
│   │   │   ├── SBS96_S1_Signatures_stats.txt
│   │   │   ├── SBS96_S1_Signatures.txt
│   │   │   ├── SBS96_S1_Wall.txt
│   │   │   └── Signature_plotSBS_96_plots_S1.pdf
│   │   ├── SBS96_2_Signatures
│   │   │   ├── SBS96_S2_Activities_SEM_Error.txt
│   │   │   ├── SBS96_S2_Activities.txt
│   │   │   ├── SBS96_S2_Hall.txt
│   │   │   ├── SBS96_S2_NMF_Convergence_Information.txt
│   │   │   ├── SBS96_S2_Samples_stats.txt
│   │   │   ├── SBS96_S2_Signatures_SEM_Error.txt
│   │   │   ├── SBS96_S2_Signatures_stats.txt
│   │   │   ├── SBS96_S2_Signatures.txt
│   │   │   ├── SBS96_S2_Wall.txt
│   │   │   └── Signature_plotSBS_96_plots_S2.pdf
│   │   └── SBS96_3_Signatures
│   │       ├── SBS96_S3_Activities_SEM_Error.txt
│   │       ├── SBS96_S3_Activities.txt
│   │       ├── SBS96_S3_Hall.txt
│   │       ├── SBS96_S3_NMF_Convergence_Information.txt
│   │       ├── SBS96_S3_Samples_stats.txt
│   │       ├── SBS96_S3_Signatures_SEM_Error.txt
│   │       ├── SBS96_S3_Signatures_stats.txt
│   │       ├── SBS96_S3_Signatures.txt
│   │       ├── SBS96_S3_Wall.txt
│   │       └── Signature_plotSBS_96_plots_S3.pdf
│   └── All_solutions_stat.csv
└── Seeds.txt

But there is also an error :

````
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "signature_extractor.py", line 37, in <module>
    run()
  File "signature_extractor.py", line 33, in run
    sig.sigProfilerExtractor("matrix", output, project, seeds=seeds, matrix_normalization=norm,resample = True, context_type=mtype, minimum_signatures=1,maximum_signatures=3,nmf_test_conv=1000, nmf_replicates=5, clustering_distance=dist,min_nmf_iterations=3000, get_all_signature_matrices=True,cpu=3)
  File "/usr/local/lib/python3.5/dist-packages/SigProfilerExtractor/sigpro.py", line 816, in sigProfilerExtractor
    solution, all_stats = sub.stabVsRError(layer_directory+"/All_solutions_stat.csv", layer_directory, title, all_similirities_list, mutation_type)
  File "/usr/local/lib/python3.5/dist-packages/SigProfilerExtractor/subroutines.py", line 2061, in stabVsRError
    mean_l1.append(round(all_similarities["L1_Norm_%"].mean(),2))
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'L1_Norm_%'
````
 
Thank you for your help,

**Comment by mishugeb** [comment]
@SegoleneDiry, could you please send me the JOB_METADATA.txt file?

**Comment by SegoleneDiry** [comment]
[JOB_METADATA.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/4655589/JOB_METADATA.txt)

Here is the file.

**Comment by mishugeb** [comment]
[results.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/4659989/results.zip)
@SegoleneDiry, unfortunately, I could not reproduce the issue. Maybe this is a problem with your python version? Could you please try with a version greater than 3.7? I have attached the results I got.

**Comment by SegoleneDiry** [comment]
Indeed, I tried with Python version 3.7.4 and it works!
Thanks for your help.

**Comment by mishugeb** [comment]
Perfect!
