### ISSUE TITLE
dendrogram missing

### ISSUE THREAD

**Issue by sjin09** [AlexandrovLab/SigProfilerExtractor#30]
To whom it may concern,

I installed the latest SigProfilerExtractor using pip and I was able to successfully run the python script. I, however, don't find the dendrogram.pdf in the De_Novo_Solution directory and I was wondering what parameters have to be provided to generate the dendrogram.pdf.

Many thanks,
Sangjin

**Comment by mishugeb** [comment]
Hi Sangjin,
We don't create a dendrogram in our latest version. 

Thanks
