### ISSUE TITLE
Missing activity table (samples) when using decompose

### ISSUE THREAD

**Issue by cagaser** [AlexandrovLab/SigProfilerExtractor#33]
Hello developers, 

I used decompose function to align the De Novo signatures to the COSMIC signatures. 
First I extracted the De Novo signatures:

```
from sigproextractor import sigpro as sig
data = "Project-339/01_sigProfilerExtractor/vcfs"
sig.sigProfilerExtractor(input_type="vcf", out_put="output", input_data=data, refgen="GRCh38",genome_build="GRCh38")

```
I only extracted SBS96 and got 1-8 signatures (why 8 signatures?) after running the tool. 
Then I wanted to run the ```decomposition``` function to get the COSMIC signatures. However, I was missing the activity table where the rows are mutation types and samples as columns. It's not in the output folder after de novo extraction.

Instead, I used the matrix generator. 

```
from sigproextractor import sigpro as sig
data = "Project-339/01_sigProfilerExtractor/vcfs"
sig.sigProfilerExtractor(input_type="vcf", out_put="output", input_data=data, refgen="GRCh38",genome_build="GRCh38")
```
Then I used the ```matrixes.SBS96.exome``` as input for the ```decomposition``` function:

```
from sigproextractor import decomposition as decomp

signatures = "output/SBS96/All_solutions/SBS96_8_Signatures/SBS96_S8_Signatures.txt"
activities = "output/SBS96/All_solutions/SBS96_8_Signatures/SBS96_S8_Activities.txt"
samples = "vcfs/output/SBS/matrixes.SBS96.exome"
output = "decomposed"
decomp.decompose(signatures, activities, samples,output=output,mutation_type="96",genome_build='GRCh38')

```

Is this the right way?

**Comment by mishugeb** [comment]
That looks good. You don't need to provide mutation_type="96". That should automatically recognize the mutation context.
