### ISSUE TITLE
COSMIC Decomposed solutions is empty

### ISSUE THREAD

**Issue by Apb58** [AlexandrovLab/SigProfilerExtractor#35]
Hello again,

I am trying to understand if I am getting a result as intended or if there is an issue with the decomposition step. 

After what appears as a successful run of SigProfileExtractor (no errors thrown, and the .err file is empty), I checked the SBS `Suggested_Solutions/COSMIC_SBS96_Decomposed_Solution` repository to see if any of the De Novo signatures matched against the established COSMIC signatures. In the folder, I see the `De_Novo_map_to_COSMIC_SBS96.csv` file, but it is empty except for the table header:

`De novo extracted, Global NMF Signatures, L1 Error %, L2 Error %, KL Divergence, Cosine Similarity, Correlation`

Initially, I thought this must mean that NONE of the De Novo signatures appear to contain any of the COSMIC signatures. However, when I look at the `Solution_Stats/Cosmic_SBS96_Decomposition_Log.txt` file, I have:

```
############################ Signature Decomposition Details ################################

Context Type: 96
Genome Build: GRCh38

######################## Decomposing SBS96A ########################


!!!!!!!!!!!!!!!!!!!!!!!!! LAYER: 0 !!!!!!!!!!!!!!!!!!!!!!!!!
Best Signature Composition ['SBS1', 'SBS5', 'SBS12']
L2 Error % 0.27
Cosine Similarity 0.96


!!!!!!!!!!!!!!!!!!!!!!!!! LAYER: 1 !!!!!!!!!!!!!!!!!!!!!!!!!
Best Signature Composition ['SBS1', 'SBS5', 'SBS12']
L2 Error % 0.27
Cosine Similarity 0.96

#################### Final Composition #################################
['SBS1', 'SBS5', 'SBS12']
L2 Error % 0.27
Cosine Similarity 0.96
```

Which makes me think there is potentially an error in writing out the `De_Novo_map_to_COSMIC_SBS96.csv` file. 

For reference, here is the JOBMETADATA.txt file for the run:
```
THIS FILE CONTAINS THE METADATA ABOUT SYSTEM AND RUNTIME


-------System Info-------
Operating System Name: Linux
Nodename: NODE1
Release: 3.10.0-957.10.1.el7.x86_64
Version: #1 SMP Mon Mar 18 15:06:45 UTC 2019

-------Python and Package Versions-------
Python Version: 3.7.3
Sigproextractor Version: 1.0.13
SigprofilerPlotting Version: 1.1.6
SigprofilerMatrixGenerator Version: 1.1.17
Pandas version: 1.0.4
Numpy version: 1.18.1
Scipy version: 1.4.1
Scikit-learn version: 0.23.1

--------------EXECUTION PARAMETERS--------------
INPUT DATA
	input_type: vcf
	output: PROJECT1
	input_data: VCFS
	reference_genome: GRCh38
	context_types: SBS96,DBS78,ID83
	exome: False
NMF REPLICATES
	minimum_signatures: 1
	maximum_signatures: 10
	NMF_replicates: 100
NMF ENGINE
	NMF_init: nndsvd_min
	precision: single
	matrix_normalization: gmm
	resample: True
	seeds: random
	min_NMF_iterations: 10,000
	max_NMF_iterations: 1,000,000
	NMF_test_conv: 10,000
	NMF_tolerance: 1e-15
CLUSTERING
	clustering_distance: cosine
EXECUTION
	cpu: 48; Maximum number of CPU is 48
	gpu: False
COSMIC MATCH
	opportunity_genome: GRCh38
	nnls_add_penalty: 0.05
	nnls_remove_penalty: 0.01
	initial_remove_penalty: 0.05
	refit_denovo_signatures: True
```

**Comment by mishugeb** [comment]
Hi, 
Could you please install the latest version of SigProfilerExtractor 1.0.13.9 and run the data from the matrix file, (NOT the vcf files) as input_type="matrix". Let me know if have a problem getting the matrix file. That should be in the results folder inside the SBS96 subfolder as the "Samples.txt" file. I want to see the error message during the decomposition step.

**Comment by Apb58** [comment]
Hi!

Okay, I have downloaded the newest version and rerun using the matrix file -- and I *did* receive a message: 
`There may be an issue with the formatting of your matrix file.` but unfortunately no additional information as to the nature of the formatting issue. 

I have attached the `Samples.txt` file from the run for reference.
Any advisement would be helpful!

Thanks,
Adrian

[Samples.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/4897292/Samples.txt)

**Comment by mishugeb** [comment]
Hi Adrian, 
I am sorry that you are having issues. However, I tried to reproduce the issue with both CPU and GPU versions, but could not reproduce that. I am unable to address the issue if I cannot reproduce that. I have attached the test_result I obtained using your dataset. 
[test_results.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/4901885/test_results.zip)

**Comment by Apb58** [comment]
Okay -- I still haven't determined the core issue, but I have learned that using the decomp function post Signature Extraction is a viable work around for me for now. Thank you for your help.
