### ISSUE TITLE
Sigprofiler reference signatures: difference between genome and exome

### ISSUE THREAD

**Issue by cagaser** [AlexandrovLab/SigProfilerExtractor#36]
Hello Developers, 

I have been using SigProfiler to extract signatures from my WES data and decomposing each sample with COSMIC v3 signatures. At same time, I am also using MutationalPattern for fitting. Finally, I'd like to compare the results from these two tools. 

I see both genomes and exomes in the signature reference folder: https://www.synapse.org/#!Synapse:syn12009743. Currently, I am using the exome signature for MutationaPattern, but which reference is actually being used by SigProfiler decomposition?

Kind regards, 
Cedrick

**Comment by mishugeb** [comment]
Hi Cedrick,
Currently, we use only the whole-genome signatures for decomposition.

**Comment by cagaser** [comment]
Thank you for your reply. 
So, is the exome reference signature normalized and to be used for WES data?

**Comment by mishugeb** [comment]
Yes, the exome reference signature should be ready to be used for WES data. You just need to set the parameter exome=True

**Comment by lalexandrov1018** [comment]
Please reopen the ticket if there are still any concerns.
