### ISSUE TITLE
ZeroDivisionError with simulated data

### ISSUE THREAD

**Issue by matrs** [AlexandrovLab/SigProfilerExtractor#37]
Hello, 
I just attended a short workshop given by Steve Rozen Lab and collaborators and we used a simulated dataset. 
We analyzed results from `SigProfilerExtractor`  generated some time ago  but i don't  know which version was used to generate the results. My problem is that when I try to extract profiles using the last version of the library  with the same input I'm getting the following error:

```python
SigProfilerExtractor.__version__
'1.0.13.9'

sig.sigProfilerExtractor(input_type = "table", 
                         output = "sig.pro.output_test", 
                         input_data = "../3.types.ground.truth.spectra.1000.size.csv", 
                         minimum_signatures=  9,  
                         maximum_signatures= 17,
                         cpu = 4)
```

```
lib/python3.8/site-packages/SigProfilerExtractor/sigpro.py in sigProfilerExtractor(input_type, output, input_data, reference_genome, opportunity_genome, context_type, exome, minimum_signatures, maximum_signatures, nmf_replicates, resample, batch_size, cpu, gpu, nmf_init, precision, matrix_normalization, seeds, min_nmf_iterations, max_nmf_iterations, nmf_test_conv, nmf_tolerance, nnls_add_penalty, nnls_remove_penalty, initial_remove_penalty, refit_denovo_signatures, clustering_distance, export_probabilities, make_decomposition_plots, get_all_signature_matrices)
    688         # get the cutoff for normatization to handle the hypermutators
    689 
--> 690         normalization_cutoff = sub.get_normalization_cutoff(genomes, manual_cutoff=100*genomes.shape[0])
    691         #print("Normalization Cutoff is :", normalization_cutoff)
    692         excecution_parameters["normalization_cutoff"]= normalization_cutoff

~/miniconda3/envs/torch/lib/python3.8/site-packages/SigProfilerExtractor/subroutines.py in get_normalization_cutoff(data, manual_cutoff)
    251 
    252 
--> 253     mean = np.mean(col_sums)
    254     std = np.std(col_sums)
    255     cutoff = (mean + 2*(std)).astype(int)

<__array_function__ internals> in mean(*args, **kwargs)

~/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py in mean(a, axis, dtype, out, keepdims)
   3370             return mean(axis=axis, dtype=dtype, out=out, **kwargs)
   3371 
-> 3372     return _methods._mean(a, axis=axis, dtype=dtype,
   3373                           out=out, **kwargs)
   3374 

~/.local/lib/python3.8/site-packages/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims)
    170             ret = ret.dtype.type(ret / rcount)
    171     else:
--> 172         ret = ret / rcount
    173 
    174     return ret

ZeroDivisionError: division by zero
```
I tried with the example data and it worked as expected  (with GPU activated too).

Here it's the input data, It's a csv file, I changed the extension because github doesn't allow that extension. It was created using [SynSigGen](https://github.com/steverozen/SynSigGen) but I don't have the code used to do it.

 [3.types.ground.truth.spectra.1000.size.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/4920952/3.types.ground.truth.spectra.1000.size.txt)

**Comment by mishugeb** [comment]
I will run a test code with the data and get back to you soon.

**Comment by mishugeb** [comment]
I have looked at your dataset. First, that is not a tab delimited file. Rather, that is a csv file. Second, mutation order and description is not compatible to SigProfilerExtractor. I have uploaded a sample matrix file, so that you will understand the input matrix format for SigProfilerExtractor.
[Samples.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/4942556/Samples.txt)

**Comment by matrs** [comment]
I see. Thanks!
