### ISSUE TITLE
Decomposed SBS96 signatures include Signature H

### ISSUE THREAD

**Issue by anishaluthra** [AlexandrovLab/SigProfilerExtractor#38]
I ran SigProfilerExtractor as I wanted the COSMIC signatures for each of my samples. I'm looking at the decomposed signatures, and I'm seeing a couple SBS signatures, but I'm also seeing Signature H. What is signature H and why is it not incorporated into the other SBS signatures? I'm only seeing about 15 COSMIC signatures in Decomposed_Solution_Activities_SBS96.txt. Thanks in advance!

**Comment by mishugeb** [comment]
Hi,
You are seeing Signature H, because that wasn't able to be decomposed into COSMIC signatures. So it was reported as a new signature. All other De Novo Signatures were decomposed into the 15 COSMIC signatures.

**Comment by anishaluthra** [comment]
Okay, got it - is the reason that is wasn't able to be decomposed into COSMIC signatures just because there are other signatures that are not similar to any of the COSMIC signatures?

**Comment by mishugeb** [comment]
Yes, you are correct.

**Comment by anishaluthra** [comment]
Understood, thank you!
