### ISSUE TITLE
Extract all SBS Cosmic signatures

### ISSUE THREAD

**Issue by vale-melo** [AlexandrovLab/SigProfilerExtractor#39]
Hi,

I have an issue regarding the extraction of all SBS Cosmic signatures from TCGA mutect data.
I have correctly installed all python tools of the SigProfiler suite and correctly generate matrix of mutation substitutions using the Matrix Generator.

When I tried to extract all SBS COSMIC signatures using the code below, the tool extracted only 9 SBS in the decomposed solution (I also tried to increase the number of signatures to be extracted with endProcess=100, but unfortunately I obtained again 9 SBS):
from sigproextractor import sigpro as sig
data = "/path_to_folder/output/SBS/LUAD_mutect.SBS96.all.txt"
sig.sigProfilerExtractor("table", "example_output_new", data, "GRCh38", "GRCh38", startProcess=1, endProcess=50, totalIterations = 100)

Is there any step/parameter that I missed to extract all SBS?

Thank you,
Valentina

**Comment by mishugeb** [comment]
Hi Valentina,
You are using an older version of SigProfilerExtractor. Please use the latest version by installing using the "$pip install SigProfilerExtractor" command. You will find the description of the parameters in the Readme file. Also, may I know the dimension of your matrix?

Thanks,
Mishu

**Comment by vale-melo** [comment]
Hi Mishu,

Thank you for your reply.

I installed SigProfilerExtractor by using pip3 install SigProfilerExtractor, now I tried with pip install SigProfilerExtractor (the installed version is now SigProfilerExtractor-1.0.14) and I am testing it.

The matrix is only 132 KB, made of 571 columns and 96 rows.

Best,

Valentina Melocchi, PhD 

UO Cancer Biomarkers

ISBReMIT - Institute for Stem-cell Biology, Regenerative Medicine and Innovative Therapies
Casa Sollievo della Sofferenza Hospital - IRCCS
Viale Padre Pio 7
71013 San Giovanni Rotondo (FG) 
E-mail: v.melocchi@operapadrepio.it
Phone: +39 0882-416571
Mobile: +39 3478702119





---------------------------------------------------
This e-mail is confidential and may also contain privileged information. If you are not the intended recipient you are not authorized to read, print, save, process or disclose this message. If you have received this message by mistake, please inform the sender immediately and delete this e-mail, its attachments and any copies. Any use, distribution, reproduction or disclosure by any person other than the intended recipient is strictly prohibited and the person responsible may incur penalties.

**Comment by lalexandrov1018** [comment]
Please reopen the ticket if there are still any concerns.
