### ISSUE TITLE
decomposed activities not generated (version 1.0.17)

### ISSUE THREAD

**Issue by itsvenu** [AlexandrovLab/SigProfilerExtractor#44]
Hi,

I ran SigProfilerExtractor 1.0.17 on my data. After the process ended, I didn't see any activities table under `COSMIC_ID83_Decomposed_Solution`. I guess it should generate `Activities` and `Signatures` folder as in `ID83_De-Novo_Solution`.

Decomposition folder only has 

- Decomposition_Plots  
- De_Novo_map_to_COSMIC_ID83.csv
- ID83_Decomposition_Plots.pdf
- Solution_Stats

`ID83_De-Novo_Solution` folder has `Activities`, `Signatures` and `Solution_stats` folder. 

I was wondering if there is anything I am missing here?

Thank you.

**Comment by mishugeb** [comment]
Hi Venu,
I am looking at the issue and will back to you soon.

**Comment by itsvenu** [comment]
@mishugeb, here is the error message I got

```
  File "/home/thatikon/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 1022, in sigProfilerExtractor
    final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build, add_penalty=add_penalty, remove_penalty=remove_penalty, mutation_context=mutation_context, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg)
  File "/home/thatikon/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 1410, in signature_decomposition
    shutil.rmtree(directory+"/Decomposition_Plots")
  File "/home/thatikon/anaconda3/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/thatikon/anaconda3/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/thatikon/anaconda3/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs0000000189c1c3c200000342'
```

**Comment by mishugeb** [comment]
Hi Venu,
Please use "make_decomposition_plots=False" until I give you the next update. I was unable to reproduce the issue on my settings.

**Comment by itsvenu** [comment]
Hi Mishu,

Thanks for the tip. With "make_decomposition_plots=False", it is generating activities file.

**Comment by mishugeb** [comment]
Hi Mark @mdbarnesUCSD, could you please reproduce the issue?

**Comment by leefall** [comment]
> @mishugeb, here is the error message I got, jic if this might help tracing the problem
> 
> ```
>   File "/home/thatikon/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 1022, in sigProfilerExtractor
>     final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build, add_penalty=add_penalty, remove_penalty=remove_penalty, mutation_context=mutation_context, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg)
>   File "/home/thatikon/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 1410, in signature_decomposition
>     shutil.rmtree(directory+"/Decomposition_Plots")
>   File "/home/thatikon/anaconda3/lib/python3.7/shutil.py", line 491, in rmtree
>     _rmtree_safe_fd(fd, path, onerror)
>   File "/home/thatikon/anaconda3/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
>     onerror(os.unlink, fullname, sys.exc_info())
>   File "/home/thatikon/anaconda3/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
>     os.unlink(entry.name, dir_fd=topfd)
> OSError: [Errno 16] Device or resource busy: '.nfs0000000189c1c3c200000342'
> ```

I also got the same error as yours. 
In my case, I changed the working directory from nfs storage to the local server's home directory.
The thing is that the error occurred not constantly.

**Comment by mdbarnesUCSD** [comment]
Thanks @itsvenu and @leefall for bringing this up. I am looking into reproducing this error.
