### ISSUE TITLE
Two issues!

### ISSUE THREAD

**Issue by rxy712** [AlexandrovLab/SigProfilerExtractor#45]
Hello,
Thank you for providing such a good tool! I now have two issues and need your help. Any input would be very much appreciated! 

1) The first issue is the error message:
>>> sig.sigProfilerExtractor("vcf", "output_SNV_VCF", "SNV_vcf", reference_genome="mm10", opportunity_genome="mm10", minimum_signatures=1, maximum_signatures=10)

************** Reported Current Memory Use: 0.29 GB *****************

Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 3.76 seconds.
Matrices generated for 16 samples with 0 errors. Total of 30452 SNVs, 0 DINUCs, and 0 INDELs were successfully analyzed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xrao/.local/lib/python3.6/site-packages/SigProfilerExtractor/sigpro.py", line 647, in sigProfilerExtractor
    excecution_parameters["context_type"]=",".join(mtypes) 
UnboundLocalError: local variable 'mtypes' referenced before assignment

------------------------------------
Then I tried this without success:
def sigProfilerExtractor():
    global mtypes

2) The following files are not contained in the output folders:
Cluster_of_Samples.txt
dendogram.pdf

I am using Python Version: 3.6.4 and Sigproextractor Version: 1.0.17

Many thanks in advance!
XR

**Comment by mishugeb** [comment]
I will check that let you know.

**Comment by mishugeb** [comment]
I could not replicate the error so far. So, let us do a test with my code at your side.  Please upgrade the SigProfilerExtractor to its current version (Version: 1.0.18). Then download and unzip the file is attached. After that, please navigate to the "public_test" folder and run "python sigpro.py" there.

Please see what happens with the test. 
[public_test.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/5310457/public_test.zip)

Also, we have some modifications in the results folder structure and you will get the Cluster_of_Samples.txt and
dendogram.pdf files there. Here I attached a sample results folder. 
[results.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/5310497/results.zip)
