### ISSUE TITLE
Can not have some of output from sigProfilerExtractor

### ISSUE THREAD

**Issue by leefall** [AlexandrovLab/SigProfilerExtractor#46]
Dear developer of SigProfilerExtractor

Thanks to the developer, it is really convenient for a mutational signature analysis with SigProfilerExtractor. 

However, I could not get some of the output filers that should be contained in the output directory according to wiki (https://osf.io/t6j7u/wiki/4.%20Output%20-%20Suggested%20Solution/).

Instead of thes files( Cluster_of_Samples.txt, comparison_with_global_ID_signatures.csv, Decomposed_Solution_Activities.txt, Decomposed_Solution_Samples_stats.txt, Decomposed_Solution_Signatures.txt, decomposition_logfile.txt, dendogram.pdf, Mutation_Probabilities.txt, ignature_plot[MutatutionContext]_plots_Decomposed_Solution.pdf) are produced in Decomposed_Soultion, there are files (named De_Novo_map_to_COSMIC_SBS96.csv, SBS96_Decomposition_Plots.pdf) and directories (named Activities, Signature, Solution_Stats).

Here is the script code i used.

from SigProfilerMatrixGenerator import install as genInstall
from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
from SigProfilerExtractor import sigpro as sig

matrices = matGen.SigProfilerMatrixGeneratorFunc("[Output_File_Name]", "GRCh37", "[InputDirectory]", exome=False, bed_file=None, chrom_based=False, plot=True, tsb_stat=False, seqInfo=False)

sig.sigProfilerExtractor("text", "[OutputName]", "[InputDirectory]/output/SBS/[Output_File_Name].SBS96.all", reference_genome="GRCh37")

then I got 

'''
process 14 continues please wait... 
execution time: 14 seconds 

process 14 continues please wait... 
execution time: 13 seconds 

process 14 continues please wait... 
execution time: 24 seconds 

Time taken to collect 100 iterations for 14 signatures is 85.88 seconds
Optimization time is 12.723468780517578 seconds
The reconstruction error is 0.0776, average process stability is 0.38 and 
the minimum process stability is 0.28 for 14 signatures

Decompositon Plot made for SBS96A <----I think 'Deompositon' is typo

Your Job Is Successfully Completed! Thank You For Using SigProfiler Extractor.
 
''''

Can you help me to handle this issue?

Thank you.

**Comment by mishugeb** [comment]
Hi,
Our wiki page is slightly out of date. 
De_Novo_map_to_COSMIC_SBS96.csv is comparison_with_global_ID_signatures.csv
The other file will be found in Signature, Activities, and Solution_stats folders with slightly different names.
We don't produce the sample clusters and dendrogram anymore. 

Thanks

**Comment by leefall** [comment]
Thanks for quick and kind comment 

Thanks
