### ISSUE TITLE
the output is not generated in "estimate_solution" function

### ISSUE THREAD

**Issue by rezwanhosseini** [AlexandrovLab/SigProfilerExtractor#47]
Hi, 
I'm using SigProfilerExtractor and I want to implement the "estimate_solution" function to find the optimum rank. The first parameter of this function named "base_csvfile" has a default string value **"All_solution_stat.csv"**, which is a CSV file that should be generated in the output folder. But when running the **example function** (below) with all the **default values**, I get the **"no such file or directory" error** for this parameter.

Example:
     >>>from SigProfilerExtractor import estimate_best_solution as ebs
     >>>ebs.estimate_solution(base_csvfile="All_solutions_stat.csv", 
                All_solution="All_Solutions", 
                genomes="Samples.txt", 
                output="results", 
                title="Selection_Plot",
                stability=0.8, 
                min_stability=0.2, 
                combined_stability=1.25)

What is wrong with this? does this file need to exist in the directory path? As an input? 
As far as I got, this file is supposed to be generated during the function implementation, isn't it?

**Comment by mishugeb** [comment]
Thanks for reporting the issue. I will check that and let you know the solution. Possibly, there is a bug and l need to fix that.

**Comment by alvinwt** [comment]
I have the same error. Likely due to changes in All_solutions_stat.csv. Format of the file is different from previous versions.

**Comment by mishugeb** [comment]
again sorry for the delay. Could you please upgrade the version and try to run the module. It is working for me.

**Comment by rezwanhosseini** [comment]
I upgraded the package but still get the same error.

**Comment by mishugeb** [comment]
Okay, let me do a test at your end. Please download the file and upzip that. Then inside the folder, just run "$python sig_number_selection.py". Let us see if that runs or gives an error. If that runs successfully, then you will see a "results" folder created. Let us see what happens.
[SelectionofSignatures.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/5308788/SelectionofSignatures.zip)

**Comment by mishugeb** [comment]
To use that function, you first need to finish a complete run with SigprofilerExtractor. Then from the results folder, use the All_Solutions folder, Samples.txt, and All_solutions_stat.csv to select signatures with different selection parameters (if you like) with the estimate_best_solution module.
