### ISSUE TITLE
RESULTS FILES....

### ISSUE THREAD

**Issue by cmorris2945** [AlexandrovLab/SigProfilerExtractor#48]
Hello.

Do you have a results file for me to compare my results
with yours? Because I ran your program, but I would like
to cross reference my results files with yours...

-CHRIS

**Comment by mishugeb** [comment]
Hello Chris,
Here, I have attached a sample results folder.
[results.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/5310502/results.zip)
