### ISSUE TITLE
sigProfilerExtractor TypeError: unsupported operand type(s) for /: 'str' and 'str'

### ISSUE THREAD

**Issue by vyellapa** [AlexandrovLab/SigProfilerExtractor#5]
When running the sigProfilerExtractor, I get a TypeError and no output is produced. I pasting the first 10 lines of the input file. Do you know of anything I can do to fix this error?

Thanks,
Teja

`juno:SBS yellapav$ head /home/yellapav/local/downloads/sigplofiler/cave_fm6_chap_alex.txt
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	2301677	2301677	A	T	SOMATIC
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	3622561	3622561	C	T	SOMATIC
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	4531849	4531849	C	A	SOMATIC
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	4538255	4538255	G	A	SOMATIC
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	4539928	4539928	G	C	SOMATIC
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	4980298	4980298	T	A	SOMATIC
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	5113557	5113557	G	T	SOMATIC
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	5493418	5493418	T	G	SOMATIC
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	6416065	6416065	C	A	SOMATIC
MM	PD26405a	CHAPMAN	GRCh37	SNP	1	6551142	6551142	C	T	SOMATIC`

>>>sig.sigProfilerExtractor("text", "/home/yellapav/local/downloads/sigplofiler/output/SBS/out","/home/yellapav/local/downloads/sigplofiler/cave_fm6_chap_alex.txt", "chap")

************** Reported Current Memory Use: 0.08 GB *****************

Extracting signature 1 for mutation type 501411

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/work/isabl/opt/python/.virtualenvs/users/yellapav/default_python3/lib/python3.6/site-packages/pandas/core/ops.py", line 1497, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "/work/isabl/opt/python/.virtualenvs/users/yellapav/default_python3/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 205, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/work/isabl/opt/python/.virtualenvs/users/yellapav/default_python3/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 65, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for /: 'str' and 'str'

**Comment by lalexandrov1018** [comment]
This issue was resolved via email.
