### ISSUE TITLE
meaning of opportunity genome 

### ISSUE THREAD

**Issue by Sames-Jtudd** [AlexandrovLab/SigProfilerExtractor#50]
Hi there, 

thanks for sharing the software. 

One question; 
for the command "sigProfilerExtractor" its is stated that the opportunity_genome argument "automatically matches the input reference genome value".

I launched the program using the command
sig.sigProfilerExtractor("vcf", output_dir, input_dir,reference_genome="GRCh38",cpu=6)

however I noticed that in the JOB_METADATA file it states that 
"COSMIC MATCH
	opportunity_genome: GRCh37"

Is this an error? Should I rerun with the additional option  'opportunity_genome="GRCh38"'

thanks 

jamie

**Comment by mishugeb** [comment]
You don't need to rerun the extraction. If the refence_genome is "GRCh38, the opportunity_genome will automatically select "GRCh38". The opportunity genome uses the corresponding version of the COSMIC signatures during decomposition.
