### ISSUE TITLE
Some default input parameter values and some patameter names in wiki differs from source.

### ISSUE THREAD

**Issue by monagai** [AlexandrovLab/SigProfilerExtractor#52]
Some default input parameter values and some patameter names in wiki differ from the source.
This is only a report.
It may be also better to add explanation or example for multiprocessing module.
wiki: version: 2020-09-22 22:30:31+00:00 UTC
      https://osf.io/t6j7u/wiki/2.%20Using%20the%20Tool%20-%20Input/
      https://osf.io/t6j7u/wiki/5.%20Quick%20Start%20Example/

**Comment by mdbarnesUCSD** [comment]
Thank you @monagai for bringing this up. I will look into updating this.

Best,
Mark
