### ISSUE TITLE
run estimate_solution without finishing denovo extraction for all ranks

### ISSUE THREAD

**Issue by itsvenu** [AlexandrovLab/SigProfilerExtractor#53]
Hi,

I started de novo extraction on my data for 35 signatures. This is taking a very long time than expected. However, I am sure there will not be 35 signatures in my data (from previous evidences, there might be 10 signatures). So far, the extraction has completed for 17 ranks. Now I would like to estimate the best solution among these 17 ranks.

When I ran the `estimate_solution` function, it is giving the following error 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thatikon/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/estimate_best_solution.py", line 50, in estimate_solution
    signatures[i]=signatures[i].rstrip("*")
AttributeError: 'int' object has no attribute 'rstrip'
>>>
```

There is some information missing from `All_solutions_stat.csv` file (I compared this with another extraction which is completed).

I was wondering if there is a way here for me to estimate the best solution without actually finishing the extraction for all provided ranks?

Thank you.

**Comment by mishugeb** [comment]
Hi Venu,
Currently, we don't have the functionality to run the estimate solution module with a partial (unfinished)"All_solutions_stat.csv". Let me give time to see if I can introduce the functionality. I will let you know once that is done.

**Comment by mishugeb** [comment]
Hi Venu, 
I have implemented the functionality you were asking for. Please try with version 1.0.19.
