### ISSUE TITLE
SigProfilerExtractor with BED-File

### ISSUE THREAD

**Issue by RaphaelHablesreiter** [AlexandrovLab/SigProfilerExtractor#56]
Hi,

how do I use the SigProfilerExtractor with a BED-file for targeted sequencing?
I used SigProfilerMatrixGenerator with a BED-File for generating the matrix, but I am not able to provide the BED file to SigProfilerExtractor.

Many thanks!

Best,
Raphael

**Comment by ntbeileh** [comment]
Hi Raphael,

SigProfilerExtractor only takes VCFs and matrix input, so you cannot provide BED files to SigProfilerExtractor. Instead you should only use the matrix you generated from SigProfilerMatrixGenerator as input for SigProfilerExtractor.

Best,
Noura

**Comment by RaphaelHablesreiter** [comment]
Hi Noura,

thank you.

Best, 
Raphael
