### ISSUE TITLE
cosine similarity cut-off in decomposition function

### ISSUE THREAD

**Issue by itsvenu** [AlexandrovLab/SigProfilerExtractor#59]
Hi Mishu,

Ludmil suggested to use decomposition function with a cosine similarity cut-off 0.9 to determine if a signature is novel and matching with one of the COSMIC signatures. However, I do not seem to find an argument to specify cosine similarity cut-off in [decomposition function](https://github.com/AlexandrovLab/SigProfilerExtractor#-decompose).

If I missed it, could you please point out which argument is the one I am looking for? 

Thank you & stay safe!

**Comment by mishugeb** [comment]
Hi Venu, 
The decomposition function doesn't use cosine similarity. It only uses L2% . The "nnls_add_penalty", "nnls_remove_penalty"  and  "initial_remove_penalty" combinedly defines the cut-off for the decomposition of denovo signatures into COSMIC signatures.
