### ISSUE TITLE
Pentanucleotide context mutational signature reference matrix

### ISSUE THREAD

**Issue by sjin09** [AlexandrovLab/SigProfilerExtractor#60]
Hello,

I am writing to inquire whether it is possible to know where I could potentially find pentanucleotide context mutational signature matrix describing the probabilities of each mutation in pentanucleotide context for all the mutational signatures.

**_Employing the single base substitution classification of 1536 mutation types, which uses the pentanucleotide sequence context two bases 5’ and two bases 3’ to each mutated base, yielded a set of signatures largely consistent with that based on substitutions in trinucleotide context alone. Notably, however, the pentanucleotide context enabled the extraction of two forms of both SBS2 and SBS13, one with mainly a pyrimidine (C or T) and the other with a purine (A or G) at the -2 base (the second base 5’ to the mutated cytosine). These may represent the activities of the cytidine deaminases APOBEC3A and APOBEC3B, respectively44._** described in the paper The Repertoire of Mutational Signatures in Human Cancer

I wasn't able to find the matrix on the website https://www.synapse.org/#!Synapse:syn11726601/files or on the paper https://www.nature.com/articles/s41586-020-1943-3#Sec18

If the matrix is confidential, I was wondering if it could be shared through email at sl17@sanger.ac.uk.

Many thanks for the help!

Regards,
Sangjin

**Comment by mishugeb** [comment]
@lalexandrov1018 could you please answer the question?

**Comment by lalexandrov1018** [comment]
Unfortunately, we do not have a 1536 reference set of COSMIC signatures. While PCAWG performed a number of 1536 analyses, we did not release any of these as official COSMIC signatures due to a number of issues with the results. We are currently in the process of updating the set of reference signatures but we do not anticipate to have a stable version before the summer.
