### ISSUE TITLE
est_genome dimensions appear to be smaller than input file size

### ISSUE THREAD

**Issue by kevwilhelm95** [AlexandrovLab/SigProfilerExtractor#61]
<img width="1336" alt="Screen Shot 2021-01-28 at 10 45 53 PM" src="https://user-images.githubusercontent.com/69325247/106232827-95cd4080-61ba-11eb-9429-c39af0251d10.png">

I am attempting to run the estimate_solution function and receiving this error stating that the index is out of range. The input matrix is 96x560 and seems to be loading correctly. Any help diagnosing this issue would be much appreciated. Thanks!

**Comment by mishugeb** [comment]
Is it possible to send me the data? So that I could try to reproduce the error on my side. 

Thanks
