### ISSUE TITLE
"ValueError: array must not contain infs or NaNs" when run sigprofilerextractor with DBS data

### ISSUE THREAD

**Issue by wjdgy3746** [AlexandrovLab/SigProfilerExtractor#62]
Dear developer,

First of all, thank you for your great program.

It runs without error when I use SBS data, but an error occurs when I use DBS data.

It is as follows.

ValueError: array must not contain infs or NaNs

<img width="878" alt="KakaoTalk_20210202_025023630" src="https://user-images.githubusercontent.com/34389660/106567611-7006b980-6575-11eb-8692-2233dc94a687.png">

It occurs after the last process ends. I guess this error happens during making ./DBS78/Suggested_Solution/COSMIC_DBS78_Decomposed_Solution/De_Novo_map_to_COSMIC_DBS78.csv file and calculating L1 error, L2 error, KL divergence, Cosine Similarity, and correlation.

Could you tell me why this error happens, and how to fix it?

Thank you :)

**Comment by mishugeb** [comment]
Hi,
Is it possible to share your DBS data with me? I need to reproduce the results.

Thanks

**Comment by wjdgy3746** [comment]
Sorry, it is hard to share the DBS data because of privacy issues.
