### ISSUE TITLE
Number of signatures given low cosine distance difference

### ISSUE THREAD

**Issue by andreyurch** [AlexandrovLab/SigProfilerExtractor#66]
Dear developers,

Thank you for the very useful tool!  

I received the following plot using a large number of samples:

[SBS96_selection_plot.pdf](https://github.com/AlexandrovLab/SigProfilerExtractor/files/6048940/SBS96_selection_plot.pdf)

The plot suggests that I should take 3 signatures for my dataset. At the same time, from other methods and evidences, I know that the most likely variant is 2 signatures. The change in cosine distance between 2 and 3 signatures is very small, around 0.01.  Is it eligible to take 2 signatures given this plot?  How can I avoid such problems in the future?

Best regards,
Andrey

**Comment by mishugeb** [comment]
Hi Andrey, 
You can choose two signatures if you wish and know the dataset quite well. SigProfilerExtractor has estimated the optimum number of sigtures based on two metrics: 1)Signature stability (silhoutte coefficient) and 2)reduction of L2 error between the original and the reconstrusted matrix. From the statistics you will find in the "All_solutions_stat.csv" file SigProfilerExtractor found that 3 signatures are enough stable and also obtaining significantly more information than 2 signtures. 

Thanks,
Mishu
