### ISSUE TITLE
hierachy/cluster function based on de novo mutation signature finding

### ISSUE THREAD

**Issue by JLiandbear** [AlexandrovLab/SigProfilerExtractor#70]
Hi there,
I thought the hierarchy/cluster function based on de novo mutation signature finding could be very interesting to many researchers. Is there any plan to put that back in near future?
Thank you

**Comment by mishugeb** [comment]
We output are resources the resource you need to make clusters. For example, you get the activity matrix and cluster the samples based on the activity of the signatures on the samples. You can get many clustering modules in scikit-learng package. Currently, we don't have a plan to integrate an in-built cluster into the package.
