### ISSUE TITLE
Decompose with exome signature/ customized signatures

### ISSUE THREAD

**Issue by marshelma** [AlexandrovLab/SigProfilerExtractor#73]
There is a 'signature_database' option in the decompose function, is this where I should supply exome signature/customized signatures?

**Comment by mishugeb** [comment]
Yes, you are correct.

**Comment by RaphaelHablesreiter** [comment]
Hi,
I want to decompose with version 2, but when I add the "COSMIC_v1_SBS_GRCh37.txt"-file to signature_database it does not change.
How does that work?
Many thanks.
