### ISSUE TITLE
CNV Signature definitions

### ISSUE THREAD

**Issue by dtm2117** [AlexandrovLab/SigProfilerExtractor#74]
Hello,

After performing the signature extraction on a CNV48 matrix, I have now generated the decomposed signatures. Are there definitions for the CNV1-CNV19 signatures? Where were these signatures derived from? 

Thanks for all the hard work and a great tool!

**Comment by mishugeb** [comment]
Hello, 
We don't have definitions for the CNV signatures publicly available till now. 
@lalexandrov1018, do have any idea when we can make CNV signatures publicly available?

Thanks,
Mishu

**Comment by lalexandrov1018** [comment]
The reference set of CN signatures are currently under development. The provided set of 19 CN signatures in SigProfilerExtractor is preliminary and should not be used until the reference set of CN signatures is officially published.
