### ISSUE TITLE
KeyError: 'none'

### ISSUE THREAD

**Issue by WZo0o** [AlexandrovLab/SigProfilerExtractor#76]
Hi,
When I perform the signature extraction on a matrix, the process was interrupted by "KeyError: 'none'". 
See below for detailed error reporting information and the matrix file is attached.
Can you help me to handle this issue?
Thanks for all the hard work and a great tool!

[COAD.SBS18.all.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/6445031/COAD.SBS18.all.txt)

###
Time taken to collect 500 iterations for 25 signatures is 1072.57 seconds
Optimization time is 2.986114025115967 seconds
The reconstruction error is 0.0219, average process stability is 0.17 and 
the minimum process stability is -0.41 for 25 signatures

Traceback (most recent call last):
  File "/lustre/wangzh/TR/test.py", line 16, in <module>
    main_function()
  File "/lustre/wangzh/TR/test.py", line 13, in main_function
    sig.sigProfilerExtractor("matrix", output, path, reference_genome= Genome, opportunity_genome=Genome, cpu = -1)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 1031, in sigProfilerExtractor
    final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build, add_penalty=0.05, remove_penalty=0.01, mutation_context=mutation_context, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 1349, in signature_decomposition
    merger.write(directory+"/"+contexts[mtype_par]+"_Decomposition_Plots.pdf")
KeyError: 'none'
###

**Comment by ntbeileh** [comment]
Hi,

Your Mutation Types column in your file does not appear to be in the correct format. I have attached an example matrix from the 21BRCA example dataset for reference.

[21BRCA.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/6446630/21BRCA.txt)

**Comment by WZo0o** [comment]
Hi,

I have noted that the format of  Mutation Types column in my file are different from your example file. But my file COAD.SBS18.all.txt was generated by SigProfilerMatrixGenerator based on 
[test.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/6446822/test.txt) so I also checked  the format of  Mutation Types column in files that are generated by SigProfilerMatrixGenerator based on test.txt. Finally, I found that the format of  Mutation Types column in these files are different and only a small number of files have the same format as your example file. 

Can you help me to handle this issue?
Thanks for all the hard work and a great tool!

**Comment by ntbeileh** [comment]
Thank you for the clarification. I was able to reproduce your error. I am looking into it now!

**Comment by mishugeb** [comment]
@ntbeileh I am just checking,  were you able to figure out what is causing the issue?

Thanks,
Mishu

**Comment by mishugeb** [comment]
Hi @WZo0o could you please set the parameter "make_decomposition_plots" =True and run the analysis again? I was able to solve the issue in that way. Here is code I used:

[public_test.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/6525527/public_test.zip)

**Comment by WZo0o** [comment]
Hi @mishugeb ,
I tried to run the analysis with your code and found the same issue. Here is  error reporting information:

"""
Time taken to collect 10 iterations for 3 signatures is 8.23 seconds
Optimization time is 3.02370023727417 seconds
The reconstruction error is 0.1803, average process stability is 0.9 and
the minimum process stability is 0.8 for 3 signatures

Traceback (most recent call last):
  File "/lustre/wangzh/TR/test/public_test/sigpro.py", line 28, in <module>
    run()
  File "/lustre/wangzh/TR/test/public_test/sigpro.py", line 22, in run
    nnls_add_penalty=nnls_add_penalty, nnls_remove_penalty=nnls_remove_penalty, initial_remove_penalty=initial_remove_penalty, make_decomposition_plots=False, get_all_signature_matrices=False, cpu=-1)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 1031, in sigProfilerExtractor
    final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build, add_penalty=0.05, remove_penalty=0.01, mutation_context=mutation_context, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 1349, in signature_decomposition
    merger.write(directory+"/"+contexts[mtype_par]+"_Decomposition_Plots.pdf")
KeyError: 'none'
"""
 
In addition, I noted that code in your script "make_decomposition_plots=False".  So, I seted the parameter  "make_decomposition_plots=True" and run it again. The error is still existed and  here is  error reporting information:

"""
Time taken to collect 10 iterations for 3 signatures is 6.35 seconds
Optimization time is 3.0817880630493164 seconds
The reconstruction error is 0.1805, average process stability is 0.86 and
the minimum process stability is 0.72 for 3 signatures


Traceback (most recent call last):
  File "/lustre/wangzh/TR/test/public_test/sigpro.py", line 28, in <module>
    run()
  File "/lustre/wangzh/TR/test/public_test/sigpro.py", line 22, in run
    nnls_add_penalty=nnls_add_penalty, nnls_remove_penalty=nnls_remove_penalty, initial_remove_penalty=initial_remove_penalty, make_decomposition_plots=True, get_all_signature_matrices=False, cpu=-1)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 1031, in sigProfilerExtractor
    final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build, add_penalty=0.05, remove_penalty=0.01, mutation_context=mutation_context, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 1349, in signature_decomposition
    merger.write(directory+"/"+contexts[mtype_par]+"_Decomposition_Plots.pdf")
"""

Thanks for all the hard work and a great tool!

**Comment by WZo0o** [comment]
Hi @mishugeb ,
I tried to run the analysis with your code and found the same issue. Here is  error reporting information:

"""
Time taken to collect 10 iterations for 3 signatures is 8.23 seconds
Optimization time is 3.02370023727417 seconds
The reconstruction error is 0.1803, average process stability is 0.9 and
the minimum process stability is 0.8 for 3 signatures

Traceback (most recent call last):
  File "/lustre/wangzh/TR/test/public_test/sigpro.py", line 28, in <module>
    run()
  File "/lustre/wangzh/TR/test/public_test/sigpro.py", line 22, in run
    nnls_add_penalty=nnls_add_penalty, nnls_remove_penalty=nnls_remove_penalty, initial_remove_penalty=initial_remove_penalty, make_decomposition_plots=False, get_all_signature_matrices=False, cpu=-1)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 1031, in sigProfilerExtractor
    final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build, add_penalty=0.05, remove_penalty=0.01, mutation_context=mutation_context, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 1349, in signature_decomposition
    merger.write(directory+"/"+contexts[mtype_par]+"_Decomposition_Plots.pdf")
KeyError: 'none'
"""
 
In addition, I noted that code in your script "make_decomposition_plots=False".  So, I seted the parameter  "make_decomposition_plots=True" and run it again. The error is still existed and  here is  error reporting information:

"""
Time taken to collect 10 iterations for 3 signatures is 6.35 seconds
Optimization time is 3.0817880630493164 seconds
The reconstruction error is 0.1805, average process stability is 0.86 and
the minimum process stability is 0.72 for 3 signatures


Traceback (most recent call last):
  File "/lustre/wangzh/TR/test/public_test/sigpro.py", line 28, in <module>
    run()
  File "/lustre/wangzh/TR/test/public_test/sigpro.py", line 22, in run
    nnls_add_penalty=nnls_add_penalty, nnls_remove_penalty=nnls_remove_penalty, initial_remove_penalty=initial_remove_penalty, make_decomposition_plots=True, get_all_signature_matrices=False, cpu=-1)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 1031, in sigProfilerExtractor
    final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build, add_penalty=0.05, remove_penalty=0.01, mutation_context=mutation_context, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg)
  File "/lustre/wangzh/tools/miniconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 1349, in signature_decomposition
    merger.write(directory+"/"+contexts[mtype_par]+"_Decomposition_Plots.pdf")
"""

Thanks for all the hard work and a great tool!

**Comment by mishugeb** [comment]
Hi @WZo0o could you please install the SigProfilerExtractor package from GitHub and let me if that is working?

Thanks,
Mishu

**Comment by WZo0o** [comment]
Hi @mishugeb
Do you mean that I uninstall SigProfilerExtractor that was installed  through the following command "pip install SigProfilerExtractor" and re-install the SigProfilerExtractor package from GitHub?

**Comment by mishugeb** [comment]
Yes, that's correct.

Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WZo0o** [comment]
Hi @mishugeb , after I install the SigProfilerExtractor package from GitHub,  I can run the analysis successfully. 

Thanks for all the hard work and a great tool!
