### ISSUE TITLE
can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by shaoyiZ** [AlexandrovLab/SigProfilerExtractor#79]
Dear Alexandrovlab, 

Good day! I have been trying to use the Sigprofiler extractor tool to generate plots for my De Novo data. 

I was trying the tool out on the sample dataset (example.txt) and successfully got the outputs. When I was trying to use the extractor tool to generate plots, I encountered a problem where python gave the(can only concatenate str (not "int") to str) command. I was using the X_seqinfo.txt file since it was the only output file that contained any columns. 

This is my code:
sig.sigProfilerExtractor(“matrix”,”results”,”/Users/shaoyizhang/Desktop/X_seqinfo.txt”,reference_genome=”GRCh37”,minimum_signatures=1,maximum_signatures=10,nmf_replicates=100,cpu=-1)

The real question here is: which file from the SigProfiler Matrix Generator should I use for the Extractor tool(I was trying to look for a file that has the same format as the 21BRCA.txt but haven't found one)? There is a lot of files and I am fairly new to python. 

Thanks a lot for the support and help!
Shaoyi

**Comment by mishugeb** [comment]
Hi Shaoyi,
You need to a file as input from the output folder of SigProfilerMatrixGenerator. Such as output/SBS/21BRCA_vcf.SBS96.all

Thanks,
Mishu

**Comment by shaoyiZ** [comment]
Dear Mishu, 

That totally solved my problem! Thanks a lot. I have another issue I want to address - When I run the extractor for my DBS.all outputs from MatrixGenerater, the extractor still gave me SBS outputs in the results file. Can you give some insights into what might have caused this issue?

Shaoyi

**Comment by mishugeb** [comment]
Hi @shaoyiZ ,
Sorry that I did not notice your last question and found it when you closed the ticket. I just tested the tool and found it is working correctly at my end. Here is the code I used: 
[Uploading public_test.zip…]()

**Comment by shaoyiZ** [comment]
Hi! Could you please

**Comment by shaoyiZ** [comment]
Hi, no problem at all!

It doesn't seem like I can open the code you shared with me. When I click on it, it just redirects me to this Github page again.

Sincerely, 
Shaoyi

**Comment by mishugeb** [comment]
[public_test.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/6641899/public_test.zip)
@shaoyiZ I attached the zip file again.

**Comment by shaoyiZ** [comment]
Thanks a lot! I was replied in another thread that the current extractor version does not support DBS - it is labeled as SBS but the results are correct. Thanks for the code and the help provided!

Sincerely, 
Shaoyi
