### ISSUE TITLE
problem with results

### ISSUE THREAD

**Issue by WZo0o** [AlexandrovLab/SigProfilerExtractor#80]
Hello,
After successfully running the program, how can I get signature for each variant?

Thank you,
WangZheng

**Comment by mishugeb** [comment]
Hi @WZo0o,
I think the following videos will be helpful to you:

https://www.youtube.com/watch?v=30JmjvJ-DtI
https://www.youtube.com/watch?v=BiBYZz_khIY
https://www.youtube.com/watch?v=BchtNeaQlv0

**Comment by WZo0o** [comment]
Hi @mishugeb,
I have seen the videos that you recommended but I am still confused.
For example, I am  interested in a variation chr19：58864357- A-G，how can I get a signature for this variant?

**Comment by mishugeb** [comment]
Hi @WZo0o,
The tool is not able to detect a signature that is associated with a specific variant.

**Comment by WZo0o** [comment]
Hi @mishugeb，
Do you mean that the tool only can detect a signature for a patient, but this tool is  not able to match the signature  with a variant?
