### ISSUE TITLE
Gave SBS output when input is DBS

### ISSUE THREAD

**Issue by shaoyiZ** [AlexandrovLab/SigProfilerExtractor#81]
When I run the extractor for my DBS.all outputs from MatrixGenerater, the extractor still gave me SBS outputs in the results file. Can you give some insights into what might have caused this issue?

Thanks a lot, 
Shaoyi

**Comment by ntbeileh** [comment]
Could you attach your JOBMETADATA.txt from the run so I can take a look?

**Comment by shaoyiZ** [comment]
Hi!

Thanks for replying! Here is the METADATA:
THIS FILE CONTAINS THE METADATA ABOUT SYSTEM AND RUNTIME


-------System Info-------
Operating System Name: Darwin
Nodename: Shaoyis-Mini
Release: 20.5.0
Version: Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101

-------Python and Package Versions------- 
Python Version: 3.9.5
Sigproextractor Version: 1.0.15
SigprofilerPlotting Version: 1.1.15
SigprofilerMatrixGenerator Version: 1.1.28
Pandas version: 1.2.4
Numpy version: 1.20.3
Scipy version: 1.6.3
Scikit-learn version: 0.24.2

--------------EXECUTION PARAMETERS--------------
INPUT DATA
	input_type: matrix
	output: DBS1-
	input_data: /Users/shaoyizhang/Desktop/DNV-/output/DBS/ASD-.DBS186.all
	reference_genome: GRCh37
	context_types: SBS186
	exome: False
NMF REPLICATES
	minimum_signatures: 1
	maximum_signatures: 10
	NMF_replicates: 100
NMF ENGINE
	NMF_init: nndsvd_min
	precision: single
	matrix_normalization: gmm
	resample: True
	seeds: random
	min_NMF_iterations: 10,000
	max_NMF_iterations: 1,000,000
	NMF_test_conv: 10,000
	NMF_tolerance: 1e-15
CLUSTERING
	clustering_distance: cosine
EXECUTION
	cpu: 8; Maximum number of CPU is 8
	gpu: False
Solution Estimation
	stability: 0.8
	min_stability: 0.2
	combined_stability: 1.0
COSMIC MATCH
	opportunity_genome: GRCh37
	nnls_add_penalty: 0.05
	nnls_remove_penalty: 0.01
	initial_remove_penalty: 0.05
	de_novo_fit_penalty: 0.02
	refit_denovo_signatures: True

-------Analysis Progress------- 
[2021-06-11 18:10:51] Analysis started: 

##################################

[2021-06-11 18:10:51] Analysis started for SBS186. Matrix size [186 rows x 1 columns]

[2021-06-11 18:10:51] Normalization GMM with cutoff value set at 18600

[2021-06-11 18:31:04] SBS186 de novo extraction completed for a total of 1 signatures! 
Execution time:0:20:12

[2021-06-11 18:31:05] Analysis ended: 

-------Job Status------- 
Analysis of mutational signatures completed successfully! 
Total execution time: 0:20:13 
Results can be found in:  DBS1-  folder

**Comment by shaoyiZ** [comment]
Now that I looked into this metadata, it seems like it has started analysis for SBS186, not DBS. But I am pretty sure I directly used the DBS.ALL file that was generated by the matrix generator (as you can see in the input data log).

**Comment by ntbeileh** [comment]
As of now SigProfilerExtractor does not support decomposition plots for DBS186. However all other outputs that you got labeled SBS186 are the correct results corresponding to DBS186. The name is just labeled SBS186 even though they are actually results for DBS186.

**Comment by shaoyiZ** [comment]
Thanks a lot! 

Sincerely,
Shaoyi
