### ISSUE TITLE
Default on cpu floods GPU with processes

### ISSUE THREAD

**Issue by mp15** [AlexandrovLab/SigProfilerExtractor#82]
If you naively set gpu=True whilst cpu=-1 on a system with a large number of cores you end up flooding the GPUs with too many processes. It might be helpful to warn about this in the part of the documentation where the GPU flag is documented as one would not normally expect a CPU flag to affect GPU settings like this (it bit me at least). I'm also wondering whether it might also be helpful to have cpu default to torch.cuda.device_count() when gpu is set to True?

**Comment by mdbarnesUCSD** [comment]
Thanks @mp15 for bringing this up. Updating the parameter description in the README so that users are more aware of this potential issue when working with the gpu and how they can resolve it.

Will look into a more longterm solution for this as well.
