### ISSUE TITLE
Unable to generate full Cosmic signatures with decompose

### ISSUE THREAD

**Issue by snasser** [AlexandrovLab/SigProfilerExtractor#85]
Hi, We would like to generate proportions for all cosmic 96 signatures. I was able to do so in April 2021 but not with the new version. Is this feature disabled? I am using the example provided on the wiki with threshold changes. 
:
#to get all cosmic signatures without filtering
decomp.decompose(signatures, activities, samples, output, genome_build="GRCh37", verbose=False,nnls_add_penalty=0.0, nnls_remove_penalty=0.0, initial_remove_penalty=0.0, de_novo_fit_penalty=0.02)

**Comment by mishugeb** [comment]
I cannot test that issue in my windows setup. May I ask @mdbarnesUCSD or @marcos-diazg to look at the issue?

**Comment by mdbarnesUCSD** [comment]
Hi @snasser,

Could you please include the error message that you are receiving? Also, could you please check which version of SigProfilerExtractor that you are using?

Thanks!

**Comment by mdbarnesUCSD** [comment]
Please reopen if you are still experiencing this issue.
