### ISSUE TITLE
Multiprocessing issue

### ISSUE THREAD

**Issue by KEYS248** [AlexandrovLab/SigProfilerExtractor#88]
The program gets stuck in a continuous loop producing the same error, I believe in an attempt to create subprocesses.

I believe I'm getting the same error as issue #41 
I did not used to get this issue until recently, maybe starting a few weeks ago.
I'm trying to run this software on an Linux cluster with resource management software Slurm which may be inducing this multiprocessing issue.
Is there any way to prevent this error maybe by not attempting to spawn subprocesses? Using the option `cpu=1` does not seem to help. Thanks!

### Error message snippet:

` /multiprocessing/spawn.py, line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.`

**Comment by mishugeb** [comment]
Please use your code inside the **if __name__=="__main__":** idiom.

**Comment by KEYS248** [comment]
Thank you @mishugeb that solved it!
