### ISSUE TITLE
decomp.decompose() with genome_build="rn6" causes error

### ISSUE THREAD

**Issue by monagai** [AlexandrovLab/SigProfilerExtractor#89]
decomp.decompose() with genome_build="rn6" causes the following error.
`UnboundLocalError: local variable 'sigDatabase' referenced before assignment`

Cf. decomp.decompose() with genome_build="mm10" works normally.

Has rn6 not been supported officially yet?
rn6 can be installed using SigProfilerMatrixGenerator, though.

[Environment]
SigProfilerExtractor	   1.1.0
SigProfilerMatrixGenerator 1.1.30
sigProfilerPlotting	   1.1.17
SigProfilerSimulator	   1.1.2

**Comment by mdbarnesUCSD** [comment]
Please update your package to SigProfilerExtractor using:
`pip install --upgrade SigProfilerExtractor`

Please let us know if the problem still exists after doing so.

**Comment by monagai** [comment]
Thank you for your comment. You are correct.
With the latest version, no errors has occurred.
I apologize my primitive mistake.
