### ISSUE TITLE
sigProfilerExtractor gpu solution can't work

### ISSUE THREAD

**Issue by brucewu1996** [AlexandrovLab/SigProfilerExtractor#9]
Hello,

I follow example to execute sigProfilerExtractor with `gpu = True.` But program interrupted after matrix generation and output folder only **job_metadata.txt** and **SBS96/All_solutions_stat.csv** exist. 

Below is command and result.
 `sig.sigProfilerExtractor("vcf",testgpu_output",data,startProcess=1,endProcess=3,totalIterations=1000,gpu = True)`. 

************** Reported Current Memory Use: 0.15 GB *****************

Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 7.81 seconds.
Matrices generated for 15 samples with 0 errors. Total of 93001 SNVs, 505 DINUCs, and 0 INDELs were successfully analyzed.
Extracting signature 1 for mutation type 96
**************************************************************************

What should i do to resolve this issue?

System information is below.

OS: Centos 7
PyTorch Version: 1.2
Python Version: 3.6.8
CUDA/cuDNN Version: 9.2/7.6
GPU Model: NVIDIA Tesla K80

Thanks,
Bruce

**Comment by vellamike** [comment]
dear @brucewu1996 is the command you are using correct? there appears to be hanging `"`:
```
sig.sigProfilerExtractor("vcf",testgpu_output",data,startProcess=1,endProcess=3,totalIterations=1000,gpu = True).
```

Did the application throw any error or did it simply not run? Would it be possible to share your data with us?

**Comment by brucewu1996** [comment]
Dear @vellamike 
My data generate by  this command `path_to_example_folder_containing_vcf_files = sig.importdata("vcf")`. 
This program work successfully by`
sig.sigProfilerExtractor("vcf","testgpu_output",data,startProcess=1,endProcess=3,totalIterations=1000).`
But add `gpu = True` ,the application break in decompose step without any error message.

**Comment by vellamike** [comment]
Thank you @brucewu1996  - is it possible to share your vcf file with me? This will make it easier to solve the problem

**Comment by brucewu1996** [comment]
@vellamike Thank for your response. 
I recently retry GPU solution by following command.

`path_to_example_vcf = sig.importdata("vcf")
data = path_to_example_vcf
sig.sigProfilerExtractor("vcf", "example_output", data,gpu = True)`

This time i got an error message :

`Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/lib/python3.6/site-packages/sigproextractor/subroutines.py", line 298, in pnmf
    W, H = nmf_fn(bootstrapGenomes,totalProcesses)  #uses custom function nnmf
  File "/usr/lib/python3.6/site-packages/sigproextractor/subroutines.py", line 218, in nnmf_gpu
    gpu_id = identity % torch.cuda.device_count()
NameError: name 'torch' is not defined` 

I confirm pytorch-GPU version have been installed in my system.

`torch.cuda.is_available()
True`
What should i do to resolve this issue?

Thanks,
Bruce

**Comment by vellamike** [comment]
Dear @brucewu1996 can you try on the latest version of sigprofilerextractor? It might be also worth trying in a conda or virtualenv environment, it looks like this multiprocessing pools are not able to import torch - this error seems to be related to your system's configuration.

**Comment by brucewu1996** [comment]
Thank you @vellamike .
This bug be fixed by using virtual environment.
But another bug appear, i executed extractor with following command :
`from sigproextractor import sigpro as sig`
 `path_to_example_table = sig.importdata("vcf")`
`data = path_to_example_vcf`
`sig.sigProfilerExtractor("vcf", "example_output", data, startProcess=1, endProcess=10,totalIterations = 100,gpu = True)`

And then application break in decompose step without any error message.
Below is JOB_MATADATA.txt context of this test.

THIS FILE CONTAINS THE METADATA ABOUT SYSTEM AND RUNTIME


-------System Info-------
Operating System Name: Linux
Nodename: deepvariant
Release: 3.10.0-862.el7.x86_64
Version: #1 SMP Fri Apr 20 16:44:24 UTC 2018

-------Python and Package Versions------- 
Python Version: 3.7.4
Sigproextractor Version: 0.0.5.77
SigprofilerPlotting Version: 1.0.10
SigprofilerMatrixGenerator Version: 1.0.22
Pandas version: 0.25.1
Numpy version: 1.17.2
Scipy version: 1.3.1
Scikit-learn version: 0.21.3
Nimfa version: 1.4.0

-------Vital Parameters Used for the execution -------
input_type: vcf
inputdata: vcftest
startProcess: 1
endProcess: 10
totalIterations: 100
cpu: -1
hierarchy: False
refgen: GRCh37
genome_build: GRCh37
mtype: ['default'] 
init: nndsvdar

-------Date and Time Data------- 
Date and Clock time when the execution started: 2019-11-21 20:58:33.981886

Please give me some advise to solve this problem.

Thanks,
Bruce

**Comment by mishugeb** [comment]
Hi Bruce,
I will look at what is happening there. But for now, could you please update your scipy library and try to run the tool again?

Thanks,
Mishu

**Comment by brucewu1996** [comment]
@mishugeb thanks for your prompt response.I already upgraded my scipy to version 1.3.2 ,but problem still exist.Maybe you can provide a list of installed package's version ?I can create another conda environment to test.

Thanks,
Bruce

**Comment by mishugeb** [comment]
Hi Bruce,
All the required packages should be installed automatically when you install this package. If there is any error, that will be detected by Travis CI and the build will not pass eventually. I will check that more, but it difficult to replicate an issue if Travis  CI cannot detect that. Sorry for the inconvenience. I will check that more thoroughly. 

Regards,
Mishu

**Comment by mishugeb** [comment]
Hi Bruce,
Could you please install the most recent tool "pip3 install SigProfilerExtractor" and check if you get the error?

Thanks
