### ISSUE TITLE
sigProfilerExtractor() (v1.1.3) cannot handle vcf which contain "," in ALT column.

### ISSUE THREAD

**Issue by monagai** [AlexandrovLab/SigProfilerExtractor#90]
sigProfilerExtractor() (v1.1.3) cannot handle vcf files which contain "," in ALT column.
(NMF analyses is not executed if one of vcf files contains "," in ALT column.
Cf. sigProfilerExtractor() (v1.1.0) can handle such vcf files.
     Is it a revised specification?

[environment]
genome: rn6
input_type: vcf
sigProfilerExtractor: 1.1.3
python: 3.8.5, 3.9.6

**Comment by marcos-diazg** [comment]
SigProfilerExtractor creates the input mutational matrix from VCF files using [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator). Can you please check that you are using the latest version of this package (1.1.31)? You can do that by checking the `JOB_METADATA.txt` file.

Please let us know if the problem still exists after doing so.

**Comment by monagai** [comment]
I really thank you for comment.
I'm using SigProfilerMatrixGenerator 1.1.13.
I think it is the latest version.

**Comment by marcos-diazg** [comment]
Dear @monagai. Thank you for your interest. That is indeed the latest version of SigProfilerMatrixGenerator. Are you using it for both SigProfilerExtractor v1.1.3 and v1.1.0? Could you please include the error message that you are receiving?

It would also be great if you can share your input data to try to replicate the issue on our end.

**Comment by monagai** [comment]
The same situation has occured editing the sample 21BRCA_vcf provided at` https://osf.io/t6j7u/wiki/2.%20Quick%20Start%20Example`.

**Comment by marcos-diazg** [comment]
I tried to reproduce your error, but I was able to correctly run the latest version of SigProfilerExtractor after editing one of the sample VCF files you mentioned. Can you please share the error message you are receiving as well as the commands used, the `JOB_METADATA.txt` file, and the edited sample file you are trying to run? Thanks!

**Comment by monagai** [comment]
Sorry for bothering you...!
I found only 1 line in 1 vcf in my data causes the error. But it does not seem general.
Please wait for a while. I will show you as much as accurate information.

**Comment by marcos-diazg** [comment]
No problem. I would also recommend you installing a conda environment exclusively dedicated to SigProfilerExtractor latest version. You can do that following these commands:

```
conda create --name sigprofilerextractor -y
conda activate sigprofilerextractor
conda install python -y
git clone https://github.com/AlexandrovLab/SigProfilerExtractor.git
cd SigProfilerExtractor
pip install .
```

**Comment by monagai** [comment]
Here is a vcf sample and the result.

Mac OS X, 10.14.6
SigProfilerExtractor       1.1.3
SigProfilerMatrixGenerator 1.1.31
sigProfilerPlotting        1.1.17

```
Python 3.8.5 (default, Jul 21 2020, 10:42:08) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from SigProfilerExtractor import sigpro as sig
>>> sig.sigProfilerExtractor("vcf", "results_ng", "vcf_ng", opportunity_genome="rn6", reference_genome='rn6', minimum_signatures=1, maximum_signatures=2, nmf_replicates=10, context_type='SBS96')

************** Reported Current Memory Use: 0.19 GB *****************

Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 19.65 seconds.
Starting matrix generation for INDELs...>>> 
```
The 1st line in attached vcf/b1_ng.vcf is:
`chr3    98574090        .       C       A,T     .       PASS    SOMATIC`
sigProfilerExtractor works correctly with removing this line.
[vcf_ng.tar.gz](https://github.com/AlexandrovLab/SigProfilerExtractor/files/7003755/vcf_ng.tar.gz)
[results_ng.tar.gz](https://github.com/AlexandrovLab/SigProfilerExtractor/files/7003757/results_ng.tar.gz)

**Comment by mdbarnesUCSD** [comment]
Hi @monagai,

SigProfilerExtractor uses [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator) to process the VCF file which requires that there only be a single alternate allele. Please make such modifications to your input VCF file before using it as input for SigProfilerExtractor. 

Thanks!

**Comment by monagai** [comment]
Hi @mdbarnesUCSD,
I really thank you for your comment.
I undestand.
