### ISSUE TITLE
UnboundLocalError: local variable 'sequence' referenced before assignment

### ISSUE THREAD

**Issue by YingYa** [AlexandrovLab/SigProfilerExtractor#93]
************** Reported Current Memory Use: 0.22 GB *****************

Extracting signature 1 for mutation type 96
The matrix normalizig cutoff is 33064

process 1 continues please wait...
execution time: 12 seconds

process 1 continues please wait...
execution time: 12 seconds

process 1 continues please wait...
execution time: 13 seconds

Time taken to collect 3 iterations for 1 signatures is 35.09 seconds
Optimization time is 12.692027807235718 seconds
Traceback (most recent call last):
  File "./03Signatures_Extractor.py", line 81, in <module>
    main()
  File "./03Signatures_Extractor.py", line 71, in main
    sig.sigProfilerExtractor(args.input_type, args.out_put, args.input_data, reference_genome=args.reference_genome, opportunity_genome=args.opportunity_genome, context_type=args.context_type, exome=args.exome,
  File "/path/to/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 900, in sigProfilerExtractor
    sub.export_information(loopResults, m, layer_directory, index, colnames, wall=wall, sequence=sequence)
UnboundLocalError: local variable 'sequence' referenced before assignment

**Comment by mdbarnesUCSD** [comment]
Hi @YingYa,

Could you please provide the JOB_METADATA file?

Thanks!

**Comment by YingYa** [comment]
Hi @mdbarnesUCSD ,

Sorry I have deleted that file, I can generate it again if you need.

I could run succefully after I modified '/path/to/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py':
add 'sequence="genome"' after '#set the squence type ("genome" or "exome") for the tmb plot inside the make_final_solution function'

Thanks!

**Comment by YingYa** [comment]
Hi @mdbarnesUCSD , 

Annother error when I run with 'context_type ID96' : The matrix does not match the correct SBS96 format. Please check you formatting and rerun this plotting function.

Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @YingYa,

If you would like to run with the context type SBS96, then set context_type="96". Set context_type to "ID" for analysis of indels.

**Comment by mdbarnesUCSD** [comment]
Please reopen this issue or a new one if you are encountering any problems.
