### ISSUE TITLE
[Errno 28] No space left on device when importing SigProfilerExtractor

### ISSUE THREAD

**Issue by hannanw** [AlexandrovLab/SigProfilerExtractor#95]
Hi,

I ran across this error when importing SigProfilerExtractor 

`>>> from SigProfilerExtractor import sigpro as sig
/home/hannan/anaconda3/lib/python3.7/site-packages/joblib/_multiprocessing_helpers.py:53: UserWarning: [Errno 28] No space left on device.  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))`

I checked both the memory and disk space and there is sufficient memory on both of them.

![Screenshot from 2021-09-20 11-37-30](https://user-images.githubusercontent.com/67099718/133954893-86df22f3-100f-4978-abee-d54743dc7e7a.png)

Here is the traceback when I tried to run the tool

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hannan/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 823, in sigProfilerExtractor
    i = i)
  File "/home/hannan/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 789, in decipher_signatures
    results = parallel_runs(excecution_parameters, genomes=genomes, totalProcesses=totalProcesses, verbose = False)
  File "/home/hannan/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 685, in parallel_runs
    pool = multiprocessing.Pool()
  File "/home/hannan/anaconda3/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/hannan/anaconda3/lib/python3.7/multiprocessing/pool.py", line 158, in __init__
    self._setup_queues()
  File "/home/hannan/anaconda3/lib/python3.7/multiprocessing/pool.py", line 251, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/home/hannan/anaconda3/lib/python3.7/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/home/hannan/anaconda3/lib/python3.7/multiprocessing/queues.py", line 332, in __init__
    self._rlock = ctx.Lock()
  File "/home/hannan/anaconda3/lib/python3.7/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/home/hannan/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/home/hannan/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 28] No space left on device`

I was wondering if this error could be coming from the SigProfiler package or from the joblib/multiprocessing package? Any suggestions/insights would be much appreciated, thanks!

Warmest regards,
Hannan

**Comment by mdbarnesUCSD** [comment]
Hi @hannanw,

Could you please verify if this is from the joblib/multiprocessing package by starting an interactive python session and importing the multiprocessing package?

`import multiprocessing`

Thanks!

**Comment by hannanw** [comment]
Hi,

I still see the error even after importing the multiprocessing package. 

`Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.`
`>>> import multiprocessing`
`>>> from SigProfilerExtractor import sigpro as sig`
`/home/hannan/anaconda3/lib/python3.7/site-packages/joblib/_multiprocessing_helpers.py:45: UserWarning: [Errno 28] No space left on device.  joblib will operate in serial mode warnings.warn('%s.  joblib will operate in serial mode' % (e,))`
`>>>`

I asked the person in charge of the server where I am trying to run the SigProfiler package and he said that there is still 1.1TB on the `/` and `/tmp` so I don't really know why I am getting this error. Sorry, I'm still quite new to computer science any help/suggestion would be greatly appreciated.

Warmest regards,
Hannan

**Comment by marcos-diazg** [comment]
Hi Hannan,

I hope you are doing great and thanks for your interest in our tool! I would strongly suggest using an exclusive conda environment for running SigProfilerExtractor since your error could be due to incompatibilities in your base anaconda environment. You can do that by using the following commands, hope that helps.

```
conda create --name sigprofilerextractor -y
conda activate sigprofilerextractor
conda install python -y
git clone https://github.com/AlexandrovLab/SigProfilerExtractor.git
cd SigProfilerExtractor
pip install .
```

**Comment by hannanw** [comment]
Hi Marcos,

Nice to see you again! Thanks for your suggestion, but it still seems like the same error is still occurring as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/67099718/134534632-129f1a2d-60fe-4c18-ab3f-fccc18ebe8a4.png)

Warmest regards,
Hannan

**Comment by marcos-diazg** [comment]
Hi again Hannan!

Please have a look at the first answer [here](https://stackoverflow.com/questions/40115043/no-space-left-on-device-error-while-fitting-sklearn-model). That should solve your issue since it seems that your `/dev/shm` is full. Hope that helps.

Best wishes,

Marcos

**Comment by hannanw** [comment]
Hi Marcos,

Thanks! That suggestion worked, I am able to import and run SigProfilerExtractor now without issue.

Warmest regards,
Hannan
