### ISSUE TITLE
Discrepancy of default value in README.md

### ISSUE THREAD

**Issue by WuyangFF95** [AlexandrovLab/SigProfilerExtractor#99]
Dear Alexandrov Lab members,

I'm a user of the previous sigproextractor package (v0.0.5.77). I have some questions related to the new SigProfilerExtractor:

From the [PyPI](https://pypi.org/project/SigProfilerExtractor/) and [GitHub](https://github.com/AlexandrovLab/SigProfilerExtractor/) repositories of SigProfilerExtractor package, there seems to have two discrepant default values for parameter `**nmf_init**`:

In the earlier part of README which listed the actual default values of the function sigProfilerExtractor():
```
sigProfilerExtractor(... ,nmf_init="random", ...)
```

In the later part of README, however, there is a table describing the significance of parameters in detail, and there is a cell saying that:

```
nmf_init | String | The initialization algorithm for W and H matrix of NMF. Options are 'random', 'nndsvd', 'nndsvda', 'nndsvdar' and 'nndsvd_min'. Default is 'nndsvd_min'.
```

Can you briefly introduce these algorithms for initialization of W and H matrices? Also, can you tell me whether I should choose "random" or "nndsvd_min"? Does "nndsvd_min" always generate identical W and H initialization if identical V is given in each NMF replicate (i.e. Poisson noise was not added to V in each NMF replicate)?

**Comment by mdbarnesUCSD** [comment]
Hi @WuyangFF95,

The sigproextractor package (v0.0.5.77) is deprecated please use [pypi to install SigProfilerExtractor](https://pypi.org/project/SigProfilerExtractor/) instead. Additionally, "random" is now selected by default for its improved performance and "nndvsvd_min" should generate identical W and H initializations given identical V's.
